### ISSUE TITLE
If customer email is available, send message to them via email if they are offline

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#107]
Right now if a customer goes offline and we respond, they won't see the message unless they come back to the page and open the widget -- would be nicer if they could get answers to their questions/comments via email if possible.

**Comment by jalberto** [comment]
I also will like to see the possibility of continue conversations by email.

I suggest SMTP as a base integration (as most providers have this option) then add integrations with other providers (my prefered provider is Mailgun as it has a nice API and EU/US servers)

**Comment by reichert621** [comment]
closing as duplicate of https://github.com/papercups-io/papercups/issues/151, will update that ticket with notes from here
