### ISSUE TITLE
Add ability to delete a conversation

### ISSUE THREAD

**Issue by fabborke** [papercups-io/papercups#113]
For privacy reasons there should be the possibility to delete a conversation from the server.

[Edit from @reichert621]
Before we can fully support this, we'll need to fix some foreign key issues... namely, when a conversation is deleted, we should probably auto-delete all associated messages/slack threads/etc

**Comment by reichert621** [comment]
great idea 👍

**Comment by reichert621** [comment]
(need to QA this before closing)

**Comment by reichert621** [comment]
(there were some issues with the PR above, need to fix some data issues before enabling this... e.g. db does not allow deleting certain resources due to current foreign key constraints)

**Comment by reichert621** [comment]
done with https://github.com/papercups-io/papercups/pull/331 🎉
