### ISSUE TITLE
Show notifications of closed conversations

### ISSUE THREAD

**Issue by fabborke** [papercups-io/papercups#114]
There are no notifications for closed conversations in the dashboard. Only an email is sent. Closed conversation notifications should still be displayed.

Alternatively, closed conversations should no longer be displayed in the client and a new conversation should be started.

**Comment by reichert621** [comment]
we plan on re-opening a conversation if a new message gets sent after it's closed :) (see https://github.com/papercups-io/papercups/issues/89)

**Comment by reichert621** [comment]
fixed in https://github.com/papercups-io/papercups/pull/116

let me know if this is still an issue!
