### ISSUE TITLE
Add ability to remove users from team

### ISSUE THREAD

**Issue by cheeseblubber** [papercups-io/papercups#121]

**Comment by reichert621** [comment]
hmm I wonder if we should add "roles" to users first, so that only admin can do this? or should anyone on a team be able to remove anyone else?

**Comment by ZmagoD** [comment]
I would like to work on this but I have few questions how should this behave.
 

- Who is the the admin of the account the one that create it?
- What happen if there is an account with many users and the one that is the admin leaves the company where he/she works, should he/she be able to grand the admin privileges to other user?
- If this is the case then can an admin remove another admin? Maybe in this case we have to check that the account has at least one admin 🤔 
- Right now everyone can invite people to join the account. If we have the role admin should we limit this action just for admins?

**Comment by reichert621** [comment]
hey @ZmagoD! I think we still need to figure out the answers to your questions before we can start working on this -- I would hold off on this until we sort out how roles should work 😅

**Comment by cheeseblubber** [comment]
* The first admin should be the account that is created
* Admin should be able to make other people admins
* Admin can demote (convert the user in to a non admin) and you can demote yourself but there must always be a single admin
* Only Admins should be able to invite right now

Migration wise we could just make everyone an admin when we introduce this feature.

**Comment by reichert621** [comment]
the "ability to remove users from team" is done in https://github.com/papercups-io/papercups/pull/242, so closing this -- still need to handle some UX around giving/revoking admin privileges, but will track that separately
