### ISSUE TITLE
Google Tag Manager Issue / Broken in Chrome?

### ISSUE THREAD

**Issue by masonhensley** [papercups-io/papercups#126]
Hello,

I just did a fresh install on heroku with the deploy button. 

I'm getting an error in chrome, even when I turn off ublock origin.

With uBlock on:
![image](https://user-images.githubusercontent.com/534165/90048570-b869ac80-dca1-11ea-841c-1bafeadb0241.png)

With uBlock off:
![image](https://user-images.githubusercontent.com/534165/90049068-4f366900-dca2-11ea-9b97-4d5ae825ebf8.png)

**Comment by reichert621** [comment]
hey @masonhensley! sorry for the delay on this -- is this still an issue, or can i close it?

**Comment by reichert621** [comment]
closing, but feel free to reopen if still an issue!
