### ISSUE TITLE
Ability to Disable Registration

### ISSUE THREAD

**Issue by masonhensley** [papercups-io/papercups#127]
Hello,

I couldn't find a way to disable registration after creating the initial account (also tried to look through the source/docs).
Is there a way to prevent anyone from creating a new org on my deployment?

If it hasn't been build/spec'd yet, here's a potential direction:

**As an** Admin
**I want** to restrict outside registration
**So that** my instance of papercups is secure

Options:
- environment variable like `REGISTRATION_DISABLED=true` that would default to false if not set (might be the quickest V1)
- switch in UI

Other considerations:
- how does an admin know once they set it the deployment that other instances have not been registered?

Like the direction & plan to use this 🤓

**Comment by reichert621** [comment]
hey @masonhensley! sorry for the delay on this -- we'll probably start off with just an environment variable like you suggested, but long term we'd like to have a better UI for managing this kind of thing :) 

to check if other instances have been registered, you would probably have to query your db through heroku -- happy to help you figure that out if you need!

**Comment by reichert621** [comment]
closing for now, feel free to reopen if you notice any issues with this!
