### ISSUE TITLE
Add ability to change the widget icon

### ISSUE THREAD

**Issue by cheeseblubber** [papercups-io/papercups#140]

**Comment by reichert621** [comment]
@cheeseblubber mind elaborating on this? i.e. do people want to pass in an image, svg, or what? do they also want control over the "x" icon?

**Comment by reichert621** [comment]
Done, we currently support passing in an image url to replace the icon

**Comment by rozenmd** [comment]
@reichert621 Is this documented anywhere? 

Trying to work out how to replace the chat icon with a custom image, only related option I can see is `iconVariant?: 'outlined' | 'filled';`
