### ISSUE TITLE
Add read receipts

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#143]
Be able to tell if/when the other person in the conversation has seen the message.

(Not sure the best way to implement this yet, may want to flesh out the details here first)

**Comment by alisinabh** [comment]
Hi,

First of all, I really like this project. :heart: 

From my past experience in developing a chat service, We can create a table with a compound primary key on `conversation_id+user_id` and a `last_read_message_id` field. When a user sends a read receipt we can upsert the `last_read_message_id` in this table if the new message is newer than the last one registered here.

This way in frontend we only need to send the read receipts for the last message in every conversation.

**Comment by cheeseblubber** [comment]
This has been merged in on the dashboard side
