### ISSUE TITLE
Save widget settings onChange (with debounce) instead of onBlur

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#144]
If someone changes an input and then refreshes the page, the latest value won't persist because the "blur" event wasn't fired.

Let's handle updating the widget settings `onChange` (with maybe a 400ms debounce) instead, so the save happens automatically more or less.

All the changes will be in this file: https://github.com/papercups-io/papercups/blob/master/assets/src/components/account/GettingStartedOverview.tsx#L245

This is the page where these inputs live:
<img width="1359" alt="Screen Shot 2020-08-14 at 9 56 08 AM" src="https://user-images.githubusercontent.com/5264279/90257185-ce4bae80-de14-11ea-8d91-d02de25a2ea0.png">

**Comment by reichert621** [comment]
@oddadmix let me know if you wanna take this!

**Comment by Oddadmix** [comment]
Please assign it and I will work on it.

**Comment by Oddadmix** [comment]
@reichert621, PR created 
https://github.com/papercups-io/papercups/pull/147

**Comment by Oddadmix** [comment]
@reichert621 I can take up more UI issues/tasks. Let me know

**Comment by reichert621** [comment]
thanks @Oddadmix i'll cc you in any good UI issues that come up :)
