### ISSUE TITLE
Flash number of unread messages on the top of tab 

### ISSUE THREAD

**Issue by cheeseblubber** [papercups-io/papercups#148]
We currently display the number of unread messages at the top of the tab, but we should enhance this by making it "flash" to draw the user's attention.

Old example:
![118009002_942090216255467_1862770315944140461_n](https://user-images.githubusercontent.com/4218509/90293426-e1707580-de38-11ea-8570-d739519586a1.png)

**Comment by josephecombs** [comment]
(This feature should mimic the way Brex "flashes" the page Title to draw the user's attention)

**Comment by simran2607** [comment]
can u pls elaborate

**Comment by reichert621** [comment]
@simran2607 by "flash" we mean the html title should show `(2) New messages!` (wait 1s) -> `Papercups` (wait 1s) -> `(2) New messages!` -> etc, so that it's more eye catching

**Comment by Aditya135** [comment]
Hi @reichert621 , can you assign this one to me?

**Comment by reichert621** [comment]
sure @Aditya135!
