### ISSUE TITLE
Add company name to Account Overview page

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#157]
Show the company name on the account overview page and make it editable (see user profile for editable input examples)

Let's add it in this section:
<img width="945" alt="Screen Shot 2020-08-16 at 9 32 04 PM" src="https://user-images.githubusercontent.com/5264279/90349518-2991c280-e008-11ea-8191-21e02d310725.png">

**Comment by lukewaring** [comment]
Hi, is this a time-sensitive issue, or is there anything else I should know? I worked on it a little today and have everything functioning except getting the updates to persist properly. I'm aiming to wrap it up this week but just wanted to make sure it wasn't something more pressing. Thanks!

**Comment by reichert621** [comment]
hey @lukewaring! it's not _too_ urgent, but definitely something I'd like to get done by end of week if possible :) feel free to open a WIP pull request in the meantime if you want!
