### ISSUE TITLE
Chat icon is in the middle of the window, not in the bottom

### ISSUE THREAD

**Issue by heyarviind** [papercups-io/papercups#159]
I have installed it on my nuxt app using Tailwind CSS and when I installed papercups, the chat icon got placed in the middle of the window, not in the bottom.

See screenshot for the reference 

<img width="409" alt="Screenshot 2020-08-17 at 8 56 48 AM" src="https://user-images.githubusercontent.com/21043614/90354871-2cbc9b00-e068-11ea-928a-d1bb9fd23e70.png">

**Comment by reichert621** [comment]
hey @heyarviind! sorry to see you're having issues 😓 it's a little hard for me to tell what's going wrong from the screenshot -- is there a way you can share a link or take a screenshot of what the CSS looks like for the chat icon component?

**Comment by heyarviind** [comment]
Sorry, I got the issue and it was from my end

**Comment by reichert621** [comment]
@heyarviind mind letting me know what the issue was so that other people can avoid it in the future? 😄

**Comment by heyarviind** [comment]
I was setting the height of  "body > div > div" to 100% which was overwriting papercups' widget CSS. I don't know why I did this in the first place 😅

**Comment by reichert621** [comment]
I see! thanks for explaining 👍 we should probably fix the widget so it's unaffected by that anyway 😛

**Comment by heyarviind** [comment]
Yes, but if someone would change CSS just by doing body > div > div then a lot of things can be affected. We can find the solution for this too.

Anyways, the widget is live at https://helppie.me/

**Comment by reichert621** [comment]
awesome! by the way if you want to customize the widget to match the colors on your website, you can set `primaryColor: '#5E23E2'` so it shows up as purple :)

**Comment by heyarviind** [comment]
Yes I did it, you can check now ☺️

**Comment by heyarviind** [comment]
Everything is awesome except the message sending time. I am opening an issue and try to raise a PR if I am able to solve it

**Comment by reichert621** [comment]
good to know, is the issue that the message sending is slow, or the time is incorrect?

**Comment by heyarviind** [comment]
message sending is slow, you can refer to this issue https://github.com/papercups-io/papercups/issues/162

**Comment by reichert621** [comment]
thank you!

**Comment by heyarviind** [comment]
plus I am using papercups on my website in return I can offer a premium package for free of https://helppie.me

let me know if you need it anytime
