### ISSUE TITLE
Can you i run a Modified Version on my Server?

### ISSUE THREAD

**Issue by TDRMinecraft** [papercups-io/papercups#161]

**Comment by reichert621** [comment]
hey @TDRMinecraft! can you provide some more details around what you would like to modify?

you can certainly fork the repo, modify the code, and deploy it to your own server :)

**Comment by TDRMinecraft** [comment]
> hey @TDRMinecraft! can you provide some more details around what you would like to modify?
> 
> 
> 
> you can certainly fork the repo, modify the code, and deploy it to your own server :) 

Sorry just in the Moment my Problem disappeared... Sorry @reichert621
