### ISSUE TITLE
Should show the message in window instantly, not after it is sent successfully

### ISSUE THREAD

**Issue by heyarviind** [papercups-io/papercups#162]
When I send a message, it takes 2-3 seconds to appear in the chat window after I hit enter.

It should show instantly in the chat window for better UX and keep on sending in the background

**Comment by reichert621** [comment]
thanks for reporting this @heyarviind -- looks like this is similar to https://github.com/papercups-io/papercups/issues/99 

i'll try to fix it today!

**Comment by reichert621** [comment]
@heyarviind this should be fixed now, but let me know if you have any issues!

(btw if you're using the React component of our chat widget, you might want to upgrade to version `1.0.25` 😄 )

**Comment by heyarviind** [comment]
I am using the vanilla javascript version not react version so I am good :)

I will test it out and let you know

**Comment by heyarviind** [comment]
Working so smooth now 😎. Thank you for fixing it

Cheers

**Comment by reichert621** [comment]
glad to hear it! 🎉
