### ISSUE TITLE
Add agent's availability in chat widget

### ISSUE THREAD

**Issue by rosinghal** [papercups-io/papercups#165]
It would be helpful for users to see if any agent is online. We can even have offline mode.

Currently there is nothing shown irrespective of agent's availability.

**Comment by reichert621** [comment]
good idea @rosinghal! what do you think is the best way to display this information in the chat?

**Comment by rosinghal** [comment]
@reichert621 
**When agents are available**
Open chat window - 'Agents availlable'
Close chat window - show default color

**When agents are not available**
Open chat window - 'Agents not availlable'
Close chat window - gray color the chat icon

**Comment by reichert621** [comment]
@rosinghal I'm thinking of starting off with a pretty simple UI for this, something like:
<img width="417" alt="Screen Shot 2020-09-05 at 2 39 19 PM" src="https://user-images.githubusercontent.com/5264279/92311515-a8ce4280-ef85-11ea-82b1-40fe9bfa41bf.png">

what do you think?

**Comment by rosinghal** [comment]
@reichert621 
Looks, nice. What about when agents are not available?

**Comment by reichert621** [comment]
maybe just this for now?
<img width="397" alt="Screen Shot 2020-09-05 at 10 24 53 PM" src="https://user-images.githubusercontent.com/5264279/92316775-a3451c80-efc6-11ea-8845-c4c3f2390f3b.png">

**Comment by rosinghal** [comment]
Looks good @reichert621.

**Comment by reichert621** [comment]
(I'll also make the text editable in case you want to customize it, e.g. "We're not available at the moment" vs "Agents are offline")

**Comment by reichert621** [comment]
@rosinghal @timgl this should be ready now in our latest version! (https://github.com/papercups-io/chat-widget/pull/46)

for this to work, just add the following to your config:
```js
config: {
  // ...
  showAgentAvailability: true,
  // ...and if you want to customize the text:
  // agentAvailableText: "Agents available",
  // agentUnavailableText: "Agents not available",
}
```

let me know if you have any issues!

**Comment by reichert621** [comment]
actually seeing some issues with this in production for some reason, reopening for now 😞

**Comment by reichert621** [comment]
should be fixed now 🤞
