### ISSUE TITLE
Mattermost instead of Slack

### ISSUE THREAD

**Issue by nt7** [papercups-io/papercups#168]
Hi, 

I wanted to ask if there is a way to chat via Mattermost, whose webhooks work similarly compared to Slacks's webhooks.
Has this been tried yet? 
The combination of both would be an optimal open-source solution for us.

**Comment by reichert621** [comment]
Makes a lot of sense! We definitely want to make it easy to connect to Mattermost. 

We're still trying to figure out which integrations to prioritize based on the feedback so far, but Mattermost will likely be near the top of that list :) 

are you currently using Mattermost, or planning to soon?

**Comment by nt7** [comment]
Great to hear, yes we are currently using MM

**Comment by reichert621** [comment]
thanks @nt7! at the moment the way our Slack integrations works is by creating a new "thread" for every new conversation started via Papercups -- I did a bit of research into Mattermost and it ~seems like they don't currently support adding/reading messages from threads via their webhooks :( 

so we might have to take a slightly different approach... maybe we'll have to create a new "channel" for every new conversation? 🤔

**Comment by nt7** [comment]
You can "reply" to a single message to [create a thread](https://docs.mattermost.com/help/messaging/sending-messages.html#replying-to-messages).

I think it works similar in Slack.

I wouldn't create a new "channel" for every conversation, imo.

**Comment by reichert621** [comment]
yup, I noticed you can reply to messages to create a thread, but I'm not seeing anything in the webhook event that points to the appropriate thread 😕 (and I agree that creating a new channel per conversation is not ideal... would really like to figure out how to get it working with threads)

for example, when i look at the webhook event, this is what i see for the first message:
```
%{
  "channel_id" => "ch_xxx",
  "channel_name" => "town-square",
  "file_ids" => "",
  "post_id" => "post_a",
  "team_domain" => "test",
  "team_id" => "team_xxx",
  "text" => "ping",
  "timestamp" => 1_597_773_847_952,
  "token" => "tok_xxx",
  "trigger_word" => "",
  "user_id" => "user_xxx",
  "user_name" => "alex"
}
```
...and this is what i see for the "reply" message (which shows up in a thread in the UI)
```
%{
  "channel_id" => "ch_xxx",
  "channel_name" => "town-square",
  "file_ids" => "",
  "post_id" => "post_b",
  "team_domain" => "test",
  "team_id" => "team_xxx",
  "text" => "pong",
  "timestamp" => 1_597_773_910_770,
  "token" => "tok_xxx",
  "trigger_word" => "",
  "user_id" => "user_xxx",
  "user_name" => "alex"
}
```
as far as i can tell, there's no way to tell that those messages are in the same thread -- right? (whereas slack has a `thread_ts` field which allows us to identify this)

**Comment by nt7** [comment]
Interesting...
Yeah, this seems to not be a thing in MM (yet) :(

https://github.com/mattermost/mattermost-server/issues/10463

https://github.com/mattermost/mattermost-plugin-jira/issues/492

**Comment by reichert621** [comment]
boooo... I guess we'll have to figure out a workaround for the time being 😞

**Comment by reichert621** [comment]
hmm interesting! I'll check it out 🙂

**Comment by nt7** [comment]
hi, 
I wanted to revisit this thread to see if there have been any upgrades on the mattermost chat?
Thank you for all your efforts!
Best,

**Comment by reichert621** [comment]
hey @nt7! not yet 😞 sorry -- it's been a bit low on the priority list, but if more people start asking for it we'll definitely bump it up! it's definitely something we'd like to get around to eventually 👍

**Comment by reichert621** [comment]
@nt7 we're working on a mattermost integration this week! just wanted to let you know in case you're still interested in trying it out :)

**Comment by nt7** [comment]
Wow, that's great to hear! 
I'm keen to try it out :)

**Comment by reichert621** [comment]
@nt7 if you want to give it a shot, here are the docs 😄 https://docs.papercups.io/reply-from-mattermost

it's still in the early stages, so happy to hop on a call and walk you through it if that would help!

**Comment by cheeseblubber** [comment]
Closing since this is merged in
