### ISSUE TITLE
[feature request] disable signup, instead create a user when init

### ISSUE THREAD

**Issue by ruruiye** [papercups-io/papercups#180]
papercups is a great software! I am look into the code for a while now, and want to deploy a instance into our company as customer support. but there is some issue came for a standard alone deployment:

Since our system need to access via internet, which means the login page and signup page is also available via internet, but in our case, we don't want to allow signup, instead we just need one account, and then invite user. so we need an option to disable signup. (better if no signup UI)

one option is to provide an option to disable signup feature, but enable an init user when start up. setup the user email, company, password, etc via system environment, and then register the user automaticallly.

**Comment by MuhammadMullah** [comment]
yeah, I think I agree. We should probably the admin invite other users. This also reminds me of another feature which is part of the admin's roles. let me create a ticket for that

**Comment by reichert621** [comment]
thanks @MuhammadMullah!

**Comment by reichert621** [comment]
I believe this is fixed now, but feel free to reopen if not!
