### ISSUE TITLE
Supporting uploading images/attachments to messages in chat

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#181]
A lot of people have requested the ability to send screenshots in particular. I guess a workaround we can recommend in the meantime is to just upload images to certain websites and share the links, but we should definitely support uploading images/attachments to messages at some point.

**Comment by alexanderadam** [comment]
What is the difference to #130? :thinking: 

**PS:** Thank you so much for papercups! :pray:

**Comment by reichert621** [comment]
good point, I'll remove the duplicate 👍

**Comment by fkotsian** [comment]
Phoenix now supports file upload natively in LiveView!: https://www.phoenixframework.org/blog/phoenix-live-view-upload-deep-dive
