### ISSUE TITLE
ADMIN CAN SUSPEND AND UNSUSPEND AN ACCOUNT

### ISSUE THREAD

**Issue by MuhammadMullah** [papercups-io/papercups#187]
Going through the issues, I came across issue https://github.com/papercups-io/papercups/issues/180 which reminded me of another feature. 

As an admin, apart from inviting users, I should also be able to suspend/unsuspend users who belong to my company. When a user is suspended they can not be able to log in and probably get informed with a message that their account has been suspended.

This is in case a user leaves a company. For integrity purposes, the company might need to keep the records of the user(not delete any information associated with the user). In that case, they can just suspend the account.

**Comment by reichert621** [comment]
Fixed in https://github.com/papercups-io/papercups/pull/242!
