### ISSUE TITLE
Slack integration not working with private channels

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#195]
For some reason, the Slack integrations isn't working with private channels.

Some things to investigate:
- is this just a matter of adding new scopes/permissions?
  - (not sure... I tried this without any luck 😞 )
- could it be because our Slack app is not "approved" yet?
- or is it just something in the code?

If it's none of the above, we might just want to reach out to Slack support for help.

**Comment by reichert621** [comment]
See also https://github.com/papercups-io/papercups/issues/136

**Comment by reichert621** [comment]
@jalford14 I don't know if you're interested in looking into this, but thought it might be good since you've recently been working on our Slack integration :)

let me know if you wanna give this a shot! this would be super helpful for us if you figured it out 🙏

**Comment by jalford14** [comment]
@reichert621 yeah that sounds great to me! I might be a little busy for the next couple days but I'll get on it as soon as possible!

**Comment by reichert621** [comment]
thanks @jalford14! no rush :)

**Comment by jalford14** [comment]
@reichert621 working on this now. would you mind assigning me?

**Comment by reichert621** [comment]
sure @jalford14! 🎉

**Comment by jalford14** [comment]
hey @reichert621! the answer to this one is actually pretty easy. all you need to do is add the event name `message.groups` which allows us to read from private channels. Here's an example below.

![image](https://user-images.githubusercontent.com/7582183/99136539-6b280e80-25f3-11eb-817f-a780eda5034c.png)
![image](https://user-images.githubusercontent.com/7582183/99136542-711def80-25f3-11eb-94e1-b6dd02e88f0d.png)

**Comment by jalford14** [comment]
and here's what I have in Slack. Let me know if there is anything else I can help with!
![image](https://user-images.githubusercontent.com/7582183/99136559-97438f80-25f3-11eb-8b4f-279347b5c8a8.png)

**Comment by reichert621** [comment]
nice @jalford14! just curious, did you get this working with your personal access token, or did you get a token through the oauth flow?

**Comment by jalford14** [comment]
I'm fairly certain it was via Oauth, though I couldn't tell you for sure. I used the guide provided in the wiki which requires using Oauth. I don't know if that answers your question so feel free to let me know what I'm missing.

**Comment by reichert621** [comment]
no worries! only reason I ask is because when I was setting up the Slack integration initially I noticed some differences in how permissions worked between my personal access token and then OAuth token... but I'll try out your solution this weekend and hopefully that's all there is to it! :)

**Comment by reichert621** [comment]
hmm @jalford14 so no matter what I do, it seems that Slack gives me a `channel_not_found` error whenever I try connecting to a private channel 😕 

<img width="697" alt="Screen Shot 2020-11-14 at 7 05 27 PM" src="https://user-images.githubusercontent.com/5264279/99159655-77bc6d80-26ac-11eb-8914-0b56919ad1f9.png">

did you have to do anything else to get this working?

**Comment by reichert621** [comment]
looks like I had to manually click "Add an app" to the channel to get it working 😕 

<img width="516" alt="Screen Shot 2020-11-14 at 7 11 23 PM" src="https://user-images.githubusercontent.com/5264279/99159731-527c2f00-26ad-11eb-9ac3-584f5d9e88f6.png">

did you have to do this too?

**Comment by jalford14** [comment]
The only thing I had to do was re-authenticate the app. I didn't have to add the app to the channel

**Comment by reichert621** [comment]
hmm strange, do you mind sharing which scopes were used for your Slack authorization?

for example, mine were:
```
channels:history,chat:write,incoming-webhook,channels:manage,chat:write.public,users:read,users:read.email,groups:history
```

**Comment by jalford14** [comment]
@reichert621  `channels:history,channels:manage,chat:write,chat:write.public,incoming-webhook,users:read,users:read.email`

**Comment by jalford14** [comment]
odd, i'm not seeing the message scope in either of our slack auths

**Comment by reichert621** [comment]
hmm I still have no idea why I had to add the app to my channel manually, while it worked for you right away 🤔 maybe I'll just have to reach out to Slack support and see if they know, they've been helpful in the past 🤷

**Comment by cheeseblubber** [comment]
@reichert621 is this still an issue?

**Comment by reichert621** [comment]
nope we can close 👍
