### ISSUE TITLE
Slack integration causing 1-6 seconds delay when a site visitor is sending a message

### ISSUE THREAD

**Issue by rishabhpoddar** [papercups-io/papercups#199]
This doesn't happen without slack integration.

**Comment by reichert621** [comment]
thanks for reporting @rishabhpoddar! does the delay only affect how long it takes the message to show up in slack, or does it also slow down in the dashboard as well?

**Comment by rishabhpoddar** [comment]
The delay is clearly visible on the visitor’s side. It takes up to 6 secs from the status to go from “sending” to “sent” as seen by the visitor. 

As soon as the message shows up on slack, the status changes from “Sending” to “sent"

**Comment by cheeseblubber** [comment]
Fixed
