### ISSUE TITLE
How to change password and delete a user?

### ISSUE THREAD

**Issue by jackkemmish** [papercups-io/papercups#218]
Is there anywhere to change a users password and remove a user from the app?

Thanks again 😄

**Comment by reichert621** [comment]
thanks for add this @jackkemmish! this is definitely something we want to do soon :)

**Comment by jackkemmish** [comment]
Thanks for letting me know! I am building a site first so will look to hand over to the client in the next week or so then will need the password changed. What's the best way to contact you directly?

Ps really impressed with this so far, look forward to seeing what's coming in the future!

**Comment by reichert621** [comment]
feel free to reach out at alex@papercups.io or ping us on slack :) https://github.com/papercups-io/papercups#get-in-touch

**Comment by cheeseblubber** [comment]
Closing going to track in https://github.com/papercups-io/papercups/issues/121#issue-677097233[](url)
