### ISSUE TITLE
Chats sent directly from Slack do not trigger webhook events

### ISSUE THREAD

**Issue by a-krishnan7** [papercups-io/papercups#232]
When an agent sends a response to a chat from within the Slack application, the messages do not cause an event to be sent to the (verified) webhook target. Thanks!

**Comment by reichert621** [comment]
thanks @a-krishnan7! as part of this i'll fix the issue with the `customer` object not showing up as well 👍

**Comment by reichert621** [comment]
deploying the fix for this right now!

**Comment by reichert621** [comment]
@a-krishnan7 this should be done now, but let me know if you encounter anymore issues!

**Comment by a-krishnan7** [comment]
@reichert621 Thanks a ton! Appreciate the quick turnaround time, works great on my end
