### ISSUE TITLE
Allow to add existing user info

### ISSUE THREAD

**Issue by folkevil** [papercups-io/papercups#236]
Hi,
It would be better if we allow to existing user information via embed code, for example:

```
 window.Papercups = {
    config: {
      accountId: '97aab7a4-52f8-40d5-8edc-3a9f3e3cf0a2',
      title: 'xxx',
      subtitle: 'Ask us anything in the chat window below 😊',
      primaryColor: '#ff6900',
      greeting: '',
      newMessagePlaceholder: 'Start typing...',
      baseUrl: 'https://app.papercups.io',
	  currentUserName: 'ABC'
      currentUserId: 1,
      currentUserEmail: mail@mail.com
    },
  };
```

or maybe some other additional info.

**Comment by reichert621** [comment]
hey @folkevil! you can already do this with our `customer` prop :) (see https://github.com/papercups-io/chat-widget#using-in-html for more info)

thanks for flagging this though -- we should make it more obvious in the dashboard that you can do this!
