### ISSUE TITLE
Change user information in to a collapsible side bar

### ISSUE THREAD

**Issue by cheeseblubber** [papercups-io/papercups#239]
Currently the side bar takes two clicks to see the information
We should default the sidebar to be opened and be able to collapse the side bar
![Screen Shot 2020-09-19 at 9 32 46 AM](https://user-images.githubusercontent.com/4218509/93671825-20f33880-fa5b-11ea-991d-6f94af0f42d0.png)

When the sidebar's collapsed/opened state should persist across conversations:
* when you collapse the sidebar it should stay collapsed across conversations

Nice to have/optional - persist the side bar state across sessions. Probably can just keep it in browser ATM

**Comment by reichert621** [comment]
done -- we just show this info in the sidebar by default now
