### ISSUE TITLE
Make changes to widget js

### ISSUE THREAD

**Issue by peeves6** [papercups-io/papercups#248]
Hi, where can i find the non minified version of widget.js? I can only see the minified version in the assets directory. The chat-widget repo also does not have it.

**Comment by reichert621** [comment]
hey @peeves6! right now I just have it setup in a little script which I haven't put on github yet, but I'll push it in the near future :) what would you like to change?

**Comment by peeves6** [comment]
Hey Alex, thanks for the response. I have a non-React site and wanted to add 'menu cards' for some common actions that customers can perform, along with image uploads. I guess I could build the react code in the chat-widget repo and add a wrapper to render an iframe...just trying to save myself some work :)

Btw is that what the widget script that you mentioned does - adding a wrapper around the react code to render in an iframe?

**Comment by reichert621** [comment]
hey @peeves6 -- basically all the script does it build everything in the chat-widget repo and then do this:
```js
import React from 'react';
import ReactDOM from 'react-dom';
import ChatWidget from './components/ChatWidget';

const noop = () => {};
const w = window as any;
const config = (w.Papercups && w.Papercups.config) || {};
const {
  accountId,
  title,
  subtitle,
  newMessagePlaceholder,
  primaryColor,
  greeting,
  customer,
  baseUrl,
  iframeUrlOverride,
  customIconUrl,
  agentAvailableText,
  agentUnavailableText,
  showAgentAvailability,
  requireEmailUpfront = false,
  defaultIsOpen = false,
  onChatOpened = noop,
  onChatClosed = noop,
  onMessageSent = noop,
  onMessageReceived = noop,
} = config;

if (!accountId) {
  throw new Error(
    'An account token is required to render the Papercups chat widget!'
  );
}

const el = document.createElement('div');
el.id = 'PapercupsChatWidget';
document.body.appendChild(el);

ReactDOM.render(
  <ChatWidget
    accountId={accountId}
    title={title}
    subtitle={subtitle}
    newMessagePlaceholder={newMessagePlaceholder}
    primaryColor={primaryColor}
    greeting={greeting}
    customer={customer}
    baseUrl={baseUrl}
    iframeUrlOverride={iframeUrlOverride}
    customIconUrl={customIconUrl}
    agentAvailableText={agentAvailableText}
    agentUnavailableText={agentUnavailableText}
    showAgentAvailability={showAgentAvailability}
    requireEmailUpfront={requireEmailUpfront}
    defaultIsOpen={defaultIsOpen}
    onChatOpened={onChatOpened}
    onChatClosed={onChatClosed}
    onMessageSent={onMessageSent}
    onMessageReceived={onMessageReceived}
  />,
  document.getElementById('PapercupsChatWidget')
);

```
other than that, it's the same as what's in the chat-widget repo (where the entrypoint above is this https://github.com/papercups-io/chat-widget/blob/master/src/components/ChatWidget.tsx)

**Comment by reichert621** [comment]
we plan on adding "menu cards" and image uploads in the near future btw! how urgently do you need it?
