### ISSUE TITLE
[Reporting - API] Update reporting methods to filter by date range

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#254]
**Problem**
Users should be able to filter reporting data by a date range. Right now, the `/api/reporting` endpoint just fetches all data by default.

**Solution**
Update the queries in the Reporting context to incorporate a `from_date` and `to_date`:
- Reporting context: https://github.com/papercups-io/papercups/blob/master/lib/chat_api/reporting.ex#L9
- Reporting controller: https://github.com/papercups-io/papercups/blob/master/lib/chat_api_web/controllers/reporting_controller.ex#L11

**Testing**
Please add tests to `test/chat_api/reporting_test.exs` and make sure they pass with `mix test` :) 

**Context**
See https://github.com/papercups-io/papercups/issues/252

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by eikooc** [comment]
Hi Alex. As mentioned, I am totally new at Elixir, but if this is a pretty confined task I'd like to contribute to this and #255. I have time tomorrow and in the weekend to work on it if no one is working on it yet :).

**Comment by reichert621** [comment]
sounds good @eikooc, that would be great! i'll assign you for now :)
