### ISSUE TITLE
[Reporting - API] Add method to count messages sent/received by date

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#255]
**Problem**
Users should be able to see a breakdown of messages sent vs received in the reporting dashboard.

**Solution**
Let's create two methods in the Reporting context (https://github.com/papercups-io/papercups/blob/master/lib/chat_api/reporting.ex)
- One should retrieve daily counts of "sent" messages
  - "Sent" messages are messages where `user_id` is not `null` (i.e. it was sent by a signed-in user)
- The other should retrieve daily counts of "received" messages
  - "Received" messages are messages where `customer_id` is not `null` (i.e. it was sent by a customer through the chat widget) 

The responses should look something like this:
```
[
  %{date: "2020-09-01", count: 7},
  %{date: "2020-09-02", count: 12}, 
  %{date: "2020-09-03", count: 4}
]
```

**Testing**
Please add tests to `test/chat_api/reporting_test.exs` and make sure they pass with `mix test` :) 

**Context**
See https://github.com/papercups-io/papercups/issues/252

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by eikooc** [comment]
As mentioned in #254 I'd like to pick this up :+1:

**Comment by reichert621** [comment]
sure @eikooc! once #254 is completed i'll assign this one to you :)

**Comment by WLSF** [comment]
I'd like to help with this one, is it available? I saw that there was nos activity over the past 4 days.

**Comment by reichert621** [comment]
sure! i'll reassign it to you since i think @eikooc still hasn't finished #254 👍 

(cc @eikooc let me know if you have any updates!)

**Comment by WLSF** [comment]
Wow ok, thanks!

**Comment by eikooc** [comment]
Totally fine. It is taking me some time to set up the Elixir development environment for some reason, so I am still working on #254 :-)

**Comment by WLSF** [comment]
@eikooc If you need some help, you can call me and we can pair or something to set the environment and discuss about the task... 😸

**Comment by reichert621** [comment]
btw we also have a shared slack channel if you guys want to chat there :) https://github.com/papercups-io/papercups#get-in-touch

**Comment by eikooc** [comment]
@WLSF that would be fun! join the slack channel and let's coordinate! 🐈

**Comment by reichert621** [comment]
done in https://github.com/papercups-io/papercups/pull/272
