### ISSUE TITLE
[Reporting - API] Add method to calculate average/total received messages by day of the week

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#256]
**Problem**
Users should be able to see which days of the week (e.g. Monday, Tuesday, etc) are the "busiest" (i.e. receive the most messages on average)

**Solution**
Let's create a method in the Reporting context (https://github.com/papercups-io/papercups/blob/master/lib/chat_api/reporting.ex) that does the following:
- Retrieves daily counts of "received" messages
  - "Received" messages are messages where `customer_id` is not `null` (i.e. it was sent by a customer through the chat widget) 
- Calculates the average number sent by day of the week (e.g. Monday, Tuesday, etc)
- Calculates the total sent by day of week

The response should look something like this:
```
[
  %{day: "Monday", average: 6.6, total: 20},
  %{day: "Tuesday", average: 9.0, total: 27},
  %{day: "Wednesday", average: 10.3, total: 31},
  # etc
]
```

**Testing**
Please add tests to `test/chat_api/reporting_test.exs` and make sure they pass with `mix test` :) 

**Context**
See https://github.com/papercups-io/papercups/issues/252

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by sbacarob** [comment]
I'd love to tackle this, if that's ok

**Comment by reichert621** [comment]
certainly, that would be great @sbacarob! assigning you now :)

**Comment by reichert621** [comment]
done in https://github.com/papercups-io/papercups/pull/274

thanks @sbacarob!
