### ISSUE TITLE
[Reporting - API] Add method to determine breakdown of messages sent per user on team

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#257]
**Problem**
Users should be able to see a breakdown of how many messages are sent by users/agents on their team. (This is only relevant for accounts with multiple users/agents on the team.)

**Solution**
Let's create a method in the Reporting context (https://github.com/papercups-io/papercups/blob/master/lib/chat_api/reporting.ex) that counts the number of messages sent per user on the account for a given date range.

Basically this just means counting messages while grouping by `user_id`, and then expanding the `user` object so we can view details like `email`.

The response should look something like this:
```
[
  %{user: %{id: 1, email: "test@test.com"}, count: 28},
  %{user: %{id: 2, email: "example@example.com"}, count: 33},
  # etc
]
```

**Testing**
Please add tests to `test/chat_api/reporting_test.exs` and make sure they pass with `mix test` :) 

**Context**
See https://github.com/papercups-io/papercups/issues/252

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by estevanjantsk** [comment]
🚀 another one 👍
