### ISSUE TITLE
[Reporting - UI] Refresh reporting data when date range is changed

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#258]
**Problem**
Right now the data does not update when the date range is changed on the reporting page.
- **NB**: this is blocked by the backend task handling filtering by date range https://github.com/papercups-io/papercups/issues/254 -- please work on that first if it's not done yet!
- The reporting page can be accessed at http://localhost:3000/reporting

The reporting page (with fake data:)
<img width="1291" alt="Screen Shot 2020-09-29 at 4 23 45 PM" src="https://user-images.githubusercontent.com/5264279/94611812-47418100-0270-11eb-9c58-dd40b208f34f.png">

**Solution**
When the date range is changed, let's trigger a refresh of the reporting data in the UI.

**Context**
See https://github.com/papercups-io/papercups/issues/252

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by Aditya135** [comment]
Hey, I did like to work on this one

**Comment by reichert621** [comment]
sure @Aditya135 -- i'll assign you for now :)

when do you think you'll be able to work on it?

**Comment by reichert621** [comment]
hey @Aditya135 -- it turned out that the fix for this was trivial (https://github.com/papercups-io/papercups/pull/280/files#diff-2160a0e22b7bdfee0ff3c1561656c30fR218) so it's done already 😓 sorry about that! 

i'll be adding more frontend tickets tonight if you're still interested in contributing 🙏
