### ISSUE TITLE
[Reporting - UI] Update chart to display real data for messages sent/received by date

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#259]
**Problem**
At the moment, the reporting page is just showing fake data. Let's update it to show real data.
- The reporting page can be accessed at http://localhost:3000/reporting

The reporting page (with fake data:)
<img width="1291" alt="Screen Shot 2020-09-29 at 4 23 45 PM" src="https://user-images.githubusercontent.com/5264279/94611812-47418100-0270-11eb-9c58-dd40b208f34f.png">

**Solution**
- Pass real data into the chart component responsible for rendering this info (currently `<MessagesSentVsReceivedChart />`)
- Make any tweaks necessary to the chart UI

**Context**
See https://github.com/papercups-io/papercups/issues/252

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by kaozdl** [comment]
I can work on this one

**Comment by reichert621** [comment]
sounds good @kaozdl! i'll assign you :)

**Comment by reichert621** [comment]
hey @kaozdl! just curious, when will you be able to tackle this?

**Comment by joelazwar** [comment]
Hi, I'd like to give this a try :)
