### ISSUE TITLE
Display customer metadata in customer details modal

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#260]
**Problem**
Users can set custom metadata on their customers, but we currently don't display this information anywhere in the UI.

This is what we currently display:
<img width="1084" alt="Screen Shot 2020-09-29 at 4 35 11 PM" src="https://user-images.githubusercontent.com/5264279/94613354-79ec7900-0272-11eb-923b-109232295829.png">

**Solution**
Using this `metadata` field on the customer object:
<img width="565" alt="Screen Shot 2020-09-29 at 4 39 35 PM" src="https://user-images.githubusercontent.com/5264279/94613352-79ec7900-0272-11eb-818a-48c947b346ed.png">

Display these fields at the bottom of the customer details modal: https://github.com/papercups-io/papercups/blob/master/assets/src/components/customers/CustomerDetailsModal.tsx#L22

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by lukewaring** [comment]
Hi @reichert621, I would be happy to work on this one 🙂

**Comment by reichert621** [comment]
thanks @lukewaring!

**Comment by sohamsshah** [comment]
Hi @reichert621 I am interested to contribute to Papercups. Can you suggest or assign me some work to start contributing towards?

**Comment by reichert621** [comment]
hey @sohamsshah -- this should have some good guidance :) 

https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md

**Comment by sohamsshah** [comment]
@reichert621 Thank you! Looking forward to be a part of this!

**Comment by eikooc** [comment]
Hi. I was just playing around, and thought I'd do this one since there has been a week without activity. @lukewaring I hope I'm not intruding, and if you have made something more elegant, you can tell me and open a PR 🙂.

My PR is here #288
