### ISSUE TITLE
Add `time_zone` field to customers

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#261]
Seems like it could be useful? (Will need to send it through on the widget side, but for the sake of this ticket just add a nullable string field to the customers table)

See https://stackoverflow.com/questions/1091372/getting-the-clients-timezone-offset-in-javascript

**Comment by estevanjantsk** [comment]
🚀

**Comment by siddhantvirus** [comment]
I was just looking through the code before i commented . @estevanjantsk are you planning to take this up ?

**Comment by estevanjantsk** [comment]
I already created a PR.
