### ISSUE TITLE
Hex.pm Proxy Lib

### ISSUE THREAD

**Issue by Grantimus9** [papercups-io/papercups#262]
**Problem Statement**
As browsers increasingly restrict third party cookies and third party script execution and/or access to localstorage, companies relying on chat apps that pull in third party scripts will be increasingly frustrated with lack of syncing and state getting lost. 

As a company that'd like to create an internal Phoenix/Elixir pubsub topic for customer events, I would like to have a hook in code I own (my own app) to observe and broadcast these events. E.g. watching new messages for keywords, like "pricing" or "angry" that could deserve extra attention immediately. 

I am a company that is either on a free tier (?) or paying customer of papercups, and expect papercups' server to process and store my data, manage my users, etc.  

**Proposed Solution**
Papercups creates & maintains an opensource hex.pm lib which: 
1. Hosts the widget javascript so phx apps can self-host it and ensure the js is served over my own domain (similar to how phoenix and phoenix_html hex libs do it). This would probably need to be configured in app.js for a few keys; e.g. 
```javascript
papercups.base_path = "/chatwidget"
```
2. Thinly proxies requests from clients to the papercups.io server, setup via an endpoint route namespace that would need to be configured; something like this in config.exs: 
```elixir 
config :papercups_firstparty, 
  papercups_base_path: "/chatwidget"
```

3. Provides a way to access the %Plug.Conn{} before it's proxied through to the papercups server, enabling the host app to inspect and maybe broadcast a pubsub event. 

The app would add to router.ex some [routing](https://hexdocs.pm/phoenix/routing.html#forward) and interception logic: 
```elixir 
forward "/chatwidget", PapercupsWidget.ProxyPlug
```

something like: 
```elixir

@doc """
This function takes a call from the js frontend and immediately forwards it to the papercups backend.  
"""
def proxy_to_papercups(conn) do
    conn 
    |> maybe_broadcast_something() // must return a conn.
end

@doc """
This function takes a response from papercups' server and proxies it back to the client. I think this can also be a %Conn{} struct. 
"""
def proxy_to_client(conn = %Conn{}) do
    conn 
    |> maybe_broadcast_something() // must return a conn.
end
```

**Alternatives Considered**
1. Rewriting this app to be a hex package. 
2. Self-hosting papercups.io. I see many developers adopting this route that would have self-hosted, myself included. We're happy to rely on Papercups' mailgun integration, Slack integration config, etc.  

**Challenges**
1. Defining a sensible "interception" API for developers. I suspect without knowing that a proxy lib or two has some good ideas or examples for inspiration. 
2. Keeping the js in the hex package up-to-date, although perhaps this complexity can be traded for adding a js build/deploy step.

**Comment by reichert621** [comment]
thanks for this great writeup @Grantimus9! it's a lot to digest, so i'll have to get back to you with my thoughts :) but i really like these ideas 🙏

**Comment by cheeseblubber** [comment]
Closing this since we don't have enough bandwidth to do this atm
