### ISSUE TITLE
[Reporting - API] Add method to determine number of new customers created per day

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#281]
**Problem**
Users should be able to see how many new customers are interacting with their chat per day.

**Solution**
Let's create a method in the Reporting context (https://github.com/papercups-io/papercups/blob/master/lib/chat_api/reporting.ex) that counts the number of customers created on the account per day for a given date range.

The response should look something like this:
```
[
  %{date: "2020-09-01", count: 7},
  %{date: "2020-09-02", count: 12}, 
  %{date: "2020-09-03", count: 4}
]
```

(This method will be quite similar to the `count_messages_by_date` method: https://github.com/papercups-io/papercups/blob/master/lib/chat_api/reporting.ex#L9)

Also, when this method is ready, feel free to add it to the response payload in the `ReportingController`!

**Testing**
Please add tests to `test/chat_api/reporting_test.exs` and make sure they pass with `mix test` :) 

**Context**
See https://github.com/papercups-io/papercups/issues/252

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by jonathanyeong** [comment]
Hey there! Could I take this issue?

**Comment by reichert621** [comment]
sure @jonathanyeong! assigning you now :)

**Comment by reichert621** [comment]
(i should add -- if this ticket is too easy for you, feel free to look out for any opportunities to do some refactoring in the `Reporting` context or in the tests!)

**Comment by jonathanyeong** [comment]
Haha let's see how I go with this ticket! First time working with a prod Elixir app!

**Comment by m1ome** [comment]
@jonathanyeong are you working on this? would like to pick this up if you are not working on it 😄

**Comment by jonathanyeong** [comment]
Hi! @m1ome I've definitely been dragging my feet on this. Looks like you already have a PR open. So go for it!

**Comment by reichert621** [comment]
hey @jonathanyeong feel free to tackle this still! I think the PR misunderstood this a bit because it queries the `users` table rather than the `customers` table

but if you don't have time this week, I'll be writing up some more tickets soon if you'd like to pick up a different one 👍

**Comment by jonathanyeong** [comment]
Okay! Great, I'm working on it tonight. I had some issues installing Elixir 1.6.3 (from the [Getting Started](https://github.com/papercups-io/papercups/wiki/Development-Setup#getting-started) wiki) but then I realized you're using 1.10 which I already have installed! So I'm able to start dev on it.

**Comment by reichert621** [comment]
ah! sorry for the confusion there, we need to update that 😓 (I'm probably going to update the docs to recommend using https://github.com/asdf-vm/asdf)

**Comment by jonathanyeong** [comment]
Nah all good! I'm pretty new to Phoenix so still getting my head around where the configs are. Hopefully, my PR addresses this issue!

**Comment by m1ome** [comment]
@jonathanyeong saw you PR, closed mine 👍

**Comment by reichert621** [comment]
done, thanks @jonathanyeong!
