### ISSUE TITLE
[Internal notifications] Send internal Slack alert when user successfully links Slack/Gmail integration

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#282]
**Problem**
This is a good way for us to track engagement -- if users are setting up these integrations, we want to make sure everything is working well for them. 

**Solution**
In the SlackController and GmailController, send an internal notification to Slack (with `ChatApi.Slack.log`) that says "{user.email} successfully linked Slack/Gmail!"

(See https://github.com/papercups-io/papercups/pull/276 for an example of how this might look)

**NB**: in order to test this manually, you'll need to get our own Slack webhook URL https://api.slack.com/messaging/webhooks and set the `PAPERCUPS_SLACK_WEBHOOK_URL` environment variable to it.

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by lorecrafting** [comment]
Hey, thanks for the descriptive and bite-sized issues.  Would you please assign this to me?  Thank you!

**Comment by reichert621** [comment]
sure @lorecrafting!

**Comment by shivamls** [comment]
Hi @lorecrafting if you are not planning to work on this lmk. I can pick this up.

**Comment by lorecrafting** [comment]
Thanks @shivamls, i'll be putting in a PR today.

**Comment by reichert621** [comment]
thanks @lorecrafting!
