### ISSUE TITLE
[Internal notifications] Send internal Slack alert when user changes subscription plan

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#283]
**Problem**
We want to get alerted right away if someone upgrades/downgrades their subscription plan

**Solution**
In the BillingController, send an internal notification to Slack (with `ChatApi.Slack.log`) that says "{user.email} set subscription plan to {plan}" whenever a user creates or updates their subscription plan.

(See https://github.com/papercups-io/papercups/pull/276 for an example of how this might look)

**NB**: in order to test this manually, you'll need to get our own Slack webhook URL https://api.slack.com/messaging/webhooks and set the `PAPERCUPS_SLACK_WEBHOOK_URL` environment variable to it.

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by eikooc** [comment]
Can I try this one out? :)

**Comment by reichert621** [comment]
certainly @eikooc! should be pretty straightforward, but let me know if you need any help getting a slack webhook url setup (i think the slack docs are pretty good though 👍 )

**Comment by reichert621** [comment]
thanks again @eikooc!

**Comment by eikooc** [comment]
Likewise!
