### ISSUE TITLE
[Reporting - UI] Create chart to display stats around messages sent per day of week

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#284]
**Problem**
Our reporting API currently returns stats around the number of total/average messages sent by day of week. Let's add a chart do display this information!
- The reporting page can be accessed at http://localhost:3000/reporting

The reporting page (with fake data:)
<img width="1291" alt="Screen Shot 2020-09-29 at 4 23 45 PM" src="https://user-images.githubusercontent.com/5264279/94611812-47418100-0270-11eb-9c58-dd40b208f34f.png">

**Solution**
- Create a new chart component in `/assets/src/components/reporting`
  - We're using `recharts` for our chart library
  - It might make sense to use some kind of bar chart (http://recharts.org/en-US/examples/SimpleBarChart) but feel free to use whatever you think looks best!
  - See https://github.com/papercups-io/papercups/blob/master/assets/src/components/reporting/MessagesPerDayChart.tsx for an example
- Pass real data into the chart component
  - You'll get it in this API response: https://github.com/papercups-io/papercups/blob/master/assets/src/components/reporting/ReportingDashboard.tsx#L39
  - The field should be `messages_by_weekday`

**Context**
See https://github.com/papercups-io/papercups/issues/252

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by KeshriAyushi22** [comment]
hey @reichert621 , can u assign this to me? It would be a great learning experience

**Comment by reichert621** [comment]
certainly @KeshriAyushi22! when do you think you'd be able to work on it btw?

**Comment by KeshriAyushi22** [comment]
> certainly @KeshriAyushi22! when do you think you'd be able to work on it btw?

I will start this by tomorrow, rn working on some other issues @reichert621

**Comment by reichert621** [comment]
sounds good @KeshriAyushi22!

**Comment by KeshriAyushi22** [comment]
Hi,
I tried to register by running the npm , inside assets .. but it wasnt
working as proxy error was giving which i realised i wasnt running the
backend module which is fair enough.. i get the issue , but how to run the
backend as im new to docker and all, i just know react so can u help me out
on that front? plz
*Thanks and Regards*
*Ayushi  Keshri*

**Comment by reichert621** [comment]
hey @KeshriAyushi22! did you follow the instructions in https://github.com/papercups-io/papercups/wiki/Development-Setup?

**Comment by reichert621** [comment]
hey @KeshriAyushi22 -- any updates on this?

**Comment by KeshriAyushi22** [comment]
Hi
No I was quite busy with my day job work, couldn't look into it. You can
assign this to someone else, meanwhile if I get time I will look into this.

Thanks
Ayushi

**Comment by divyeshairmeet** [comment]
Hi I want to work on this. I'll take a little more time, I hope that's fine

**Comment by Tapudp** [comment]
Hi I want to work on this, I might take a little longer than usual. I hope that's fine.

**Comment by reichert621** [comment]
sounds good @Tapudp! when do you think you'll be able to work on it?

**Comment by Tapudp** [comment]
> sounds good @Tapudp! when do you think you'll be able to work on it?

This week I'll keep working on this on my free time after work. Do you guys have slack that I can join to communicate for questions to understand the repo better.

**Comment by reichert621** [comment]
yes! there's a link in the issue at the top :)

(or see https://github.com/papercups-io/papercups#get-in-touch)

**Comment by JekRock** [comment]
Is there a way to fill the database with fake data (like seeding) to check the charts?

**Comment by reichert621** [comment]
hey @JekRock! not at the moment 😞 I should create a ticket for that haha

**Comment by reichert621** [comment]
@Tapudp any updates on this?

**Comment by Tapudp** [comment]
Hey sorry couldn't update the status here, I have been traveling. I'll look up other FE tasks in the repo then. :(

**Comment by reichert621** [comment]
sounds good @Tapudp! i just want to make sure tickets are handled within 7 days of assigning them 👍
