### ISSUE TITLE
[Reporting - UI] Create chart to display breakdown of messages sent per user/agent

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#285]
**Problem**
Our reporting API currently returns stats around the number of messages sent per user/agent over a given date range. Let's add a chart do display this information!
- The reporting page can be accessed at http://localhost:3000/reporting

The reporting page so far (with fake data:)
<img width="1291" alt="Screen Shot 2020-09-29 at 4 23 45 PM" src="https://user-images.githubusercontent.com/5264279/94611812-47418100-0270-11eb-9c58-dd40b208f34f.png">

**Solution**
- Create a new chart component in `/assets/src/components/reporting`
  - We're using `recharts` for our chart library
  - It might make sense to use some kind of pie chart (e.g. http://recharts.org/en-US/examples/PieChartWithPaddingAngle) but feel free to use whatever you think looks best!
  - See https://github.com/papercups-io/papercups/blob/master/assets/src/components/reporting/MessagesPerDayChart.tsx for an example
- Pass real data into the chart component
  - You'll get it in this API response: https://github.com/papercups-io/papercups/blob/master/assets/src/components/reporting/ReportingDashboard.tsx#L39
  - The field should be `messages_per_user`

**Context**
See https://github.com/papercups-io/papercups/issues/252

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by Aditya135** [comment]
Hi @reichert621 , I did like to work on this one, I am free to work on Fri 9 - Oct 11
