### ISSUE TITLE
[Email notifications] Add customer email to "new message" notification if available

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#287]
**Problem**
Our email notifications currently don't include any information about the sender. We should include the customer/sender email in the message if it's available.

**Solution**
If the customer sending the message has an email address, display it in the email notification. (Here's where the logic lives: https://github.com/papercups-io/papercups/blob/master/lib/chat_api/messages.ex#L206-L208)

For example, instead of just writing `"A new message has arrived: #{message}"` we should write `"A new message has arrived from #{customer.email}: #{message}"` (in https://github.com/papercups-io/papercups/blob/master/lib/chat_api/emails/email.ex#L19)

**Testing**
Please add tests if possible and make sure everything passes with `mix test` :) 

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by shivamls** [comment]
Hi
Please assign this to me.

**Comment by reichert621** [comment]
sure @shivamls :) i'll assign you for now -- when do you think you'll be able to work on it?

**Comment by shivamls** [comment]
Going through the docs and slack. Will start as soon as I get a hang of things (first time contributing)

Targeting completing this by today

**Comment by reichert621** [comment]
sounds good, thanks for the update @shivamls :)

**Comment by reichert621** [comment]
done, thanks @shivamls!
