### ISSUE TITLE
Unable to start web app on local development using Docker

### ISSUE THREAD

**Issue by aladhims** [papercups-io/papercups#294]
**Describe the bug**
I'm unable to start local development due to the issue of the mix package manager

**To Reproduce**
1. Trigger local docker development using this command `docker build -t papercups . && docker-compose up` as mentioned on the [wiki](https://github.com/papercups-io/papercups/wiki/Development-Setup)
2. After some installations, the log on the web app shows this error ` the dependency is not available, run "mix deps.get"
web_1  | ** (Mix) Can't continue due to errors on dependencies`

**Expected behavior**
The app should run without no issues

**Screenshots**
![image](https://user-images.githubusercontent.com/20749737/95419021-e77b6200-0962-11eb-86b5-9bcddb5b01bf.png)

**Additional context**
-

**Comment by reichert621** [comment]
Thanks for reporting this @aladhims! Just curious, did you try running `mix deps.get` to see if that fixes anything?

**Comment by reichert621** [comment]
cc @cheeseblubber

**Comment by aladhims** [comment]
Hi @reichert621 , Thanks for the response,  `mix deps.get` is actually already included in the Dockerfile here https://github.com/papercups-io/papercups/blob/c094d5b3d95e3bcaaecb6fddd95e42e56f5483ec/Dockerfile#L16

**Comment by reichert621** [comment]
hmm good point 🤔 we'll look into it!

**Comment by aladhims** [comment]
Sure, thanks. Please let me know if you guys found something, in the meantime I'll try to look way around it.

**Comment by reichert621** [comment]
sounds good, will do 👍 have you tried the non-Docker setup in https://github.com/papercups-io/papercups/wiki/Development-Setup? (that might be the easiest workaround for now)

**Comment by aladhims** [comment]
Yes, I probably will try the non-Docker setup if I can't resolve this problem on my own, but having a local dev with docker is easy and simple 😄

**Comment by reichert621** [comment]
for sure, we'll definitely want to get that fixed!

**Comment by cheeseblubber** [comment]
Hey Aladhims long shot but do you have any more logs around when `mix do deps.get` was running?
