### ISSUE TITLE
How does papercups handle concurrency

### ISSUE THREAD

**Issue by sladyn98** [papercups-io/papercups#299]
Suppose two users are logged into the same dashboard, how do you make sure that they do no overwrite the same chat ?

**Comment by reichert621** [comment]
hey @sladyn98! not quite sure what you mean -- if two users are logged in and they each send a message, both messages would show up from each user in the UI

did you encounter some issue?

**Comment by sladyn98** [comment]
Hey @reichert621 thanks for the reply. I would like to frame it better. If the admin invites two users to a dashboard and they try to reply to the same customer at the same time. Do the messages overwrite or does each message appear on the conversation. Because it could be possible they reply with a different answer

**Comment by reichert621** [comment]
ah I see! yes, at the moment both messages would show up if two users replied at the same time

**Comment by reichert621** [comment]
let me know if there's anything unexpected happening or you have a feature request! in the meantime, going to close this
