### ISSUE TITLE
Docker deployment?

### ISSUE THREAD

**Issue by rberrelleza** [papercups-io/papercups#30]
I have an almost-functioning Dockerfile, happy to contribute it if this is something you are interested in supporting.

**Comment by cheeseblubber** [comment]
Thanks Ramiro! Definitely if you open a pull request we'd be happy to accept it

**Comment by cheeseblubber** [comment]
It definitely it is in our roadmap to support docker in the long run

**Comment by cheeseblubber** [comment]
Merged in commit
