### ISSUE TITLE
[Reporting - API] Add method to determine breakdown of customer browsers/timezones/OS's

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#304]
**Problem**
Users should be able to see a breakdown of their customers' browser/OS/timezone in the Reporting Dashboard

**Solution**
Let's create a method in the Reporting context (https://github.com/papercups-io/papercups/blob/master/lib/chat_api/reporting.ex) that counts the number of customer browsers/OS's/timezones for a given date range.

Basically this just means grouping the `customers` table by a given field (e.g. `:browser`/`:os`/`:time_zone`) and counting the number of occurrences.

The method might look something like:
```elixir
def get_customer_breakdown(account_id, field, filters \\ %{}) do
  # `field` will be `:os`, `:browser`, `:time_zone`, etc (fields on the Customer model)
  # `filters` should include a `from_date` and `to_date`
end 
```

The response should look something like this:
```elixir
get_customer_breakdown(account_id, :browser, %{from_date: ..., to_date: ...})
# => 
[
  %{browser: "Chrome", count: 25},
  %{browser: "Firefox", count: 12},
  # etc
]
```

**Testing**
Please add tests to `test/chat_api/reporting_test.exs` and make sure they pass with `mix test` :) 

**Context**
See https://github.com/papercups-io/papercups/issues/252

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by shivamls** [comment]
You can assign this to me.

**Comment by reichert621** [comment]
hey @shivamls -- any updates?

**Comment by eikooc** [comment]
Does it make sense for me to pick this up? It looks stale.

**Comment by reichert621** [comment]
yup go for it @eikooc :)

**Comment by eikooc** [comment]
@reichert621 I have created a draft pull request at #361. I couldn't for the life of me figure out how to make the field an atom or what is needed to make the key of the map dynamic based on the `field` given as input, so I chose to go with a generic name called `field` for now. If you can help me, then it would be appreciated :)

**Comment by reichert621** [comment]
hey @eikooc! thanks for the draft PR :) i'll take a look later, but in the meantime if it's easier feel free to use use `Enum.map` to convert `:field` to the name of the field (e.g. `:browser`)
