### ISSUE TITLE
Display customer timezone in CustomerDetailsModal if available

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#305]
**Problem**
For some customers, we are able to detect their timezone. But we don't currently show this in the `CustomerDetailsModal` component.

This is what we currently display:
<img width="1084" alt="Screen Shot 2020-09-29 at 4 35 11 PM" src="https://user-images.githubusercontent.com/5264279/94613354-79ec7900-0272-11eb-923b-109232295829.png">

**Solution**
If the `time_zone` field is available on the `customer`, let's display it in the modal as "Time zone". Let's place it to the right of the "ID" field, below the "Phone" field. If the field is `null`, just display "Unknown".

Here's the component: https://github.com/papercups-io/papercups/blob/master/assets/src/components/customers/CustomerDetailsModal.tsx#L22

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by raditya3** [comment]
Hi @reichert621 , Can you assign me this one?

**Comment by reichert621** [comment]
sure @raditya3!

**Comment by raditya3** [comment]
Hi @reichert621, by timezone you mean offset like `+5:30 GMT` right?

**Comment by reichert621** [comment]
closing, thanks @raditya3!
