### ISSUE TITLE
Add typespecs to API controller methods

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#306]
**Is your feature request related to a problem? Please describe.**
We want to start getting better about including typespecs for our Elixir code. The controllers should be an easy place to start.

**Describe the solution you'd like**
Add typespecs to all the methods in our controllers, i.e. the files in the `lib/chat_api_web/controllers` directory.

For more info on typespecs, see https://hexdocs.pm/elixir/typespecs.html

For the most part, these will all be roughly the same, e.g.:
```elixir
  @spec index(Plug.Conn.t(), map()) :: Plug.Conn.t()
  def index(conn, params) do
    # ...
  end
```

(I imagine this will only be different for any private functions in the controllers.)

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by m1ome** [comment]
Submitted PR according to this issue

**Comment by m1ome** [comment]
@reichert621 👍

**Comment by reichert621** [comment]
thanks @m1ome! 🎉
