### ISSUE TITLE
Add typespecs to backend "context" modules

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#307]
**Is your feature request related to a problem? Please describe.**
We want to start getting better about including typespecs for our Elixir code. A lot of our backend logic lives in Phoenix "contexts" (e.g. `lib/chat_api/messages.ex`), so this will be a great place to add more typespecs.

**Describe the solution you'd like**
Add typespecs to all the modules in the `lib/chat_api` directory. Don't worry about any of the subdirectories for now -- just focus on e.g. `lib/chat_api/accounts.ex`, `lib/chat_api/messages.ex`, `lib/chat_api/conversations.ex`.

For more info on typespecs, see https://hexdocs.pm/elixir/typespecs.html

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by m1ome** [comment]
Submitted PR according to this issue

**Comment by reichert621** [comment]
closing, thanks @m1ome!
