### ISSUE TITLE
Fix some `any` types in the Conversations UI

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#308]
**Is your feature request related to a problem? Please describe.**
We have a lot of `any` types in our frontend. Let's start replacing these with more descriptive types.

**Describe the solution you'd like**
In all the components in `assets/src/components/conversations`, replace as many `any` types with `Conversation`/`Message`/`Account`/`User` types from https://github.com/papercups-io/papercups/blob/master/assets/src/types.ts as possible :) 

(Note that you may need to add/update some of the types in that file.)

**Additional context**
One thing that might be helpful to understand how data looks coming from the API:

If you're trying to figure out what's included in the `Conversation` type, take a look at the `conversation_view.ex` file on the backend to see what the API response payload includes.

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by xapatjb4** [comment]
Hey @reichert621 would like to give this a shot. Can you assign this to me?

**Comment by raditya3** [comment]
Hey, Can I get this one?

**Comment by reichert621** [comment]
sure @raditya3! assigning you for now :)
