### ISSUE TITLE
Move to ex_machina for fixture testing

### ISSUE THREAD

**Issue by m1ome** [papercups-io/papercups#316]
**Is your feature request related to a problem? Please describe.**
Currently papercups using stuff like self-bound factories to run tests, bad thing about it: 
- It generates some weird functions like: `create_test_user` e.t.c
- It should also be handled in future development

**Describe the solution you'd like**
Solution is to use [ex_machina](https://github.com/thoughtbot/ex_machina) and remove all fixtures generation/generation code out of repository.

**Describe alternatives you've considered**
https://github.com/batate/blacksmith and a couple of others, seems very inmature and hard to config/maintain

**Comment by reichert621** [comment]
great idea @m1ome! this sounds related to https://github.com/papercups-io/papercups/issues/60, do you mind commenting on that issue as well in case these should be done at the same time?

**Comment by m1ome** [comment]
@reichert621 can you assign hacktoberfest labels also? 😃

**Comment by m1ome** [comment]
@reichert621 also it would be awesome if you assign this on to me, and i will try done this ASAP

**Comment by reichert621** [comment]
sure! still trying to sort things out in this discussion (#60), but in the meantime I'd love to see what your proposed updates would look like :)

**Comment by reichert621** [comment]
hey @m1ome! any updates on this?

**Comment by flmel** [comment]
Me
