### ISSUE TITLE
Please opt-in GoogleAnalytics

### ISSUE THREAD

**Issue by webdeb** [papercups-io/papercups#322]
To prevent of being sued we have to get the permission from the user to opt-in analytics. Right now we'd have to disable Papercups completely :(

**Comment by reichert621** [comment]
hey @webdeb! can you tell us a bit more about your setup?

for example:
- are you using our hosted dashboard at http://app.papercups.io/, or are you self-hosting on our own server?
- where do you need the opt-in to happen? in the chat widget or in the dashboard? (I'm assuming the chat widget, but I don't think we have Google Analytics there 🤔)

**Comment by webdeb** [comment]
Hello @reichert621! 
please check this out. It looks like Google Analytics cookie to me:
<img width="778" alt="Bildschirmfoto 2020-10-15 um 23 32 43" src="https://user-images.githubusercontent.com/14992140/96188388-efc53580-0f3e-11eb-91db-20e599c47155.png">

For me the opt-in/out would cool on the JS side, so we could use a client-side consent manager flow.

**Comment by reichert621** [comment]
I see -- thanks for the info! I'll look into it 👍

**Comment by webdeb** [comment]
> do you have an example of how you'd like the client-side consent manager flow to look?

Right now I am in the middle of implementing one, so I'll first just go the most basic enable-all / disable-all flow. And since we are using a React-App and are controlling all of the scripts we can just enable / disable the parts of the app that are affected by the user decision like `useAnalytics` etc.. 

In case of third-party apps like papercups we would have to entirely disable it

`return !analyticsAllowed ? null : <ChatWidget ... />`

Of course it would be much nicer to just pass the boolean down to ChatWidget

```
<ChatWidget
  analyticsAllowed={analyticsAllowed}
  ...
/>
```

**Comment by cheeseblubber** [comment]
@webdeb So our widget doesn't itself doesn't do any google analytics tracking. You can see in the code yourself we don't even include it in the [package.json](https://github.com/papercups-io/chat-widget/blob/master/package.json). We add the google analytics tracking to our hosted site which is app.papercups.io. 

I think what is happening is that the cookie that is coming from app.papercups.io is being associated with chat-widget.papercups.io. 

A really simple experiment you can do to validate this is load the widget in incognito window then check if it is doing any tracking. Then navigate to app.papercups.io the navigate back and you'll see that the cookie gets associated with chat-widget.papercups.io

**Comment by webdeb** [comment]
@cheeseblubber you are right, the cookie was already in my browser, thank you the explanation 👍
