### ISSUE TITLE
Add API endpoint to export customer data as CSV

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#324]
**Problem**
Users would like to export their customer data in CSV format.

**Solution**
Let's create an API endpoint in our `CustomerController` that returns customer data in CSV format. (Currently we just return it as JSON).

This could probably be a good use case for pattern matching, e.g.
```elixir
def index(conn, %{"format" => "csv") do
  # ...
  customers = Customers.list_customers(account_id)
  # handle returning in CSV format
end
```

**Comment by fel-mazo** [comment]
Hi ! I'm going to try to get this done over the weekend and make a pull request ! wish me luck still an elixir beginner !

**Comment by reichert621** [comment]
sounds good @fel-mazo!

**Comment by alisinabh** [comment]
Hi everyone,

I just have a question. How are you going to handle `tags` in customer data?

**Comment by reichert621** [comment]
hey @alisinabh! good question -- for now, we can just omit them

**Comment by reichert621** [comment]
thanks @alisinabh!

**Comment by alisinabh** [comment]
:blue_heart: :purple_heart: :green_heart: :heart:
