### ISSUE TITLE
Allow users to edit their customer's information

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#327]
**Problem**
Our users should be able to edit their customers' information -- specifically their name, email, and phone number.

Users can currently view these fields, but not edit them... this is what we currently display:
<img width="923" alt="Screen Shot 2020-10-18 at 9 08 36 PM" src="https://user-images.githubusercontent.com/5264279/96394885-2befd480-1191-11eb-9493-478cf0998a4f.png">

**Solution**
Make the "name", "email", and "phone number" fields editable.

To do this, we should:
- Add a button to the bottom of the modal that says "**Edit**"
- Move the "**Close**" button to the left side of the modal
- When clicking the button, the modal should go into "edit mode"... this means that editable fields will change from **text** to **input** fields
- When in edit mode, the "**Edit**" button should change into "**Save**" and "**Cancel**" buttons
- Clicking "**Save**" should persist the changes, while "**Cancel**" should revert them (if any)
- In order to persist changes, we will hit the **update customer API endpoint**
  - i.e. **`PUT /api/customers/${customerId}`**

Here's the component: https://github.com/papercups-io/papercups/blob/master/assets/src/components/customers/CustomerDetailsModal.tsx

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by swatikothari** [comment]
I can take this one

**Comment by reichert621** [comment]
sure @swatikothari :) I'll assign you 👍

**Comment by reichert621** [comment]
hey @swatikothari! any updates on this?

**Comment by swatikothari** [comment]
Hey @reichert621 - Sorry I got busy with another PR for a different Hacktoberfest project. If this hasn't been taken, I have bandwidth to work on this now. Please let me know.

**Comment by joelazwar** [comment]
hi, i know hacktoberfest is past but i'd still love to try this issue :)

**Comment by reichert621** [comment]
sure @joelazwar! i'll assign you :)
