### ISSUE TITLE
Migrate customers table `current_url`/`pathname` fields from `string` to `text` types

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#328]
**Problem**
The `current_url` and `pathname` fields on the Customers table are sometimes longer than the max character limit for DB fields of type "string".

**Solution**
Migrate the following fields on the Customers table from type "string" to type "text":
- `current_url`
- `pathname`

For context: https://github.com/papercups-io/papercups/blob/master/lib/chat_api/customers/customer.ex#L29

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by kamilpikula** [comment]
if the problem's similar to https://github.com/papercups-io/papercups/issues/329 - you can assign to me. :)

**Comment by reichert621** [comment]
hey @kamilpikula! sounds good :)

**Comment by kamilpikula** [comment]
hi @reichert621, I sent PR with the changes - https://github.com/papercups-io/papercups/pull/338 :)

**Comment by reichert621** [comment]
thanks @kamilpikula!
