### ISSUE TITLE
SlackConversationThreads should auto-delete when the associated Conversation is deleted

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#330]
**Problem**
When deleting a `conversation` in the database, we get an error if associated `slack_conversation_threads` exist.

This is because when we created the `slack_conversation_threads` table, we forgot to add an `on_delete: :delete_all` to the migration script.

This is what we did: https://github.com/papercups-io/papercups/blob/master/priv/repo/migrations/20200720153026_create_slack_conversation_threads.exs#L9

This is what we **should've** done: https://github.com/papercups-io/papercups/blob/master/priv/repo/migrations/20201001165426_create_tags.exs#L25

**Solution**
Since we can't rewrite the migration script, we'll have to create a new migration.

It looks like this thread might have some helpful suggestions for how to do that: https://elixirforum.com/t/can-you-modify-a-columns-references-3-options-in-ecto/4443/8

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by daskycodes** [comment]
Hi, I would like to prepare a PR for this!

**Comment by reichert621** [comment]
thanks @daskycodes! let me know if you're interested in tackling any other tickets :)
