### ISSUE TITLE
Add ability to redirect users to a protected page after login

### ISSUE THREAD

**Issue by cheeseblubber** [papercups-io/papercups#340]
**Is your feature request related to a problem? Please describe.**
If you try to reach a page that requires login you should be redirected to the original page after logging in.

**Describe the solution you'd like**
Use the `redirect` query param to redirect the user back to the original page they tried to access.

For example:
- User tries to go to `/conversations/all` page
- User is not authenticated, so gets redirected to `login` page

The fix we want:
- User tries to go to `/conversations/all` page
- User is not authenticated, so gets redirected to `login` page with `redirect=/conversations/all` in query param
  - e.g. `locahost:3000/login?redirect=/conversations/all`

This might be a decent starting point? https://github.com/papercups-io/papercups/blob/master/assets/src/App.tsx#L48

**Comment by reichert621** [comment]
done in https://github.com/papercups-io/papercups/pull/348
