### ISSUE TITLE
[Backend] Add ability to archive a conversation

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#349]
**Problem**
We should be able to archive (soft delete) conversations if they've been closed for a certain period of time. This will speed up our queries and remove unnecessary data from the UI. Also, since it's a soft-delete, we'll be able to retrieve the data if the user decides they want it back.

**Solution**
Let's add an `archived_at` field to the `conversations` table and use the presence of that field to determine whether or not the conversation is archived. (This gives us the benefit of knowing exactly when the conversation was archived, as opposed to just using a flag or "status=archived" field.)

Steps:
- Create migration to add `archived_at` field to `conversations` table
- Add method to archive conversation on `ChatApi.Conversations` context module
  - e.g. something like `ChatApi.Conversations.archive_conversation(conversation_id)`
  - This will simple update the conversation to have `archived_at: DateTime.utc_now()` 
- Update conversation query methods (e.g. `ChatApi.Conversations.list_conversations_by_account`, `ChatApi.Conversations.find_by_customer`) to ignore conversations where an `archived_at` field is not `null`
- **Write tests!**

**Testing**
Please add tests to `test/chat_api/conversations_test.exs` and make sure they pass with `mix test` :) 

**Context**
https://github.com/papercups-io/papercups/issues/334

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by reichert621** [comment]
cc @daskycodes if you're interested!

**Comment by daskycodes** [comment]
Thank you @reichert621 I will have a go at that :)

**Comment by reichert621** [comment]
done!
