### ISSUE TITLE
Send conversation state updates to Slack conversation thread

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#354]
**Problem**
We don't send any notification to our Slack integration when a conversation is closed, prioritized, archived, etc.

This makes it hard to know the state of a conversation if you're only looking at it in Slack.

**Solution**
Let's send the following messages to the Slack conversation thread when necessary:
- Conversation is closed: _This conversation has been closed._
- Conversation is reopened: _This conversation has been reopened._
- Conversation is archived: _This conversation has been archived._
- Conversation is deleted: _This conversation has been deleted._
- Conversation is marked a priority: _This conversation has been prioritized._
- Conversation is marked a non-priority: _This conversation has been de-prioritized._

Note that the messages should be formatted in italics (or some other different styling) in the markdown sent to Slack in order to make it clear that it ISN'T a message from a user.

**Additional context**
Eventually we'll want to make it possible to close/reopen/prioritize/etc a conversation from Slack, but that's not within the scope of this ticket.

**Testing**
You'll need to set up our Slack integration in order to test this. But please also add some unit/integration tests as well if you can!

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by jalford14** [comment]
Mind if I take a stab at this?

**Comment by reichert621** [comment]
Sure @jalford14! It might be slightly annoying because setting up Slack locally is kind of a pain, so let me know if you need any help :) 

Here are the docs for Slack btw: https://github.com/papercups-io/papercups/wiki/Setting-up-Slack
