### ISSUE TITLE
Wrong age shown for message

### ISSUE THREAD

**Issue by danielfaust** [papercups-io/papercups#376]
**Describe the bug**

When clicking on the lower right chat button on https://papercups.io/ so that the widget pops up, I get the following message:

> Hi there! Send us a message and we'll get back to you as soon as we can. In the meantime, check out our demo!
> 
> Papercups · Sent 60 minutes ago

**Expected behavior**

> Papercups · Sent 60 minutes ago

should be

> Papercups · Sent 1 second ago

**Screenshots**
![image](https://user-images.githubusercontent.com/320098/98292448-03e3dc00-1fad-11eb-931b-92dfe83b3f19.png)

**Additional context**
My TZ is Europe/Berlin and we've moved from DST (CEST = UTC+2) to normal time (CET = UTC+1) on 25. October 2020.

**Comment by reichert621** [comment]
thanks for flagging this @danielfaust! this is a known issue (https://github.com/papercups-io/chat-widget/issues/62)

**Comment by reichert621** [comment]
hey @danielfaust! i think this should be fixed now -- can you double check for me and let me know if I can close this?

**Comment by danielfaust** [comment]
Hi @reichert621 it's fixed. Great job!

**Comment by reichert621** [comment]
glad to hear it, thanks for flagging this!
