### ISSUE TITLE
Add support for Flutter

### ISSUE THREAD

**Issue by Immortalin** [papercups-io/papercups#380]
You can do the same as the React Native widget and put everything in a WebView.

**Comment by reichert621** [comment]
Yup, that's the plan! Would you be interested in trying to tackle this @Immortalin?

**Comment by reichert621** [comment]
For reference, this is all our React Native library does: https://github.com/papercups-io/chat-widget-native/blob/master/src/index.tsx

**Comment by aguilaair** [comment]
I may be interested in tackling this, I'll take a look at what I can do!

**Comment by aguilaair** [comment]
https://github.com/aguilaair/papercups_flutter -- Very rough still, but it's a start

**Comment by reichert621** [comment]
awesome @aguilaair! this looks great so far 🎉 🎉 🎉 

do you happen to have any experience with creating packages in Dart? (I don't have any experience with Dart, so I'm not sure... is it similar to creating a new npm module? 🤷)

**Comment by aguilaair** [comment]
I'm afraid I have no experience with new npm modules so I cannot really judge 😅
I'll send over the basic docs for creating a package if you want to take a look: https://flutter.dev/docs/development/packages-and-plugins/developing-packages

**Comment by reichert621** [comment]
no worries, thanks!

**Comment by Immortalin** [comment]
@reichert621 I think papercups flutter can now be added to the docs.

**Comment by reichert621** [comment]
🎉
