### ISSUE TITLE
How to prevent multiple accounts on the same server

### ISSUE THREAD

**Issue by avorio** [papercups-io/papercups#383]
Hi there,

I'd like to use Papercups for a single project — the default multi-tenancy approach does not work for my use case.

Is there a way to disable the creation of new accounts once it's been deployed?

Thanks!

**Comment by reichert621** [comment]
hey @avorio! yes :) if you set the `PAPERCUPS_REGISTRATION_DISABLED` environment variable to `1` or `true`, it will prevent anyone else from being able to register for an account unless they have an invitation link from you

**Comment by avorio** [comment]
> hey @avorio! yes :) if you set the `PAPERCUPS_REGISTRATION_DISABLED` environment variable to `1` or `true`, it will prevent anyone else from being able to register for an account unless they have an invitation link from you

Fantastic! That worked. Thank you so much!
