### ISSUE TITLE
Add "Timezone" data to initial Slack conversation thread

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#388]
**Problem**
This is a useful proxy for knowing where the user is located. It should be easy to just add this to the initial message in our Slack conversation threads.

**Solution**
Add "Timezone" to initial Slack conversation thread if it exists. If it doesn't exist, just display "N/A"

The code will go here: https://github.com/papercups-io/papercups/blob/master/lib/chat_api/slack.ex#L278-L300

**Testing**
You may need to set up our Slack integration locally to test this.

Here are the docs: https://github.com/papercups-io/papercups/wiki/Setting-up-Slack

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by kamilpikula** [comment]
hi @reichert621, I think I'll add this feature, you can assign to me. :)

**Comment by reichert621** [comment]
sounds good, thanks @kamilpikula!

**Comment by cheeseblubber** [comment]
@reichert621 closing now since it looks merged feel free to reopen
