### ISSUE TITLE
Removed unused variables in tests

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#389]
**Problem**
When running `mix test`, I see a lot of warnings for unused variables.

**Solution**
Let's either remove these variables, or use them if necessary.

**Testing**
Make sure `mix test` still passes!

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by edgrknye** [comment]
Hey @reichert621, I would love to take this up.

**Comment by reichert621** [comment]
go for it @edgrknye! since this is a pretty small issue i'll take the first PR from whoever gets this done :)
