### ISSUE TITLE
Optimize the query in `ChatApi.Conversations.list_conversations_by_account`

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#391]
**Problem**
This query could be made more efficient. We currently fetch all conversations ordered by `:inserted_at`, while in the UI we display them based on how recently a message was sent within it (i.e. `message.sent_at`).

**Solution**
Optimize this query to order the results by the most recently sent message associated with the conversation.

It might also be helpful to write a query to fetch all conversations with only the most recent message included along with it, rather than ALL associated messages. (Our current query won't scale...)

Method: https://github.com/papercups-io/papercups/blob/e4fb1b82d6fb4d388b4effc030efbd01c500b159/lib/chat_api/conversations.ex#L33-L41

**Testing**
Please write test cases in `/test/chat_api/conversations_test.exs`

Also please verify that this doesn't break how conversations are loaded in the UI!

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by WLSF** [comment]
Hi Alex, can I have this one?

**Comment by reichert621** [comment]
sure @WLSF! assigning you for now 👍
