### ISSUE TITLE
As a customer support agent I want to be able to add a private note to a customer

### ISSUE THREAD

**Issue by cheeseblubber** [papercups-io/papercups#417]
**Problem**
I want to add private notes to a customer so in case there is a reoccurring issue next time I have more context. A private note is only shown to the company and not to the customer

**Additional context**
On the side bar there should be a private note section where you can add the note 

On the side bar:
It should show  private notes related to a customer
It should show private notes related to a conversation

A conversation can have multiple private notes

Implementation: 
This story can be broken up in to client side and backend.
Backend would be a rest endpoint for private note with relations to customer and conversation
Client side should render private notes associated to customer and conversation with the ability add, edit the private note

The private note can be modified by anyone in the same company

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by reichert621** [comment]
let's make sure we distinguish between private notes on customers vs private notes/messages in a conversation -- these might need to be handled separately

TODOs for this:
- [ ] draft a spec of the models and APIs we'll need to create/modify
- [ ] write ticket(s) for building out those models/APIs
- [ ] write ticket(s) for building out the UI

we can probably just take inspiration from Intercom or Chatwoot (both from an backend/API design, as well as frontend/UX design)

**Comment by reichert621** [comment]
(spec will be written here: https://github.com/papercups-io/papercups/issues/433)
