### ISSUE TITLE
/logo192.png file not found

### ISSUE THREAD

**Issue by arjenrschat** [papercups-io/papercups#422]
**Describe the bug**
file not found logo192.png

**To Reproduce**
Open any page in the browser it wants to load 
<link rel="apple-touch-icon" href="/logo192.png">

**Additional context**
[error] #PID<0.1191.0> running ChatApiWeb.Endpoint (connection #PID<0.1190.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: GET /logo192.png
** (exit) an exception was raised:
    ** (File.Error) could not read file "./priv/static/index.html": no such file or directory
        (elixir 1.10.4) lib/file.ex:353: File.read!/1
        (chat_api 0.1.0) lib/chat_api_web/controllers/page_controller.ex:6: ChatApiWeb.PageController.index/2
        (chat_api 0.1.0) lib/chat_api_web/controllers/page_controller.ex:1: ChatApiWeb.PageController.action/2
        (chat_api 0.1.0) lib/chat_api_web/controllers/page_controller.ex:1: ChatApiWeb.PageController.phoenix_controller_pipeline/2
        (phoenix 1.5.5) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (chat_api 0.1.0) lib/chat_api_web/endpoint.ex:1: ChatApiWeb.Endpoint.plug_builder_call/2
        (chat_api 0.1.0) lib/chat_api_web/endpoint.ex:1: ChatApiWeb.Endpoint."call (overridable 3)"/2
        (chat_api 0.1.0) lib/plug/debugger.ex:132: ChatApiWeb.Endpoint."call (overridable 4)"/2
        (chat_api 0.1.0) lib/chat_api_web/endpoint.ex:1: ChatApiWeb.Endpoint.call/2
        (phoenix 1.5.5) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.8.0) /Users/arjenschat/Sites/papercups/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.8.0) /Users/arjenschat/Sites/papercups/deps/cowboy/src/cowboy_stream_h.erl:300: :cowboy_stream_h.execute/3
        (cowboy 2.8.0) /Users/arjenschat/Sites/papercups/deps/cowboy/src/cowboy_stream_h.erl:291: :cowboy_stream_h.request_process/3
        (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

**Comment by reichert621** [comment]
hopefully fixed in https://github.com/papercups-io/papercups/commit/c57e461c16568fc3232f7423af906b60b2e34476, but i'm having some trouble reproducing... let me know if this is still an issue!
