### ISSUE TITLE
Customer Notes v1

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#433]
**Problem**
As a user, I should be able to add notes to a customer.

At a high level, this will involve the following tasks:
- Creating a new table/model in the db to store the notes
  - For reference, here's Intercom's Notes API: https://developers.intercom.com/intercom-api-reference/v0/reference#note-model
- Creating the APIs to create/read/update/delete a note
  - And ideally some tests! (Phoenix will autogenerate some tests)
- Updating the conversation sidebar UI to display notes and allow the user to add/edit/delete notes

For reference, here's how notes look in Intercom's UI:
<img width="1014" alt="intercom-sidebar-notes" src="https://user-images.githubusercontent.com/5264279/100820971-6483fe80-341d-11eb-813f-174efc7f2c26.png">

(Note that Intercom calls them "leads"... we should still call them "customers" for now to be consistent with the rest of our app)

**Solution**

TODO: outline the above in more details:
- The fields we should include on the Notes model/table
- The API endpoints we'll set up for this feature
- A proposal for what the UX should be like
  - (e.g. do we create/edit the notes inline vs in a modal?)

(For reference, here's how we broke down the tasks for our Reporting dashboard: https://github.com/papercups-io/papercups/issues/252)

(Also if you're new to Elixir/Phoenix, here's an example from a while ago showing how we set up one of our Conversations APIs: https://github.com/papercups-io/papercups/blob/master/docs/examples/add_conversations_api.md)

**Comment by reichert621** [comment]
@fkotsian mind if I assign this to you? 😄

**Comment by fkotsian** [comment]
3 pieces:

> - Creating a new table/model in the db to store the notes

Note
- author_id: int
- account_id: uuid
- customer_id: uuid
- body: text
- timestamps()

> - Creating the APIs to create/read/update/delete a note
>  - And ideally some tests! (Phoenix will autogenerate some tests)

NoteController

def create(conn, %{"note" => note_params}) do  # params = %{"body" => body}
  # require body
  # author_id = current_user, account_id = current_user.account
end

def index(conn, params) do
  # with %{account_id: account_id} <- conn.assigns.current_user do
  #   notes = Notes.list_notes(account_id)
  # render(conn, "index.json", notes: notes)
end

# NB: I kinda think we don't need this endpoint? Fetch 1 specific note? Notes will always be fetched in batches AFAICT
def show(conn, %{id => id}) do
  # Notes.get_note(id)
  # render(conn, "show.json", note: note)
end

def update(conn, %{"id" => id, "note" => note_params}) do
  # note = Note.get_note!(id)
  # with... update_note! do
  #   render (conn, "show.json", note: note)
  # end
end

def delete(conn, %{"id" => id}) do
  # note = Notes.get_note!(id)
  # with {:ok => %Note{}} <- Notes.delete_note!(note) do
  #   send_resp(conn, :no_content, "")
  # end
end

> - Updating the conversation sidebar UI to display notes and allow the user to add/edit/delete notes

- just a single textbox with a "Add Note" button below it for now (most MVP possible)
 - onclick, create note
 - validate note must be of length 1
- render all notes beneath textbox (mirror Intercom UI)

Sync up w Alex after to determine delete/etc flow


Open Qs:
- SPA approach (bootstrap notes on load via notes#index.json), or pass notes down in a special account_w_notes.json view?

**Comment by fkotsian** [comment]
UI notes:

- modals
- delete exp

**Comment by reichert621** [comment]
thanks for all the help on this @fkotsian 🎉
