### ISSUE TITLE
Being able to opt out of the automatic emails

### ISSUE THREAD

**Issue by makkiedavid** [papercups-io/papercups#441]
**Problem**
I wish to disable the e-mails automatically sent out after a customer has ended the session and I send them a message back.

**Additional context**
The company should have an option to opt out from automatic e-mails. Where this should be implemented is up to the developers. I suggest inside the config script tag, something along the lines of `sendEmails: true/false`

For further context: the e-mails I'm talking about are sent out by noreply@mail.heypapercups.io

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by reichert621** [comment]
hey @makkiedavid! would it work for you if we added this feature to the account settings page in the dashboard, rather than as a field on the chat widget?

**Comment by makkiedavid** [comment]
Hi @reichert621 this would work perfectly fine for me! :)

**Comment by makkiedavid** [comment]
Hi @reichert621, is there any progress on this?

**Comment by reichert621** [comment]
hey @makkiedavid sorry for the delay on this! hoping to get to it by next week

**Comment by makkiedavid** [comment]
Looking forward to it a lot! Thanks.

**Comment by reichert621** [comment]
hey @makkiedavid I added the backend logic for this but still need to implement the UI -- want me to just turn this off for your account manually for you in the meantime?

**Comment by makkiedavid** [comment]
@reichert621 turning it off for me would be great! I messaged you the e-mail I signed up with.
