### ISSUE TITLE
I wish to be able to translate certain texts in the chat window

### ISSUE THREAD

**Issue by makkiedavid** [papercups-io/papercups#442]
**Problem**
I wish to be able to edit all text inside of the chatbox for translation purposes

**Solution**
Being able to edit the text inside of a chatbox via the script config tag

**Additional context**
I am talking about the texts that we are not yet able to edit such as the "Sent just now" & "Enter your email". The reason I wish to edit those is because my target audience is Dutch. Thanks in advance!

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by reichert621** [comment]
@makkiedavid makes sense! making "Enter your email" editable should be easy, so we'll probably do that first :) 

("Sent just now" is dynamic, so that might be a bit trickier... since it shows up as "Sent 5 minutes ago", etc as time goes on)

**Comment by reichert621** [comment]
@makkiedavid quick updates -- the "Enter your email" portion of this should be done by the end of today 👍 (we'll be adding an `emailInputPlaceholder` option where you can customize it)

**Comment by makkiedavid** [comment]
Super! 😄

**Comment by reichert621** [comment]
@makkiedavid you should now be able to add `emailInputPlaceholder` to your Papercups config to customize it :)

**Comment by makkiedavid** [comment]
Working very well, thank you! I suppose this issue can be closed then?

**Comment by reichert621** [comment]
glad to hear it! editing dynamic text will probably not happen in the short term (unless we can think of a relatively simple way to do it), so i'm going to close this for now and move this task to https://github.com/papercups-io/chat-window/issues/21
