### ISSUE TITLE
New message notification sound not playing

### ISSUE THREAD

**Issue by arjenrschat** [papercups-io/papercups#446]
**Describe the bug**
When a new message comes no sound is played, because Firefox blocked it,
Raising: 
Failed to play notification sound: DOMException: The play method is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

**To Reproduce**
Use Firefox to receive messages,
After a few messages, the autoplay permissions is blocking the sound
<img width="700" alt="image" src="https://user-images.githubusercontent.com/25150192/101157272-23ad0500-362a-11eb-98eb-39fed59652b4.png">

**Expected behavior**
Indicate in the interface the notification sound is blocked and how to fix this

**Comment by reichert621** [comment]
hey @arjenrschat! i'm having trouble reproducing this... did you manually set the "block audio" permission, or did something happen automatically? is this only an issue in incognito?

**Comment by aguilaair** [comment]
This is a Firefox issue, mine has this default setting:
![image](https://user-images.githubusercontent.com/29983481/101172973-29aee000-3642-11eb-96af-053070478d95.png)

**Comment by reichert621** [comment]
ahh i see now, thanks for clarifying @aguilaair

**Comment by cheeseblubber** [comment]
Sounds like it isn't an issue closing now
