### ISSUE TITLE
Implement pagination for the `ChatApi.Customers.list_customers/1` method

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#450]
**Problem**
We currently fetch ALL customer records when we call the `ChatApi.Customers.list_customers/1` method (i.e. we set no `limit` or `offset` in our query, nor do we have cursors or anything like that)

This will not scale very well as more and more data gets added.

**Solution**
To start off, let's do the following:
- Implement another version of `ChatApi.Customers.list_customers(account_id)` that paginates the response, either by using a `limit` and an `offset` in the query, or cursors
  - Here's where the method lives in the code: https://github.com/papercups-io/papercups/blob/master/lib/chat_api/customers.ex#L22
  - Possible library for `limit/offset` approach: https://github.com/drewolson/scrivener_ecto
  - Possible library for cursor approach: https://github.com/duffelhq/paginator
- (Note: I'm not sure that the cursor approach would even work in this scenario, since we want to be able to e.g. "fetch page 2 of our list of customers", which I'm not sure is possible with cursors... but I have a very minimal understanding of how to use cursors, so I may be wrong here)
- This new method should just be called something like `ChatApi.Customers.list_customers_paginated(account_id, pagination_options)`, and should only return, let's say, 50 records at a time

**Testing**
For the sake of this ticket, DO NOT use this new method in the `GET /api/customers` endpoint. We just want to set up the method itself, and write some tests showcasing how it works.

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by flmel** [comment]
I can take on it
