### ISSUE TITLE
Implement pagination for the `ChatApi.Conversations.list_conversations_by_account/2` method

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#451]
**Problem**
We currently fetch ALL conversation records when we hit the `ChatApi.Conversations.list_conversations_by_account/2` method (i.e. we set no `limit` or `offset` in our query, nor do we have cursors or anything like that)

This will not scale very well as more and more data gets added.

**Solution**
To start off, let's do the following:
- Implement another version of `ChatApi.Conversations.list_conversations_by_account(account_id, filters)` that paginates the response, ideally using cursors
  - Here's where the method lives in the code: https://github.com/papercups-io/papercups/blob/master/lib/chat_api/conversations.ex#L24
  - Possible library for cursor approach: https://github.com/duffelhq/paginator
- (Note: I have a very minimal understanding of how to use cursors, so I may be wrong that this is the best approach... feel free to push back!)
- This new method should just be called something like `ChatApi.Conversations.list_conversations_by_account(account_id, filters, pagination_options)`, and should only return, let's say, 50 records at a time
- Conversations should be sorted by **most recent message** -- not sure how tricky this will be given it may require some `join` queries on the `messages` table, but maybe we'll just have to add a new field for `last_message_sent_at` or something 🤔 

**Testing**
For the sake of this ticket, DO NOT use this new method in the `GET /api/conversations` endpoint. We just want to set up the method itself, and write some tests showcasing how it works.

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by psolvy** [comment]
Hi
I'll take this one)

**Comment by reichert621** [comment]
sounds good @psolvy! I'll assign you for now :)

**Comment by flmel** [comment]
Hi  @psolvy, @reichert621

If we want to use prams such as limit offset  eg. _`%{page_size: 5, page_number: 10}`_ we cant use cursor based pagination.
I have opened a [pr](#490) which uses [scrivener](https://github.com/drewolson/scrivener_ecto) (offset based pagination). 

also this is related with #332

**Comment by reichert621** [comment]
@flmel since conversations will be fetched as the user scrolls (or with e.g. a "Load more" button), rather than in a table with pages, i think it should be fine to use cursor-based pagination here 👍

**Comment by psolvy** [comment]
> @flmel since conversations will be fetched as the user scrolls (or with e.g. a "Load more" button), rather than in a table with pages, i think it should be fine to use cursor-based pagination here 👍

ок

**Comment by reichert621** [comment]
hey @psolvy! any updates on this?

**Comment by fmterrorf** [comment]
HI :wave: If this is up for grabs, I'd like to work on this! Thanks

**Comment by reichert621** [comment]
hey @fmterrorf! let me check in with @flmel to see if he's still interested in working on this, i think he may have had some questions that weren't addressed in the issue description

**Comment by fmterrorf** [comment]
HI @reichert621 Yeah! I'd like to work on this one

**Comment by reichert621** [comment]
ok great! assigning you for now 🚀

**Comment by fmterrorf** [comment]
> Conversations should be sorted by most recent message -- not sure how tricky this will be given it may require some join queries on the messages table, but maybe we'll just have to add a new field for last_message_sent_at or something thinking

Yeah this one is tricky. I've opened a draft PR for this, but i dont feel too good about it :sweat_smile:

**Comment by reichert621** [comment]
oops @fmterrorf just saw this!

i wrote this in your PR just now:
> looks great! i need to take a little more time to review but wanted to get your thoughts on something... after working on this, do you think it would make our lives a lot easier to just add a new field to `conversations` that holds the `last_message_sent_at`/`last_activity_at`, and make sure to update that whenever a message is created?

it seems like it might make sense to go that route instead... what do you think?

**Comment by fmterrorf** [comment]
Yeah i think that's the way to go. It'll make pagination & ordering better

**Comment by reichert621** [comment]
sounds good!

**Comment by fmterrorf** [comment]
Forgot to add `fixes: #451` on my last PR :sweat_smile: but we could probably close this issue
