### ISSUE TITLE
Conversation Private Notes v1

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#452]
**Problem**
As a user, I should be able to add a private note to a conversation.

At a high level, this will involve the following tasks:
- Updating the `messages` table to support private notes as well
  - Or, creating a new table/model in the db for private conversation notes, if we decide this is preferable
- Making sure that private notes are only available in the admin/agent UI
  - This also means preventing them from being broadcast to "public" channels (for examples, look for instances of the `Messages.broadcast_to_conversation!` method in the codebase)
  - _Note that there will be several places that we'll need to ensure this doesn't happen!_
- Updating the conversation textarea for new messages to include an option to send a private note
- Updating the conversation messages UI to display private notes differently

For reference, here's how private conversation notes look in Intercom's UI:
<img width="811" alt="Screen Shot 2020-12-05 at 6 56 12 PM" src="https://user-images.githubusercontent.com/5264279/101297333-74715900-37f6-11eb-9770-6c9c78cea6f3.png">

...vs a regular message:
<img width="842" alt="Screen Shot 2020-12-05 at 6 56 05 PM" src="https://user-images.githubusercontent.com/5264279/101297332-73d8c280-37f6-11eb-9669-69fdf9cfce8d.png">

**Solution**
TODO: outline the above in more details:
- If we decide to extend the `messages` table/mode, list the fields we should add
  - For some background, this is how Intercom and Chatwoot seem to handle it... Intercom has a `subtype: "note"` and `admin_only: true`, whereas Chatwoot has `private: true`... I would probably opt for something like `type: "note", private: true`, but that's just me. Happy to chat more about this!
- If we decide to create a new table/model, list all the fields it should have
- The API endpoints we'll set up for this feature
- A proposal for what the UX should be like
  - (We should probably just more-or-less copy Intercom 🤷)

**Thoughts and considerations**
One thing that will be a bit tricky to handle is the fact that both agents and customers (i.e. both sides of the chat) are listening in on the same channel, so that every time a new message is created, both are alerted.

I suppose that creating a new table to store private messages would make this a little bit easier, but I'm not sure that the cost is worth it. (Still need to think about that some more though, I could be persuaded otherwise!)

Otherwise, we would have to figure out a good way to separate the conversation channels that the admin and customer are listening to. And then, whenever a new message is created, we either broadcast it to both (for public messages), or just the admin channel (for private messages). I _think_ that's my preferred approach, but that's just my gut instinct.

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by jalford14** [comment]
Hey @reichert621, just a few thoughts from our very brief discussion yesterday. I've gone through Intercoms API docs and see how they differentiate between `messages` and `notes`. It looks like they're two different models entirely. 

![image](https://user-images.githubusercontent.com/7582183/101368267-f0aa8180-3874-11eb-9e29-2b2dcb2e4af8.png)
![image](https://user-images.githubusercontent.com/7582183/101368312-fd2eda00-3874-11eb-82d8-fb75908b6054.png)

To me, this makes the most sense to seperate `Notes` from `Messages` but I'm curious what your thoughts are.

**Comment by reichert621** [comment]
hey @jalford14! so the `Notes` API you mentioned above is actually "customer/contact notes", not private conversation notes -- we have a separate ticket set up for that in https://github.com/papercups-io/papercups/issues/433 :) 

Intercom's public API doesn't seem to expose the functionality around private conversation notes, but when I looked at the network responses in their dashboard i noticed that they use the `Messages` model as well, indicating private notes with `subtype: "note", admin_only: true`

**Comment by reichert621** [comment]
done in https://github.com/papercups-io/papercups/pull/521
