### ISSUE TITLE
Add `object` field to JSON views to reference the name of the model

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#453]
**Problem**
One thing I like about Stripe's API responses is that they include the name of the model in the JSON response payload as an `object` field. For example, in their Customer object (https://stripe.com/docs/api/customers/object) they have:
```js
// Customer API response JSON:
{
  "id": "cus_xxxxxxx",
  "object": "customer", // <------
  "address": null,
  "balance": 0,
  "created": 1607300509,
  // etc
}
```

**Solution**
Let's add an `object` field to all our JSON views where it references a clear model (e.g. "message", "customer", "conversation", etc.)

Here's an example of doing this for the account view: https://github.com/papercups-io/papercups/commit/f1ff0e189d98a70475ab1352eb96b9a6cd6fdb16

For this ticket, please do the same type of thing for the appropriate views in the [lib/chat_api_web/views](https://github.com/papercups-io/papercups/tree/master/lib/chat_api_web/views) directory. (Just ignore the `billing_view`, `changeset_view`, `error_view`, and any file without `_view` in the name)

**Testing**
As in this commit -- https://github.com/papercups-io/papercups/commit/f1ff0e189d98a70475ab1352eb96b9a6cd6fdb16 -- it might be nice to include this in some controller tests (e.g. maybe only one per controller)

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by edgarkanye** [comment]
I would like to take this up

**Comment by reichert621** [comment]
sure @edgarkanye, i'll assign you for now :)
