### ISSUE TITLE
[Free tier] Set up a worker to archive stale conversations after 30 days

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#454]
**Problem**
We want to limit data retention for users in our hosted free tier. Let's start by archiving conversations that haven't been active in >30 days and are not marked as a priority (i.e. favorited/starred).

**Solution**
Create a worker with Oban ([example](https://github.com/papercups-io/papercups/blob/master/lib/workers/archive_conversations.ex)) that archives conversations where the following conditions are true:
- the account is on our free tier (e.g. `account.subscription_plan == "starter"`)
- the last message sent in the conversation was created >30 days ago (e.g. `message.inserted_at`)
- the conversation is not prioritized (e.g. `conversation.priority == "not_priority"`)

(We could name this worker `ChatApi.Workers.ArchiveFreeTierConversations`, or something like that)

_:warning: Note that we should probably rename the worker in https://github.com/papercups-io/papercups/blob/master/lib/workers/archive_conversations.ex to be something more like `ChatApi.Workers.ArchiveClosedConversations`_

**Additional context**
For context, the relations work as follows:
- `conversation` belongs to `account` (via `conversation.account_id`)
- `message` belongs to `conversation` (via `message.conversation_id`); `conversation` has many `message`s

Also related to https://github.com/papercups-io/papercups/issues/444

**Testing**
Please add some tests for the method that handles the above logic :)

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by edgarkanye** [comment]
@reichert621 I would like to take this on.

**Comment by reichert621** [comment]
sure @edgarkanye! i'll assign you for now 👍

**Comment by reichert621** [comment]
thanks @edgarkanye! (forgot to close this 😅 )
