### ISSUE TITLE
Add `closed_at` field to Conversation model

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#486]
**Problem**
We need to be able to calculate how long it takes for a conversation to be closed ("resolved").

Right now the way we determine if a conversation is closed is by looking at the `status` field, which can currently only be `"open"` or `"closed"`.

**Solution**
- Set up a database migration to add the `closed_at` field to the `conversations` table (as a `utc_datetime`)
- Update the `ChatApi.Conversations.Conversation` module appropriately (e.g. add the new field, also add it to the `changeset`)
- Update the `ChatApi.Conversations.update_conversation` method to set the `closed_at` field to the current time if a `status: "closed"` update is coming through (and if a `status: "open"` update is coming through, make sure to unset the `closed_at` field by setting it to `null`/`nil`)
  - Not sure what the conventional way of handling this is... I wonder if it's possible to do in the `changeset` method? Might ask the Elixir Slack group what the most idiomatic way is 🤔 
  - **Update:** this seems like it might be the best approach: https://elixirforum.com/t/adding-calculated-field-on-save/14745/3

**Describe alternatives you've considered**
It might make sense to eventually have separate, explicit API endpoints for opening/closing a conversation (rather than just handling the logic in the `update` method), but for now the above solution should require less upfront refactoring.

**Additional context**
This will be necessary to handle https://github.com/papercups-io/papercups/issues/484

**Testing**
We'll want to write tests to make sure that the `closed_at` field is set/unset appropriately based on the `status` updates.

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by jeepers3327** [comment]
Can I work on this one?

**Comment by reichert621** [comment]
sure @jeepers3327! i'll assign you for now 👍

**Comment by reichert621** [comment]
thanks @jeepers3327! (forgot to close this 😅 )
