### ISSUE TITLE
Figure out the best way to determine how long it takes to reply to a conversation

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#487]
**Problem**
Our users want to measure how long it takes from a conversation being created to the first reply from an agent.

At the moment we could determine this by querying conversations and messages and comparing `conversation.inserted_at` with `message.inserted_at` for the first message that comes from an agent (i.e. the first message with a `user_id`).

However I'm a little worried that this might end up being an expensive query, so I'm not sure if it's worth adding a new field (e.g. `first_replied_at`?) to track when this happens.

**Solution**
I'm not sure what the best solution is, but I imagine it's either:
- Write a query that returns `conversation.inserted_at` vs `first_agent_reply_message.inserted_at`
- OR, add a new field to the `conversations` table (e.g. `first_replied_at`) and set this field whenever we detect the initial agent reply to a conversation
  - Then, to query and compare these fields is trivial

**Testing**
We should definitely write some tests to make sure this works as expected, regardless of which approach we take :) 

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by cheeseblubber** [comment]
I prefer the solution of adding a first_replied_at field mainly because the queries is going to be pretty expensive as the number of conversations of a company grows and it is probably better to cache the calculation so we don't have to do it every time.

I plan on setting the first_replied_at field when the first message from the agent is first sent on message_controller's create function

**Comment by cheeseblubber** [comment]
@reichert621 Probably plan on creating a function in notification_channel.ex "maybe_update_first_replied_at" that checks if a conversation has a "first_replied_at" field and then update the field there. 

Other options were doing it in the message controller on create but it felt like notification_channel.ex fits a bit better

**Comment by reichert621** [comment]
@cheeseblubber sounds good, tbh there's probably a bit of refactoring we should do eventually to handle the fact that we can create messages from 3 sources as an "agent": the dashboard (via websockets, `notification_channel`), the API (via the `message_controller`), and Slack (via `slack_controller` webhook)

i think starting off in the `notification_channel` makes the most sense 👍 

one nice thing about this update is that we can always backfill data pretty easily (since we can just query all conversations with messages and see when the first message from an agent shows up)

**Comment by cheeseblubber** [comment]
WIP: https://github.com/papercups-io/papercups/tree/track-agent-response-time
