### ISSUE TITLE
[Tech debt] Fix dialyzer typespec warnings for missing types

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#534]
**Problem**
When we run `mix dialyzer` in the project, we can see all the warnings based on our typespecs:
<img width="574" alt="Screen Shot 2021-01-19 at 5 34 48 PM" src="https://user-images.githubusercontent.com/5264279/105101606-b12ea200-5a7c-11eb-964d-38b435818810.png">

Let's start off by fixing the `unknown_type` warnings by adding these types to the relevant models!

**Solution**
For all the models with a missing type definition, let's add one to the same module that defines their schema. (See `lib/chat_api/messages/message.ex` for an example: https://github.com/papercups-io/papercups/blob/master/lib/chat_api/messages/message.ex#L10-L28)

Avoid using the `any()` type as much as you can :) 

(Also no need to worry about any of the other dialyzer warnings for the sake of this ticket!)

**Describe alternatives you've considered**
I was hoping Ecto would autogenerate these types, but apparently it doesn't 🤷 

**Testing**
Make sure these warnings go away when you run `mix dialyzer` after adding the appropriate type definitions

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by hieutle2011** [comment]
Hi, can i help on this?

**Comment by reichert621** [comment]
sure! I'll assign you for now @hieutle2011 👍

**Comment by reichert621** [comment]
thanks @hieutle2011!
