### ISSUE TITLE
Set up API for retrieving previous conversation

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#538]
**Problem**
Users want to be able to see previous conversations from the context of an existing conversation, in order to view what was discussed previously with a customer (if that customer had already messaged them in the past).

**Solution**
- Write the method to query for previous conversation, given a current conversation.
- Create the API endpoint for this as well (e.g. `GET /api/conversations/:id/previous`)

**Describe alternatives you've considered**
We could possibly just do this in the UI, but that could get a bit hacky and probably wouldn't scale well (e.g. as we add pagination)

**Additional context**
Still need to figure out if it makes sense to retrieve the full conversation details with the API endpoint, or just an ID (and then use the basic `GET /api/conversations/:id` method after that)

**Testing**
Please write unit tests!

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by aguilaair** [comment]
I think the next step could be a way to get all previous conversations, that'd help with customers seeing all their conversations

**Comment by reichert621** [comment]
@aguilaair this is just for the admin/dashboard side, we can already retrieve customer conversations with the `ConversationController.find_by_customer` endpoint but for now we're avoiding displaying these on the customer side

the point of this ticket is just to make it easier to link one conversation to another in the dashboard, but we're still figuring out the best way to do that
