### ISSUE TITLE
Include `account_id` in more Ecto (SQL) `where` clauses

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#54]
For API endpoints that should be secured (e.g. these: https://github.com/papercups-io/papercups/blob/master/lib/chat_api_web/router.ex#L52-L56) we need to make sure we're always limiting the data returned to the current user's `account_id`

The account id can be accessed on `conn.assigns.current_user` in each request like so:
https://github.com/papercups-io/papercups/blob/master/lib/chat_api_web/controllers/conversation_controller.ex#L11 (there are probably more idiomatic ways to do that, but this works for now 🤷‍♂️ )

Here's an example of filtering by `account_id` in one of the contexts: https://github.com/papercups-io/papercups/blob/master/lib/chat_api/messages.ex#L21

**Comment by masonhensley** [comment]
Potentially related to #127

**Comment by a8t** [comment]
Bodyguard actually offers [schema-level authorization helpers](https://github.com/schrockwell/bodyguard#schema-scopes), but I think context- or controller-level is enough. I think we should close this in favour of the more recent issues.

**Comment by reichert621** [comment]
closing in favor of these more specific tickets: https://github.com/papercups-io/papercups/issues/641
