### ISSUE TITLE
Support private notes in Slack integration

### ISSUE THREAD

**Issue by Twixes** [papercups-io/papercups#560]
**Problem**
Private notes added in #521 are great – they are however not sendable from the Slack integration, nor are they viewable there.

**Solution**
There should be an explicit way to send a private note from Slack (e.g. the message is considered a note when if it begins with a slash), and when a private note is sent from somewhere else (i.e. the web app), it should in turn be displayed in the Slack thread.

**Additional context**
A use case which would make this specifically useful is mentioning teammates (other _agents_) inside Slack, e.g. for assistance, without notifying the customer.

**Testing**
Not sure how you test the Slack integration, but basically sending a message with in Slack and verifying that it is then saved as a note (and NOT as a reply) in Papercups would cover this end-to-end.

**Comment by reichert621** [comment]
@Twixes I did a little research into this, and it looks like Slack doesn't support slash commands in reply threads for some reason 😞 (see "**Limitations on use**" in https://api.slack.com/interactivity/slash-commands#enabling-interactivity-with-slash-commands__what-are-slash-commands)

So I'm thinking there are a couple alternatives to how we can handle this:
1. Any messages that @mentions the Papercups app/bot is considered a note
2. Any message that starts with `[note]` or 🔒 or `;;` or some other agreed upon string/emoji is considered a note
3. Something else?

Curious to hear your thoughts/preference

**Comment by Twixes** [comment]
I think 1. could occasionally backfire if someone wants to do this intentionally. 2. sounds pretty good, just that the prefix should be simple to enter (definitely not an emoji) and practically never used in an online conversation or in some support case at the start of the message. I was thinking a backslash would work well.

**Comment by reichert621** [comment]
backslash sounds good for now :+1:

**Comment by reichert621** [comment]
done in https://github.com/papercups-io/papercups/pull/562!
