### ISSUE TITLE
Close and Reopen in Reply from Slack

### ISSUE THREAD

**Issue by Twixes** [papercups-io/papercups#564]
**Problem**
Currently to close or reopen a conversation, you have to click the link to the Papercups dashboard and do it there.

**Solution**
It'd be much smoother and faster if at the bottom of the initial Slack message linked to a Papercups conversation (below Status), there was button "Close" or "Reopen" - based on the current status of the conversation.

<img width="504" alt="Screen Shot 2021-02-08 at 01 34 39" src="https://user-images.githubusercontent.com/4550621/107164600-11e03900-69b0-11eb-905a-7e086d5f7a05.png">

**Comment by reichert621** [comment]
Done in https://github.com/papercups-io/papercups/pull/566!
