### ISSUE TITLE
Fix how we save IP addresses of customers

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#57]
Since we currently get very little info on the anonymous customers that interact with the chat widget, we save their IP addresses (so we can eventually do a location lookup)

At the moment, we use `conn.remote_ip` (https://github.com/papercups-io/papercups/blob/master/lib/chat_api_web/controllers/customer_controller.ex#L17), but this ~seems to only return private IP addresses.

Investigate this as a possible solution? https://www.cogini.com/blog/getting-the-client-public-ip-address-in-phoenix/

**Comment by henrymori** [comment]
I'll take a stab at this if it's not taken yet!

**Comment by reichert621** [comment]
yes please @henrymori! (and as an added bonus, if you know of any good APIs to get locations from IP addresses, let me know 😬)

**Comment by henrymori** [comment]
> yes please @henrymori! (and as an added bonus, if you know of any good APIs to get locations from IP addresses, let me know 😬)

Sounds good, thanks! I have some ideas on reverse geocoding I can kick around once we get the IP addresses accurately captured (at that point, we should probably start a separate GH issue for tracking IP -> geocoded information mapping).

**Comment by reichert621** [comment]
for sure, will definitely want to track that in a separate ticket 👍
