### ISSUE TITLE
Basic text search through tags

### ISSUE THREAD

**Issue by cheeseblubber** [papercups-io/papercups#571]
I want to be able to do basic string text search through tags of descriptions and tags on tags page

**Comment by imjared** [comment]
i'd be down to take a pass at this. would you expect all searching to be done on the client against a list of fetched tags?

**Comment by reichert621** [comment]
@imjared yup let's just do a client side search for now :) 

maybe just put a search input above the tags table (in the `TagsOverview.tsx`) here:
<img width="1096" alt="Screen Shot 2021-03-22 at 10 22 11 AM" src="https://user-images.githubusercontent.com/5264279/112005005-bb126700-8af8-11eb-9e57-397efc9d74dd.png">

**Comment by reichert621** [comment]
@imjared I added this on the customers overview today if you want to take a look for reference :) https://github.com/papercups-io/papercups/blob/master/assets/src/components/customers/CustomersPage.tsx#L158-L165

<img width="806" alt="Screen Shot 2021-03-22 at 6 57 54 PM" src="https://user-images.githubusercontent.com/5264279/112068630-a954b200-8b40-11eb-958c-e888347273bc.png">

**Comment by cheeseblubber** [comment]
Closing this since its been merged in. Feel free to reopened if its not completed yet
