### ISSUE TITLE
Have tabs to switch between React and HTML example in getting started 

### ISSUE THREAD

**Issue by cheeseblubber** [papercups-io/papercups#574]
We should support more example in different languages to prevent issues from set up. We probably want something like what stripe has as an example
<img width="885" alt="Screen Shot 2021-02-12 at 10 45 57 AM" src="https://user-images.githubusercontent.com/4218509/107789423-91a73400-6d1f-11eb-9f2e-ab1b0de1b347.png">

**Comment by a8t** [comment]
I can work on this.

**Comment by reichert621** [comment]
thanks @a8t! assigning you for now :)

**Comment by aguilaair** [comment]
Maybe add flutter in the future too? (Maybe not yet because not all features are integrated, specifically agent availability)

**Comment by a8t** [comment]
Should the issue be closed? Or edited, if we still want it terminal-styled like above.

**Comment by reichert621** [comment]
I’ll let Kam decide :)

**Comment by reichert621** [comment]
going to close for now -- feel free to create another ticket if we want to update the design later @cheeseblubber!
