### ISSUE TITLE
Delete user invitation links after they are used

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#58]
Right now user invitations (from `user_invitations` table) never get deleted, but we should delete them after they are successfully used.

This is where we currently use it: https://github.com/papercups-io/papercups/blob/master/lib/chat_api_web/controllers/registration_controller.ex#L14

If the registration is successful, the `user_invite` record should be deleted.

**Comment by n1arash** [comment]
Hi,
I want to send a PR on this.
Isn't this better that we add a boolean flag for user invite and keep the record that will invalidate the invitation link and save the record in the database for future use like analytics or showing past invitations?

**Comment by reichert621** [comment]
hmm yeah @n1arash, good point -- maybe we can add a flag like you suggested or just update the `expires_at` field to the current time, and then make sure we check against expiration before allowing the invitation to be used? what do you think?

**Comment by n1arash** [comment]
I think updating the `expires_at` field can do the job, and also we can send an appropriate error to the frontend if a user used the link again with a 403 status header.

**Comment by reichert621** [comment]
sounds perfect @n1arash

**Comment by rlanga** [comment]
Hi,
I've done some sample modifications that delete the invite token after user creation is successful. I also split out the logic for cases when an invite token is included in the params and when it isn't. I think logic for #59 can be added to the create method for invite tokens. It could be modified to set the boolean flag to the invites as @n1arash mentioned.

Here's the [link](https://github.com/rlanga/papercups/commit/2632fdffb3e5095b819be698f7f052dd7c2173dc) to the commit on my repo fork.

**Comment by reichert621** [comment]
@rlanga nice! your commit definitely looks like it solves the original issue, and i love the refactoring + test coverage 😁 

i think what @n1arash mentioned might be a good idea though — instead of deleting the invite after it's used, it would be helpful to keep it around so we can have a record of which invites have been used vs not. so rather than deleting, we could set up a method like
```elixir
ChatApi.UserInvitations.mark_user_invitation_expired(invite)
```

or something like that, and then throw a helpful error if someone tries to sign up with an expired invite. what do you think?

**Comment by rlanga** [comment]
Definitely sounds like a great idea! I could modify my code for this

**Comment by reichert621** [comment]
thanks @rlanga!

**Comment by reichert621** [comment]
btw @rlanga and @n1arash if you ever want to chat with us directly about this, feel free to join our slack or discord channels https://github.com/papercups-io/papercups#get-in-touch 😄

**Comment by reichert621** [comment]
handled in https://github.com/papercups-io/papercups/pull/81
