### ISSUE TITLE
Make it possible to delete a user and all of its data via API

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#600]
**Problem**
We want to be able to delete a user record and all of its associated data. Eventually we'll add a UI to enable this, but to start off we should be able to do it safely and programmatically.

(This will probably require some database migrations that improve how associated records are deleted... at the moment some resources are not automatically deleted when a parent resource is attempted to be deleted.)

This will also be necessary for GDPR compliance.

**Solution**
Set up an API for `DELETE /api/users/:id` (or similar) which deletes a user and all of its data.

**Testing**
Write automated tests and verify that all the user data is deleted, and no other user is affected.

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by fmterrorf** [comment]
Hi there, I'd like to work on this one :wave:

**Comment by fmterrorf** [comment]
> (This will probably require some database migrations that improve how associated records are deleted... at the moment some resources are not automatically deleted when a parent resource is attempted to be deleted.)

Just looking at the `users` table and yeah it looks like there's quite a bit of tables associated to it that don't have ON DELETE CASCADE

```
Referenced by:
TABLE "messages" CONSTRAINT "messages_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id)
TABLE "conversations" CONSTRAINT "conversations_assignee_id_fkey" FOREIGN KEY (assignee_id) REFERENCES users(id)
TABLE "user_profiles" CONSTRAINT "user_profiles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id)
TABLE "user_settings" CONSTRAINT "user_settings_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id)
TABLE "google_authorizations" CONSTRAINT "google_authorizations_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id)
TABLE "tags" CONSTRAINT "tags_creator_id_fkey" FOREIGN KEY (creator_id) REFERENCES users(id)
TABLE "conversation_tags" CONSTRAINT "conversation_tags_creator_id_fkey" FOREIGN KEY (creator_id) REFERENCES users(id)
TABLE "customer_tags" CONSTRAINT "customer_tags_creator_id_fkey" FOREIGN KEY (creator_id) REFERENCES users(id)
TABLE "personal_api_keys" CONSTRAINT "personal_api_keys_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
TABLE "notes" CONSTRAINT "notes_author_id_fkey" FOREIGN KEY (author_id) REFERENCES users(id)
TABLE "files" CONSTRAINT "files_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id)
```

**Comment by reichert621** [comment]
hey @fmterrorf! yep, these are the things we'll need to fix -- do you still wanna take it? happy to assign you in the meantime :+1:

**Comment by fmterrorf** [comment]
If a `user` gets deleted, and that user is assigned to a `conversation`, should the `conversation` be deleted? Right now i have the `conversation.assignee_id` set to to null if the assigned user is deleted. See [diff](https://github.com/papercups-io/papercups/compare/master...fmterrorf:delete_user_data#diff-f5e80f638e16c883312c8913a41cd826ff59d3408850c076676269e9713b93b2R20)

Same question with with `tags`. If we delete the user should the `tags` that the user created be deleted as well?

**Comment by reichert621** [comment]
It probably makes most sense to just set those values to null in both cases
like you said :)

**Comment by reichert621** [comment]
@fmterrorf any updates on this? i've set up similar PRs for `customers` (https://github.com/papercups-io/papercups/pull/611) and `accounts` (https://github.com/papercups-io/papercups/pull/612) if that's helpful for reference!

**Comment by fmterrorf** [comment]
Opened a PR here https://github.com/papercups-io/papercups/pull/613
