### ISSUE TITLE
Add `away_message` field to `widget_settings` table

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#621]
**Problem**
We're adding an `awayMessage` prop to our `ChatWidget` component, so we should add this field to our `widget_settings` table as well in case users want to set it in our dashboard (rather than directly in their code config)

**Solution**
Let's add an optional/nullable `away_message` string field to the `widget_settings` table.

**Additional context**
See https://github.com/papercups-io/papercups/pull/606/files for an example of adding a new field to this table.

**Testing**
Make sure all tests still pass (and maybe add the `away_message` field in some tests as well!)

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by reichert621** [comment]
great! i'll assign you to both for now :+1:

**Comment by a8t** [comment]
default limit is 255 characters. Do we want more or less?

**Comment by a8t** [comment]
Thanks for linking that relevant example. It was helpful!

**Comment by reichert621** [comment]
@a8t no default is necessary! and `text` seems fine :1:
