### ISSUE TITLE
Add `away_message` input in "Getting Started" page

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#622]
**Problem**
After #621 is finished, we should add the input to the "Getting Started" page so users can actually set this field.

**Solution**
Add an input below the `greeting` input on the "Getting Started" page (which is here: https://github.com/papercups-io/papercups/blob/master/assets/src/components/account/GettingStartedOverview.tsx#L306-L318)

The label should say "**Set an away message (will replace greeting message outside working hours):**"

(Happy to revisit this copy later)

<img width="991" alt="Screen Shot 2021-03-10 at 10 36 15 AM" src="https://user-images.githubusercontent.com/5264279/110654892-8a434100-818c-11eb-8eff-622d5af6de86.png">

**Testing**
Please include screenshots in your PR!

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by reichert621** [comment]
(@a8t can you leave a comment here so i can assign you 😄 )

**Comment by a8t** [comment]
commenting

**Comment by reichert621** [comment]
yeah i think if you're not a member of the org/repo it doesn't let me assign you unless you engage with the issue 🤷
