### ISSUE TITLE
Add boilerplate CRUD APIs for `canned_responses`

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#623]
**Problem**
Users have been asking for canned responses, and the schema is pretty straightforward, so let's start setting it up!

**Solution**
Set up the db migrations and boilerplate CRUD (create/read/update/delete) methods for a `canned_responses` table.

For an example of how to do this, you can probably use https://hexdocs.pm/phoenix/Mix.Tasks.Phx.Gen.Json.html (or see https://github.com/papercups-io/papercups/blob/master/docs/examples/add_conversations_api.md for some additional examples of this in action)

The schema should look something like this:
- `name`: required/non-nullable string field that represents the "code" for the canned response
  - Note that this should be unique per account (i.e. there should not be two `canned_response` records with the same `name` within a single `account`
- `content`: required/non-nullable text field that represents the full message of the response
- `account_id`: required/non-nullable foreign key for `accounts`

An example record might look like:
- `name: "pricing"`
- `content: "We have a free tier for X users! For additional pricing options, check out papercups.io/pricing"`
- `account_id: "__SOME_ACCOUNT_UUID__"`

**Additional context**
We can worry about the UI/UX for this later.

**Testing**
Please include automated tests! (A bunch of these should be autogenerated)

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by a8t** [comment]
What if the user wants variables (or whatever we want to call it) for interpolating into the message? Like `content: "Hi %user_name%, nice to meet you."` - any thoughts on this? Would probably be a next-iteration feature.

**Comment by reichert621** [comment]
seems like a good idea! but i don't think it needs to be part of this ticket :+1:

**Comment by jeepers3327** [comment]
Hi, is this still unassigned?.
I'd like to work on this one later after my work.

**Comment by a8t** [comment]
@jeepers3327 I'm starting work on it now, but I don't mind if we both do and your PR is the one that goes in.

**Comment by reichert621** [comment]
@jeepers3327 @a8t I'll assign you both for now :+1: happy to review both PRs and provide feedback 🤓
