### ISSUE TITLE
Cryptographic Authentication Without the Email Based Registration Workflow

### ISSUE THREAD

**Issue by fredfortier** [papercups-io/papercups#627]
I suspect that what I'm about to ask is already possible but I couldn't easily find documentation.

I want to use self-signed customer data instead of email for registration. For example, this may involve implementing implementing an alternative `api/register` endpoint that takes `{customer: "...", signature: "0x.."}`. We recover a public key from the signed customer data then authenticate it against an external registry. If successful, we map this customer data to a generated `accountId` in the database (if this is roughly equivalent to what email registration does). It would be even better if we could use the public key as the `accountId` instead of generating one. This way, users would just sign another message (say a nonce) to login without any additional lookup.

I'm not asking how to implement the cryptography. I'm asking where to implement such custom registration while minimizing changes to the framework.

I hope the question make sense. Any pointer would be appreciated. I can figure this out with little info. I just need to validate my conceptual understanding and ideally know the general area where to implement this.

For further context, we're planning to self-host using the docker-compose definition you guys provided. We're very familiar with Postgres. The chat box will be instantiated as a React component of our existing frontend.

**Comment by reichert621** [comment]
hey @fredfortier! not sure I understand 😅 maybe we could hop on a quick call sometime to learn more about your use case?

let me know if that would work for you!

**Comment by cheeseblubber** [comment]
Don't really understand this ticket. Closing for now. Feel free to reopen if this is still something you are interested in.
