### ISSUE TITLE
Gmail integration v1

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#637]
**Problem**
Users want to sync their `support@` email accounts with Papercups.

Why?
- the whole team can see emails within the Papercups dashboard
- people can tag or comment on messages without their customers seeing any of this
- anyone from the team can reply to emails, and it will show up as the `support@` email from the customer's perspective
- people can reply to emails directly from Slack (🤯)

**Solution**
TODO: spec this out some more!

Some thoughts:
- we'll probably start with a recurring job that runs every 5-10 mins checking for new emails
  - TODO: outline how we determine what constitutes a "new email"
- we'll probably have to figure out a decent way to remove/filter out the email history in longer threads (so every new message doesn't contain the history of all the old messages)
- this may involve some annoying parsing, depending on what the Gmail API gives us
- we also may only want to sync messages by a certain label, but we can probably just start off with all new messages in the inbox
  - I guess for testing it would be good to set up a label to indicate which messages to sync?
- how do we handle replying to a thread? I think it might just be adding some ID to a header, but not sure off the top of my head
- eventually we'll need to figure out how to handle parsing markdown (since we support markdown syntax in the dashboard and Slack)
- we'll need to figure out how to map Gmail thread IDs and message IDs to Papercups conversations/messages
  - probably will need to set up something similar to `slack_conversation_threads`, i.e. a `gmail_conversation_threads` table

**Describe alternatives you've considered**
Need to investigate if Mailgun makes it possible to do something like this more easily 🤔 hard to imagine that would be the case though?

**Additional context**
TBD

**Testing**
This will probably require a fair bit of manual testing.

(TODO: list out some QA test case scenarios)

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by a8t** [comment]
Interesting. Gmail seems to have a [Push Notification system](https://developers.google.com/gmail/api/guides/push) that could be used instead of polling.

**Comment by reichert621** [comment]
thanks @a8t! super helpful :) 

also going to paste in some sample response payloads from the Gmail API here...

### `/gmail/v1/users/me/messages`

```elixir
%{
  "messages" => [
    %{"id" => "1783bb273d3ca8ed", "threadId" => "1783bb273d3ca8ed"},
    %{"id" => "1783b6533a33f0f1", "threadId" => "1783b6533a33f0f1"},
    %{"id" => "1783b5705b99bde2", "threadId" => "1783b5705b99bde2"},
    %{"id" => "1783b56c46b4eef6", "threadId" => "1783b56c46b4eef6"},
    %{"id" => "1783b45f10c856ad", "threadId" => "1782884988975d0e"},
    # etc.  
  ]
}
```

### `/gmail/v1/users/me/messages/#{message_id}`

```elixir
%{
  "historyId" => "367404",
  "id" => "1783bdc5ee6857a2",
  "internalDate" => "1615912000000",
  "labelIds" => ["SENT"],
  "payload" => %{
    "body" => %{"size" => 0},
    "filename" => "",
    "headers" => [
      %{"name" => "MIME-Version", "value" => "1.0"},
      %{"name" => "Date", "value" => "Tue, 16 Mar 2021 12:26:40 -0400"},
      %{
        "name" => "References",
        "value" => "<CADrf=fmqwxG84EvjcE8rm-asKaQM-hZSm=kYizrvOX1kavyGtg@mail.gmail.com>"
      },
      %{
        "name" => "In-Reply-To",
        "value" => "<CADrf=fmqwxG84EvjcE8rm-asKaQM-hZSm=kYizrvOX1kavyGtg@mail.gmail.com>"
      },
      %{
        "name" => "Message-ID",
        "value" => "<CAO-SVC=6y8jKsTpVy=783mroF7v+qfX+DvWwL9SA9xL7iAa4Tw@mail.gmail.com>"
      },
      %{"name" => "Subject", "value" => "Re: Test subject for Gmail API"},
      %{"name" => "From", "value" => "Alex Reichert <alex@papercups.io>"},
      %{"name" => "To", "value" => "Alex Reichert <reichertjalex@gmail.com>"},
      %{
        "name" => "Content-Type",
        "value" => "multipart/alternative; boundary=\"000000000000d4bab205bda9d4dd\""
      }
    ],
    "mimeType" => "multipart/alternative",
    "partId" => "",
    "parts" => [
      %{
        "body" => %{
          "data" => "TmljZSEgVGhpcyBpcyBhIHRlc3QgcmVwbHkuDQoNCkxldCdzIHNlZSBob3cgaXQgZ29lcy4NCuGQpw0KDQpPbiBUdWUsIE1hciAxNiwgMjAyMSBhdCAxMjoyNiBQTSBBbGV4IFJlaWNoZXJ0IDxyZWljaGVydGphbGV4QGdtYWlsLmNvbT4NCndyb3RlOg0KDQo-IEhleSBBbGV4IQ0KPg0KPiBUaGlzIGlzIGEgdGVzdCBtZXNzYWdlIGZvciB0aGUgR21haWwgQVBJLg0KPg0K",
          "size" => 210
        },
        "filename" => "",
        "headers" => [
          %{
            "name" => "Content-Type",
            "value" => "text/plain; charset=\"UTF-8\""
          },
          %{
            "name" => "Content-Transfer-Encoding",
            "value" => "quoted-printable"
          }
        ],
        "mimeType" => "text/plain",
        "partId" => "0"
      },
      %{
        "body" => %{
          "data" => "PGRpdiBkaXI9Imx0ciI-TmljZSEgVGhpcyBpcyBhIHRlc3QgcmVwbHkuPGRpdj48YnI-PC9kaXY-PGRpdj5MZXQmIzM5O3Mgc2VlIGhvdyBpdCBnb2VzLjwvZGl2PjwvZGl2PjxkaXYgaHNwYWNlPSJzdHJlYWstcHQtbWFyayIgc3R5bGU9Im1heC1oZWlnaHQ6MXB4Ij48aW1nIGFsdD0iIiBzdHlsZT0id2lkdGg6MHB4O21heC1oZWlnaHQ6MHB4O292ZXJmbG93OmhpZGRlbiIgc3JjPSJodHRwczovL21haWxmb29nYWUuYXBwc3BvdC5jb20vdD9zZW5kZXI9YVlXeGxlRUJ3WVhCbGNtTjFjSE11YVc4JTNEJmFtcDt0eXBlPXplcm9jb250ZW50JmFtcDtndWlkPTEwN2JkMGRkLTdmODYtNGIzZS04MDM4LTdhZDMyNWUwMmYxZCI-PGZvbnQgY29sb3I9IiNmZmZmZmYiIHNpemU9IjEiPuGQpzwvZm9udD48L2Rpdj48YnI-PGRpdiBjbGFzcz0iZ21haWxfcXVvdGUiPjxkaXYgZGlyPSJsdHIiIGNsYXNzPSJnbWFpbF9hdHRyIj5PbiBUdWUsIE1hciAxNiwgMjAyMSBhdCAxMjoyNiBQTSBBbGV4IFJlaWNoZXJ0ICZsdDs8YSBocmVmPSJtYWlsdG86cmVpY2hlcnRqYWxleEBnbWFpbC5jb20iPnJlaWNoZXJ0amFsZXhAZ21haWwuY29tPC9hPiZndDsgd3JvdGU6PGJyPjwvZGl2PjxibG9ja3F1b3RlIGNsYXNzPSJnbWFpbF9xdW90ZSIgc3R5bGU9Im1hcmdpbjowcHggMHB4IDBweCAwLjhleDtib3JkZXItbGVmdDoxcHggc29saWQgcmdiKDIwNCwyMDQsMjA0KTtwYWRkaW5nLWxlZnQ6MWV4Ij48ZGl2IGRpcj0ibHRyIj5IZXkgQWxleCE8ZGl2Pjxicj48L2Rpdj48ZGl2PlRoaXMgaXMgYSB0ZXN0IG1lc3NhZ2UgZm9yIHRoZSBHbWFpbCBBUEkuPC9kaXY-PC9kaXY-DQo8L2Jsb2NrcXVvdGU-PC9kaXY-DQo=",
          "size" => 845
        },
        "filename" => "",
        "headers" => [
          %{"name" => "Content-Type", "value" => "text/html; charset=\"UTF-8\""},
          %{
            "name" => "Content-Transfer-Encoding",
            "value" => "quoted-printable"
          }
        ],
        "mimeType" => "text/html",
        "partId" => "1"
      }
    ]
  },
  "sizeEstimate" => 1927,
  "snippet" => "Nice! This is a test reply. Let&#39;s see how it goes. ᐧ On Tue, Mar 16, 2021 at 12:26 PM Alex Reichert &lt;reichertjalex@gmail.com&gt; wrote: Hey Alex! This is a test message for the Gmail API.",
  "threadId" => "1783bdc057a1f4c2"
}
```

### `/gmail/v1/users/me/threads`

```elixir
%{
  "nextPageToken" => "00264963116145399493",
  "resultSizeEstimate" => 250,
  "threads" => [
    %{
      "historyId" => "367407",
      "id" => "1783bdf49b1f474d",
      "snippet" => "[Webinar] Learn about global data protection and deliverability | View online version Hey there, A lot has changed since GDPR came into effect in May 2018. Have you been keeping up with all the updates"
    },
    %{
      "historyId" => "367404",
      "id" => "1783bdc057a1f4c2",
      "snippet" => "Nice! This is a test reply. Let&#39;s see how it goes. ᐧ On Tue, Mar 16, 2021 at 12:26 PM Alex Reichert &lt;reichertjalex@gmail.com&gt; wrote: Hey Alex! This is a test message for the Gmail API."
    },
    %{
      "historyId" => "367255",
      "id" => "1783bb273d3ca8ed",
      "snippet" => "Cruise to buy rival driverless car startup; ElevateBio raises $525M in VC; Sprinklr confidentially files for an IPO; Gatsby gets green light for $10M Read online | Don&#39;t want to receive these"
    },
```

### `/gmail/v1/users/me/threads/#{thread_id}?format=full`

```elixir
%{
  "historyId" => "367404",
  "id" => "1783bdc057a1f4c2",
  "messages" => [
    %{
      "historyId" => "367378",
      "id" => "1783bdc057a1f4c2",
      "internalDate" => "1615911941000",
      "labelIds" => ["IMPORTANT", "CATEGORY_PERSONAL", "INBOX"],
      "payload" => %{
        "body" => %{"size" => 0},
        "filename" => "",
        "headers" => [
          %{"name" => "Delivered-To", "value" => "alex@papercups.io"},
          %{
            "name" => "Received",
            "value" => "by 2002:a2e:9694:0:0:0:0:0 with SMTP id q20csp4647726lji;        Tue, 16 Mar 2021 09:26:18 -0700 (PDT)"
          },
          %{
            "name" => "X-Received",
            "value" => "by 2002:a92:540d:: with SMTP id i13mr4411823ilb.8.1615911978285;        Tue, 16 Mar 2021 09:26:18 -0700 (PDT)"
          },
          %{
            "name" => "ARC-Seal",
            "value" => "i=1; a=rsa-sha256; t=1615911978; cv=none;        d=google.com; s=arc-20160816;        b=Qr3NovZVSSOKvZFihmnEZ93EdGgNJAl+S5Rbb2KvOQPKCp5D55+RDZPP59vrIg2GxE         aWoPW+lmYxKvldQK3cZqjeJYe/2BY6WNLLGFgr1LMx8E+4V888sVZJ2e0gJvnM4pOK52         5NJBqpMS55UbB/aJAIRYs0cQEca7oTFg8Cy9GzHkOFqHsR7rPLVmzh9co0YdEOFJcF8l         wezz5in3yEtXgOCC2C5xfHIfDfkAj127+bxeipf5H9murFrEn3Ee87jS1ET4JD5XtzAk         7iWPmBoXOqcFasT2s+77wu3TF/cPMKSh0NXK3Ibqtt8osWBheZDtbVxQQHa1UnXlEUoQ         yxfA=="
          },
          %{
            "name" => "ARC-Message-Signature",
            "value" => "i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;        h=to:subject:message-id:date:from:mime-version:dkim-signature;        bh=Utx/9TlOmY4X3JEroB0TzviHX6lVHUqAFBQ7/R2R8gY=;        b=NW4WLSuqYPUXePK27OEjYN9/+oo7HhChx2ksGdIugMjYBjK1HWMLa+pObBoltCk54n         +ZkAvEpw7oJkRyG7sd33ok4IyoANQz5lw30+mWG4KayI3W0V1tZ8IZiQd8+Pxa36oxvs         kw2W9Jn4Ck5slbgWEtpfTEU81Zp3cIAon/sKk39tcWR1gceoB7dg3DRXTUYmP0F2nw1Z         /Rx4SXjVBQ+8F5wHnpH7LTm1XzfjcHDPCeulk2+ao7sdlmighY2VaQH95lV+Uu0ASc5Q         EbyufEWLFUoGOtwZamMudcIL525qm49pk7DVzcNsnJ+/i2dF9i4YdIoU3NYvhDeDoPPU         yyhA=="
          },
          %{
            "name" => "ARC-Authentication-Results",
            "value" => "i=1; mx.google.com;       dkim=pass header.i=@gmail.com header.s=20161025 header.b=gpygfwCF;       spf=pass (google.com: domain of reichertjalex@gmail.com designates 209.85.220.41 as permitted sender) smtp.mailfrom=reichertjalex@gmail.com;       dmarc=pass (p=NONE sp=QUARANTINE dis=NONE) header.from=gmail.com"
          },
          %{"name" => "Return-Path", "value" => "<reichertjalex@gmail.com>"},
          %{
            "name" => "Received",
            "value" => "from mail-sor-f41.google.com (mail-sor-f41.google.com. [209.85.220.41])        by mx.google.com with SMTPS id p79sor8092478iod.73.2021.03.16.09.26.18        for <alex@papercups.io>        (Google Transport Security);        Tue, 16 Mar 2021 09:26:18 -0700 (PDT)"
          },
          %{
            "name" => "Received-SPF",
            "value" => "pass (google.com: domain of reichertjalex@gmail.com designates 209.85.220.41 as permitted sender) client-ip=209.85.220.41;"
          },
          %{
            "name" => "Authentication-Results",
            "value" => "mx.google.com;       dkim=pass header.i=@gmail.com header.s=20161025 header.b=gpygfwCF;       spf=pass (google.com: domain of reichertjalex@gmail.com designates 209.85.220.41 as permitted sender) smtp.mailfrom=reichertjalex@gmail.com;       dmarc=pass (p=NONE sp=QUARANTINE dis=NONE) header.from=gmail.com"
          },
          %{
            "name" => "DKIM-Signature",
            "value" => "v=1; a=rsa-sha256; c=relaxed/relaxed;        d=gmail.com; s=20161025;        h=mime-version:from:date:message-id:subject:to;        bh=Utx/9TlOmY4X3JEroB0TzviHX6lVHUqAFBQ7/R2R8gY=;        b=gpygfwCFJoVj4sS985jmGwMFJ+DafVa4QFu13DuBWWajhdV9Dp2tZ+H5Nmb7mljtuf         gjCANID4oAOVj9LxrWTTN1ieE9wZHRyCPgqll+68BAXyJ2TMudur90pz0e+hIaxuKsf1         QITbrm04eFnyZ50WTfGKeHtK9nbgxV9MOJUiMHO5nBNBdOPo3ESLwx1SZo/heJgD0PBf         z8eye+Sm8PYadgwJ229HPjjs5suqV0LBZPl3fpY4uaPioEtudl2gbWYd3NyWPAIjirny         +c9/xUzQJ1EWiHN7+G/pQprTSPJjA60xirJuAOhNC2dcvtozyE9caCUnYRIhSUupCpW8         naLA=="
          },
          %{
            "name" => "X-Google-DKIM-Signature",
            "value" => "v=1; a=rsa-sha256; c=relaxed/relaxed;        d=1e100.net; s=20161025;        h=x-gm-message-state:mime-version:from:date:message-id:subject:to;        bh=Utx/9TlOmY4X3JEroB0TzviHX6lVHUqAFBQ7/R2R8gY=;        b=Cm/H4TDPDfjZcJtbJZXHQcM8+tQWr+GJPKK9CEO/teZ+QKqs0I56/tUAGWj0MG4gEy         YrpHY/VYR0e/1+9IMjcenNov3z9dqYwuX6DckT2nfoANgrtQWwawNQJETMLmb8ks7vkY         3K66/0jSATmKnDJ60Zk3ilSeiqbQIVQFG8NTMvLjOCLyb1xKW2F9ptn9IlkIKWFN1j3C         ol9WFvyZRv5mRkhhb2XNqumvEOJpvKhohLNnV7N/aw/vK13EFafIQyRdRyVgy12R3+tW         j1z1s3IJiRRPjUBQNd+l/cPgm9UOSpvtAFToZE7RV+dOt1F5yZo8G/+g1s+99L7cCL7e         cw2Q=="
          },
          %{
            "name" => "X-Gm-Message-State",
            "value" => "AOAM530BdJj/E5PqZOZ8x0/TEiySEY2EnvUQIQdJq6gynwWFiQ0se/IN iEhSsVTu+Q5RiTd7+/EE6x4gJQX1DVkpnK1yQOYrTGsgqRM="
          },
          %{
            "name" => "X-Google-Smtp-Source",
            "value" => "ABdhPJz1jztn29kswW7Uxfe+7KS0Uapms9nz0R0QAKLlGnyv42TYnsXi9vMQfNCRrGzTNPubpXBI5vV4qbum7v/6Cb4="
          },
          %{
            "name" => "X-Received",
            "value" => "by 2002:a6b:fd07:: with SMTP id c7mr3985617ioi.198.1615911977550; Tue, 16 Mar 2021 09:26:17 -0700 (PDT)"
          },
          %{"name" => "MIME-Version", "value" => "1.0"},
          %{
            "name" => "From",
            "value" => "Alex Reichert <reichertjalex@gmail.com>"
          },
          %{"name" => "Date", "value" => "Tue, 16 Mar 2021 12:25:41 -0400"},
          %{
            "name" => "Message-ID",
            "value" => "<CADrf=fmqwxG84EvjcE8rm-asKaQM-hZSm=kYizrvOX1kavyGtg@mail.gmail.com>"
          },
          %{"name" => "Subject", "value" => "Test subject for Gmail API"},
          %{"name" => "To", "value" => "Alex Reichert <alex@papercups.io>"},
          %{
            "name" => "Content-Type",
            "value" => "multipart/alternative; boundary=\"0000000000006906a505bda9d373\""
          }
        ],
        "mimeType" => "multipart/alternative",
        "partId" => "",
        "parts" => [
          %{
            "body" => %{
              "data" => "SGV5IEFsZXghDQoNClRoaXMgaXMgYSB0ZXN0IG1lc3NhZ2UgZm9yIHRoZSBHbWFpbCBBUEkuDQo=",
              "size" => 56
            },
            "filename" => "",
            "headers" => [
              %{
                "name" => "Content-Type",
                "value" => "text/plain; charset=\"UTF-8\""
              }
            ],
            "mimeType" => "text/plain",
            "partId" => "0"
          },
          %{
            "body" => %{
              "data" => "PGRpdiBkaXI9Imx0ciI-SGV5IEFsZXghPGRpdj48YnI-PC9kaXY-PGRpdj5UaGlzIGlzIGEgdGVzdCBtZXNzYWdlIGZvciB0aGUgR21haWwgQVBJLjwvZGl2PjwvZGl2Pg0K",
              "size" => 99
            },
            "filename" => "",
            "headers" => [
              %{
                "name" => "Content-Type",
                "value" => "text/html; charset=\"UTF-8\""
              }
            ],
            "mimeType" => "text/html",
            "partId" => "1"
          }
        ]
      },
      "sizeEstimate" => 4863,
      "snippet" => "Hey Alex! This is a test message for the Gmail API.",
      "threadId" => "1783bdc057a1f4c2"
    },
    %{
      "historyId" => "367404",
      "id" => "1783bdc5ee6857a2",
      "internalDate" => "1615912000000",
      "labelIds" => ["SENT"],
      "payload" => %{
        "body" => %{"size" => 0},
        "filename" => "",
        "headers" => [
          %{"name" => "MIME-Version", "value" => "1.0"},
          %{"name" => "Date", "value" => "Tue, 16 Mar 2021 12:26:40 -0400"},
          %{
            "name" => "References",
            "value" => "<CADrf=fmqwxG84EvjcE8rm-asKaQM-hZSm=kYizrvOX1kavyGtg@mail.gmail.com>"
          },
          %{
            "name" => "In-Reply-To",
            "value" => "<CADrf=fmqwxG84EvjcE8rm-asKaQM-hZSm=kYizrvOX1kavyGtg@mail.gmail.com>"
          },
          %{
            "name" => "Message-ID",
            "value" => "<CAO-SVC=6y8jKsTpVy=783mroF7v+qfX+DvWwL9SA9xL7iAa4Tw@mail.gmail.com>"
          },
          %{"name" => "Subject", "value" => "Re: Test subject for Gmail API"},
          %{"name" => "From", "value" => "Alex Reichert <alex@papercups.io>"},
          %{
            "name" => "To",
            "value" => "Alex Reichert <reichertjalex@gmail.com>"
          },
          %{
            "name" => "Content-Type",
            "value" => "multipart/alternative; boundary=\"000000000000d4bab205bda9d4dd\""
          }
        ],
        "mimeType" => "multipart/alternative",
        "partId" => "",
        "parts" => [
          %{
            "body" => %{
              "data" => "TmljZSEgVGhpcyBpcyBhIHRlc3QgcmVwbHkuDQoNCkxldCdzIHNlZSBob3cgaXQgZ29lcy4NCuGQpw0KDQpPbiBUdWUsIE1hciAxNiwgMjAyMSBhdCAxMjoyNiBQTSBBbGV4IFJlaWNoZXJ0IDxyZWljaGVydGphbGV4QGdtYWlsLmNvbT4NCndyb3RlOg0KDQo-IEhleSBBbGV4IQ0KPg0KPiBUaGlzIGlzIGEgdGVzdCBtZXNzYWdlIGZvciB0aGUgR21haWwgQVBJLg0KPg0K",
              "size" => 210
            },
            "filename" => "",
            "headers" => [
              %{
                "name" => "Content-Type",
                "value" => "text/plain; charset=\"UTF-8\""
              },
              %{
                "name" => "Content-Transfer-Encoding",
                "value" => "quoted-printable"
              }
            ],
            "mimeType" => "text/plain",
            "partId" => "0"
          },
          %{
            "body" => %{
              "data" => "PGRpdiBkaXI9Imx0ciI-TmljZSEgVGhpcyBpcyBhIHRlc3QgcmVwbHkuPGRpdj48YnI-PC9kaXY-PGRpdj5MZXQmIzM5O3Mgc2VlIGhvdyBpdCBnb2VzLjwvZGl2PjwvZGl2PjxkaXYgaHNwYWNlPSJzdHJlYWstcHQtbWFyayIgc3R5bGU9Im1heC1oZWlnaHQ6MXB4Ij48aW1nIGFsdD0iIiBzdHlsZT0id2lkdGg6MHB4O21heC1oZWlnaHQ6MHB4O292ZXJmbG93OmhpZGRlbiIgc3JjPSJodHRwczovL21haWxmb29nYWUuYXBwc3BvdC5jb20vdD9zZW5kZXI9YVlXeGxlRUJ3WVhCbGNtTjFjSE11YVc4JTNEJmFtcDt0eXBlPXplcm9jb250ZW50JmFtcDtndWlkPTEwN2JkMGRkLTdmODYtNGIzZS04MDM4LTdhZDMyNWUwMmYxZCI-PGZvbnQgY29sb3I9IiNmZmZmZmYiIHNpemU9IjEiPuGQpzwvZm9udD48L2Rpdj48YnI-PGRpdiBjbGFzcz0iZ21haWxfcXVvdGUiPjxkaXYgZGlyPSJsdHIiIGNsYXNzPSJnbWFpbF9hdHRyIj5PbiBUdWUsIE1hciAxNiwgMjAyMSBhdCAxMjoyNiBQTSBBbGV4IFJlaWNoZXJ0ICZsdDs8YSBocmVmPSJtYWlsdG86cmVpY2hlcnRqYWxleEBnbWFpbC5jb20iPnJlaWNoZXJ0amFsZXhAZ21haWwuY29tPC9hPiZndDsgd3JvdGU6PGJyPjwvZGl2PjxibG9ja3F1b3RlIGNsYXNzPSJnbWFpbF9xdW90ZSIgc3R5bGU9Im1hcmdpbjowcHggMHB4IDBweCAwLjhleDtib3JkZXItbGVmdDoxcHggc29saWQgcmdiKDIwNCwyMDQsMjA0KTtwYWRkaW5nLWxlZnQ6MWV4Ij48ZGl2IGRpcj0ibHRyIj5IZXkgQWxleCE8ZGl2Pjxicj48L2Rpdj48ZGl2PlRoaXMgaXMgYSB0ZXN0IG1lc3NhZ2UgZm9yIHRoZSBHbWFpbCBBUEkuPC9kaXY-PC9kaXY-DQo8L2Jsb2NrcXVvdGU-PC9kaXY-DQo=",
              "size" => 845
            },
            "filename" => "",
            "headers" => [
              %{
                "name" => "Content-Type",
                "value" => "text/html; charset=\"UTF-8\""
              },
              %{
                "name" => "Content-Transfer-Encoding",
                "value" => "quoted-printable"
              }
            ],
            "mimeType" => "text/html",
            "partId" => "1"
          }
        ]
      },
      "sizeEstimate" => 1927,
      "snippet" => "Nice! This is a test reply. Let&#39;s see how it goes. ᐧ On Tue, Mar 16, 2021 at 12:26 PM Alex Reichert &lt;reichertjalex@gmail.com&gt; wrote: Hey Alex! This is a test message for the Gmail API.",
      "threadId" => "1783bdc057a1f4c2"
    }
  ]
}
```

### Decoded message body

Encoded:
`
"PGRpdiBkaXI9Imx0ciI-TmljZSEgVGhpcyBpcyBhIHRlc3QgcmVwbHkuPGRpdj48YnI-PC9kaXY-PGRpdj5MZXQmIzM5O3Mgc2VlIGhvdyBpdCBnb2VzLjwvZGl2PjwvZGl2PjxkaXYgaHNwYWNlPSJzdHJlYWstcHQtbWFyayIgc3R5bGU9Im1heC1oZWlnaHQ6MXB4Ij48aW1nIGFsdD0iIiBzdHlsZT0id2lkdGg6MHB4O21heC1oZWlnaHQ6MHB4O292ZXJmbG93OmhpZGRlbiIgc3JjPSJodHRwczovL21haWxmb29nYWUuYXBwc3BvdC5jb20vdD9zZW5kZXI9YVlXeGxlRUJ3WVhCbGNtTjFjSE11YVc4JTNEJmFtcDt0eXBlPXplcm9jb250ZW50JmFtcDtndWlkPTEwN2JkMGRkLTdmODYtNGIzZS04MDM4LTdhZDMyNWUwMmYxZCI-PGZvbnQgY29sb3I9IiNmZmZmZmYiIHNpemU9IjEiPuGQpzwvZm9udD48L2Rpdj48YnI-PGRpdiBjbGFzcz0iZ21haWxfcXVvdGUiPjxkaXYgZGlyPSJsdHIiIGNsYXNzPSJnbWFpbF9hdHRyIj5PbiBUdWUsIE1hciAxNiwgMjAyMSBhdCAxMjoyNiBQTSBBbGV4IFJlaWNoZXJ0ICZsdDs8YSBocmVmPSJtYWlsdG86cmVpY2hlcnRqYWxleEBnbWFpbC5jb20iPnJlaWNoZXJ0amFsZXhAZ21haWwuY29tPC9hPiZndDsgd3JvdGU6PGJyPjwvZGl2PjxibG9ja3F1b3RlIGNsYXNzPSJnbWFpbF9xdW90ZSIgc3R5bGU9Im1hcmdpbjowcHggMHB4IDBweCAwLjhleDtib3JkZXItbGVmdDoxcHggc29saWQgcmdiKDIwNCwyMDQsMjA0KTtwYWRkaW5nLWxlZnQ6MWV4Ij48ZGl2IGRpcj0ibHRyIj5IZXkgQWxleCE8ZGl2Pjxicj48L2Rpdj48ZGl2PlRoaXMgaXMgYSB0ZXN0IG1lc3NhZ2UgZm9yIHRoZSBHbWFpbCBBUEkuPC9kaXY-PC9kaXY-DQo8L2Jsb2NrcXVvdGU-PC9kaXY-DQo="
`

Decoded:
`
"<div dir=\"ltr\">Nice! This is a test reply.<div><br></div><div>Let&#39;s see how it goes.</div></div><div hspace=\"streak-pt-mark\" style=\"max-height:1px\"><img alt=\"\" style=\"width:0px;max-height:0px;overflow:hidden\" src=\"https://mailfoogae.appspot.com/t?sender=aYWxleEBwYXBlcmN1cHMuaW8%3D&amp;type=zerocontent&amp;guid=107bd0dd-7f86-4b3e-8038-7ad325e02f1d\"><font color=\"#ffffff\" size=\"1\">ᐧ</font></div><br><div class=\"gmail_quote\"><div dir=\"ltr\" class=\"gmail_attr\">On Tue, Mar 16, 2021 at 12:26 PM Alex Reichert &lt;<a href=\"mailto:reichertjalex@gmail.com\">reichertjalex@gmail.com</a>&gt; wrote:<br></div><blockquote class=\"gmail_quote\" style=\"margin:0px 0px 0px 0.8ex;border-left:1px solid rgb(204,204,204);padding-left:1ex\"><div dir=\"ltr\">Hey Alex!<div><br></div><div>This is a test message for the Gmail API.</div></div>\r\n</blockquote></div>\r\n"
`

**Comment by wmnnd** [comment]
Here are some gerneral considerations for evaluating whether using IMAP would be a viable alternative to the Gmail API:

## What is IMAP
IMAP is *the* standard for retrieving emails from a server and defined in [RFC 3501](https://tools.ietf.org/html/rfc3501).
IMAP is supported by all email providers¹. 

## IMAP and Gmail
- Special Integration with Gmail is still possible; IMAP credentials for Gmail accounts can be obtained via OAuth2 (see https://developers.google.com/gmail/imap/xoauth2-protocol).

## Determining "new emails"
IMAP has several ways we could use to determine "new" emails
  - `\Recent`: IMAP servers automatically tag all emails that no client has been notified about yet with this flag. This would be reasonable to use if linked inboxes are never accessed by other clients (unlikely)
  - `\Seen` this flag is available on all emails that have not been marked as read. Again only useful if the inbox is not used in other clients (so also not useful).
  - `UIDNEXT` is a status attribute of mailboxes and represents the next UID (unique identifier) that will be used by the server when the next email arrives. Storing this attribute and using it when fetching emails should reliably yield only emails since the last fetch².
  GMail’s `historyId` is probably based on or closely tied to IMAP UIDs.
  **This is probably the way to go.**


## Push/pull
IMAP allows a client to remain connected and immediately receive new messages. This would make an implementation much more complex, however. So I don’t think this would make sense for an MVP.

## Threading
There are at least three ways in which threading could be implemented at the IMAP client level:
- IMAP has an extension for threading (`THREAD`, [RFC 5256](https://www.ietf.org/rfc/rfc5256.txt)).  It is supported by the most common FLOSS IMAP servers Dovecot but not by Gmail or MS Exchange (see [matrix at imapwiki.org](https://www.imapwiki.org/Specs))
- Gmail has a proprietary extension for threading, `X-GM-THRID` (see [developer.google.com](https://developers.google.com/gmail/imap/imap-extensions#access_to_the_gmail_thread_id_x-gm-thrid)). This might be useful for an MVP supporting just GMail.
- People on StackOverflow have suggested this relatively straighforward algorithm which should provide good results for threading: https://www.jwz.org/doc/threading.html

## Available Elixir/Erlang libraries
There are several Elixir and Erlang IMAP client libraries. None of them show any recent activity. However, since the scope of IMAP is limited, it is not to be expected that a reasonably well-functioning implementation would change frequently:
- https://github.com/altenwald/eimap - Erlang library, not on Hex
- https://github.com/around25/eximap - Elixir library, only library on Hex. Last update 2 years ago. No apparent glaring problems. Decent number of users according to Hex. There’s actually a comprehensive blog post praising the library: https://andreiclinciu.net/imap-elixir-adventures-the-complete-guide-to-handling-imap-e-mails-from-within-elixir
- https://github.com/Around25/eximap - Elixir library, not on Hex. Last update 2 years ago
- https://github.com/voughtdq/imap - Elixir library, not on Hex. Last update 3 years ago. No users (?).
- https://github.com/Mainframe-Archive/switchboard - Erlang application for more than just IMAP handling. Abandoned 4 years ago.


Alternatively, if we end up focusing on polling emails without long-lasting open connection, simply using Hackney et al might be a viable option.

## Conclusion
Using IMAP seems like a viable alternative to Gmail’s API. We would need to evaluate whether `eximap` can work well within Papercups or whether we should build our own small wrapper for the IMAP protocol.

Building an IMAP integration will be a bit more work than a Gmail API integration but I don’t expect it to be *significantly* more difficult.

---

¹ Notable exceptions are hey.com and tutanota.com but they focus on particular aspects of email and are not suited for customer-support emails anyways.

² There is another attribute, `UIDVALIDITY` which we should store alongside `UIDNEXT`. If `UIDVALIDITY` has changed, then `the mailbox [has been] deleted and a new mailbox with the same name [has been] created at a later date` - but this is probably an edge case.

**Comment by reichert621** [comment]
rough next steps:
- figure out how to authenticate an email/gmail account
- figure out how to retrieve messages from the account
- figure out how to listen for new messages (probably just polling for now?)
- figure out how to send messages as the account

(we can worry about how we map these to resources in papercups later)

**Comment by reichert621** [comment]
@wmnnd here are some quick thoughts, hopefully this is a bit more concrete! (I'll try to keep adding more details, but feel free to ask any questions or clarifications)

To start off we're just going to poll for new messages (every 5-10 mins?) rather than rely on a "push" notification from a webhook or something like that. This feature will only be used by <10 beta users to start, so let's not worry too much about scalability issues quite yet.

The main operations we'll need to accomplish this:
- Retrieve a list of threads
- Retrieve a single thread with its list of messages
- Retrieve a single message
- Retrieve a history of events (e.g. "message added", "message removed", etc)
- Send a message 
- Send a message as a reply to an existing thread

See pseudocode below for a bit more detail...

### `Client.list_threads(authorization)`

This method handles retrieving the list of email threads in an inbox. Each thread should have an ID, which can be passed in below to retrieve all the details.

This method should ideally retrieve the list sorted by most recent -> oldest threads.

### `Client.get_thread(authorization, thread_id)`

This method should retrieve the entire thread, along with its messages. The thread details should include a list of messages.

Each message should include:
- a unique ID
- its subject line
- its sender/recipient/cc/bcc info
- the time it was created
- the text body of the message
- the html body of the message
- its labels (optional)
- (anything else that might be important)

### `Client.get_message(authorization, message_id)`

This method will retrieve a single message by ID. The shape of the message will be the same as above.

### `Client.get_events_since(authorization, history_id)`

The `history_id` here simply represents a unique ID of an event. This method should return a list of "events" since that ID.

Ideally this will give us a clear "diff" (i.e. messages added/removed) since the event ID passed in.

This method should be run whenever we do a "sync" with an email account (since we'll start off by just polling for updates). We'll check for "messages added" to determine which conversations need to be created/updated in Papercups.

### `Client.send_message(authorization, payload)`

This method should handle sending messages as the authenticated email account. If the appropriate fields are passed into the message payload (e.g. "In-Reply-To" header, etc), then the message should be sent as a reply to its existing thread.
