### ISSUE TITLE
[Twilio Integration v1] Write documentation for getting started

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#677]
**Problem**
Users who want to connect to Twilio will need docs to guide them through the process, since Twilio can be a bit difficult to navigate if you've never used it before.

**Solution**
Write docs and add them to https://docs.papercups.io/

**Additional context**
https://github.com/papercups-io/papercups/issues/678

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by a8t** [comment]
- make an account
- add account sid and auth token to papercups
- set up webhook

is there anything else?

**Comment by reichert621** [comment]
@a8t nope that's about it, just need to include screenshots and links etc to guide through the flow

**Comment by a8t** [comment]
@reichert621 I see that it's assigned to you, but I could do this if you don't have time.

**Comment by reichert621** [comment]
sure that would be super helpful @a8t!

**Comment by a8t** [comment]
https://github.com/papercups-io/docs/pull/6 @reichert621 please take a look!
