### ISSUE TITLE
Bitdefender Anti-tracker Chrome extension blocks Papercups admin

### ISSUE THREAD

**Issue by jaimeiniesta** [papercups-io/papercups#683]
**Describe the bug**
Bitdefender Anti-tracker Chrome extension blocks Papercups admin

**To Reproduce**
1. Install the Bitdefender extension on https://chrome.google.com/webstore/detail/bitdefender-anti-tracker/khndhdhbebhaddchcgnalcjlaekbbeof
2. Reload Papercups admin
3. See that, as a visitor, the chat widget shows "we're not online at the moment". Also, as an admin you cannot talk to visitors.

**Expected behavior**
It should work with the extension enabled.

**Additional context**
If this can't be fixed, maybe a warning in the README or the website install instructions should let you know that some adblockers can interfere.

**Comment by reichert621** [comment]
thanks for flagging this @jaimeiniesta! btw when you check the extension, does it show anything being blocked other than google analytics for you?

**Comment by jaimeiniesta** [comment]
No, I only see google analytics being blocked...

https://www.dropbox.com/s/lv82thica83fsnp/Captura%20de%20pantalla%202021-03-24%20a%20las%2014.28.53.png?raw=1

**Comment by jaimeiniesta** [comment]
Bitdefender it's definitely making it not work, see this screenshot where I open another incognito window in the back and try to talk to myself, the message notification reaches the admin conversations but the text "hola" is not shown, just "...". And, "my reply" does not reach the other side either.

https://www.dropbox.com/s/8b9zud828y83l8k/Captura%20de%20pantalla%202021-03-24%20a%20las%2014.32.16.png?raw=1

After I disable Bitdefender, everything works fine (except for the lost "my reply" reply):

https://www.dropbox.com/s/z55h10bmq1dnw5i/Captura%20de%20pantalla%202021-03-24%20a%20las%2014.33.12.png?raw=1

**Comment by reichert621** [comment]
@jaimeiniesta just curious, are you still having this issue? (the dashboard should no longer have any cookies, i wonder if that fixes your issue 🤔 )

**Comment by cheeseblubber** [comment]
Closing this feel free to reopen if this is still an issue

**Comment by jaimeiniesta** [comment]
Hey thanks - I just tried and it seems to work fine with Bitdefender enabled! And no cookies were catched! 🚀

**Comment by jaimeiniesta** [comment]
For the record, this happened again. I was unable to reply to conversations from the admin backend until I disabled Bitdefender Antitracker. I finally uninstalled that Chrome Extension :(

**Comment by jaimeiniesta** [comment]
This may have not been caused by Bitdefender anyway - it looks like the web client loses the websockets connection under some circumstances and is not being able to reconnect. As there are no visible warning sign on the page (like a LOST CONNECTION message, or a reload), you may think you're connected but you're not, and your messages are not sent. :(

**Comment by reichert621** [comment]
thanks for letting us know @jaimeiniesta! we may just need to add a notification to refresh the page as a temporary workaround while we figure out the best way to reestablish websocket connections after they're lost 🤔

**Comment by jaimeiniesta** [comment]
Thanks for the notification about connection being lost - it's very useful.

It will be even better if it automatically reconnects - I'm having to refresh the web page a lot of times per day currently.

**Comment by cheeseblubber** [comment]
Thanks @jaimeiniesta we'll be working on the reconnections first thing next week
