### ISSUE TITLE
Proactively send messages to customers from the customer details page

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#688]
**Problem**
Users want to be able to proactively send messages to their customers.

Now that we have a customer details page, let's add this feature there!

**Solution**
Add a modal (or some UI) that enables sending a message to a customer that hasn't started a conversation yet.

**Additional context**
At the moment this feature only exists within the Live Session viewer (with our Storytime feature).

**Testing**
This will require a bit of manual testing.

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by taewookim** [comment]
might be better to just use setTimeout() and pop a chat ANYWAY  with a pre-written message in case of user idling, so that it engages the user

(FYI: im the one who requested this feature on slack chat with Alex)

**Comment by taewookim** [comment]
How do you enable this feature? im using the hosted version of papercups

**Comment by reichert621** [comment]
@taewookim we'll be deploying some updates today :) but here's the general flow:
![proactive-chat-demo](https://user-images.githubusercontent.com/5264279/116591764-3a137000-a8ed-11eb-83c0-4efcb4e5d331.gif)
