### ISSUE TITLE
Having papercups available as an helm chart

### ISSUE THREAD

**Issue by remyleone** [papercups-io/papercups#691]
**Problem**

I would like to install on a kubernetes cluster a running and production ready setup of papercups

**Solution**

I would like to see on your organization a repository such as:

github.com/papercups-io/helm-charts

That contains all the required charts to deploy papercups on a standard Kubernetes
https://helm.sh/docs/topics/charts/

**Describe alternatives you've considered**

- Having it deploy through heroku limit us to a single provider

**Comment by cheeseblubber** [comment]
We have helm charts working https://github.com/papercups-io/charts we just need to get it documented. Let me know if you have any issue or feedback for the helm chart.

**Comment by remyleone** [comment]
Sorry, I was looking for helm charts :) I've missed it. Will take a look and let you know if I encounter an issue.
