### ISSUE TITLE
Support for specifying the customer on the /api/v1/messages endpoint

### ISSUE THREAD

**Issue by matthewhall-ca** [papercups-io/papercups#706]
**Problem**
Wanting to create messages that come from customers programmatically inside an existing Conversation with the REST API

**Solution**
Add support to the /api/v1/messages endpoint to provide a customerId 

**Describe alternatives you've considered**
Implementing the existing websockets system from the widget

**Additional context**
We make a Slack bot called https://chatfox.app/ — We’re using Papercups in our web dashboard side of things but also want to integrate it inside of Slack itself. When someone is having issues they can message us in their Slack and we use the Papercups API + Webhooks to create/update conversations. Which we can then reply to via our Slack in Papercups. Its like a complex Slack to Slack system 

**Testing**
Can you change what customer a message is from? Success

**Comment by reichert621** [comment]
makes sense! thanks for flagging this @matthewhall-ca, we'll update it this week :+1:

**Comment by reichert621** [comment]
hey @matthewhall-ca — we're deploying the update for this right now :+1: let us know if you have any issues with it!

**Comment by matthewhall-ca** [comment]
@reichert621 Working PERFECT! 🎉
