### ISSUE TITLE
Make it possible to disconnect from Gmail integration

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#707]
**Problem**
Right now users can only connect/reconnect to Gmail. Let's add a way for users to disconnect from the integration if they want to.

<img width="1136" alt="Screen Shot 2021-04-05 at 2 51 01 PM" src="https://user-images.githubusercontent.com/5264279/113612911-70c3d680-961e-11eb-9d3f-1c8714204ba6.png">

**Solution**
This will involve a few small tasks on both the frontend and backend:
- Set up a `DELETE /api/google/authorizations/:id` endpoint (see the SlackController and MattermostController for examples of this: https://github.com/papercups-io/papercups/blob/master/lib/chat_api_web/controllers/slack_controller.ex#L137)
- Add a button to the UI that calls this endpoint and refreshes the integrations page (see Slack and Mattermost for examples in the UI: https://github.com/papercups-io/papercups/blob/master/assets/src/components/integrations/IntegrationsTable.tsx#L81-L99)

**Testing**
Please write automated tests for the backend API :) 

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by a8t** [comment]
Thought I'd try this one out. I'm having trouble getting the connection step working locally. I have the Google API key and all that, I'm able to select my email and everything, but it never says Connected. It seems like Google would want to call an endpoint on my localhost to let it know that I authorized? How do I set that up?

**Comment by reichert621** [comment]
ah yeah @a8t the google auth setup is a little annoying... you'd probably need to set up your own project and redirect url, did you do that already?

**Comment by reichert621** [comment]
the easiest way to handle this in the meantime might just be to create a dummy record in the database with fake api keys etc

**Comment by a8t** [comment]
Yeah I set up my own project. I don't think I understand what the redirect url is for, gonna have to read up some docs... I'm guessing I will have to ngrok my local server?

**Comment by a8t** [comment]
gottem 
<img width="915" alt="image" src="https://user-images.githubusercontent.com/7440689/113663951-e9f01780-9678-11eb-8d42-500b6151ab74.png">

had to jump back and forth through the front end code a bit to figure it out. would be good to have some docs for this. for posterity, `redirect_uri = http://localhost:3000/integrations/google` worked
