### ISSUE TITLE
Use server-side pagination for the customer overview page

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#708]
**Problem**
As we've gotten more and more customers in our DB, the customer overview page has gotten slower since we don't paginate the results on the server.

We already have the backend logic to be able to use pagination, but we still need to update the `GET /api/customers` endpoint to actually use it.

**Solution**
- Update the `CustomerController#index` route at `GET /api/customers` to accept pagination params (see https://github.com/drewolson/scrivener_ecto)
- Update the frontend customer table to use server-side pagination (in https://github.com/papercups-io/papercups/blob/master/assets/src/components/customers/CustomersTable.tsx)

**Describe alternatives you've considered**

**Additional context**
We use antd's `Table` component for our table UI -- reference: https://ant.design/components/table

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by fmterrorf** [comment]
Hi @reichert621 👋 I'm interested on working on this one

**Comment by reichert621** [comment]
sounds good @fmterrorf! assigning you 😄

**Comment by fmterrorf** [comment]
I noticed that this search box uses a code from the client https://github.com/papercups-io/papercups/blob/master/assets/src/components/customers/CustomersPage.tsx#L13 to do a text search
![sreenshot](https://user-images.githubusercontent.com/77761194/113786437-5d843a00-96f6-11eb-8b50-831369c690ba.png)

If we start paginating the customers page, we wont have all the customers in the initial request. Should we start implementing this search in the server side first before doing the pagination?

**Comment by reichert621** [comment]
ah good call-out! @fmterrorf for the sake of this ticket, feel free to just hide the search from the UI. we can update it to do the search on the server after this is done :+1: (or just in a separate ticket)

**Comment by fmterrorf** [comment]
Just giving an update for this one :wave: I was able to get it working the `/customers` page. I'm currently getting it to work in the `CompanyDetailsPage` and `TagDetailsPage` since the Customer Table is being used there. Probably going to put it up for PR tomorrow

**Comment by fmterrorf** [comment]
This can be closed now :heart:
