### ISSUE TITLE
Webhook status unchanged after verification

### ISSUE THREAD

**Issue by rahulpat** [papercups-io/papercups#721]
**Describe the bug**
Unverified label is unchanged when a webhook endpoint is verified.

**To Reproduce**
1. Go to https://app.papercups.io/integrations
2. Paste webhooks url in text input
3. Text shows verified! But label remains unchanged.

**Expected behavior**
Label should change to verified.

**Screenshots**

![pap1](https://user-images.githubusercontent.com/848036/113811010-08ddcf00-9789-11eb-94c9-1ea51cfafa19.png)
![pap2](https://user-images.githubusercontent.com/848036/113811014-0aa79280-9789-11eb-925c-9df1b77d8866.png)
![pap3](https://user-images.githubusercontent.com/848036/113811025-0f6c4680-9789-11eb-9bcc-30f85bf68335.png)

**Additional context**

**Comment by reichert621** [comment]
hey @rahulpat! i just tried it out with your webhook url and it seemed to work, just curious if you changed anything since filing this ticket?

did you try removing the event subscription and adding it back again?

**Comment by reichert621** [comment]
ah it seems like the "update" is not working 🤔 but i think if you try removing it and then adding it again, it should work now?

thanks for reporting this!

**Comment by rahulpat** [comment]
Seems to have worked now!

**Comment by reichert621** [comment]
great! i think i understand the issue :+1: thanks again, we'll put out a fix soon!
