### ISSUE TITLE
papercup image on ducker hub

### ISSUE THREAD

**Issue by n1arash** [papercups-io/papercups#73]
I was trying to run the project using docker-compose but there is a problem Papercups image does not exist in the docker hub and it will fail to run.

https://github.com/papercups-io/papercups/blob/master/docker-compose.yml#L5

I believe that we need to build and push the latest image, based on repo tags to the docker hub using Github Actions or any other CI service.

**Comment by reichert621** [comment]
thanks for flagging @n1arash!

@cheeseblubber can you take a look?

**Comment by cheeseblubber** [comment]
Thanks I'll create a docker repository today! If you want to build it locally you can run `docker build . -t papercups` and then `docker-compose` up and you should be able to develop locally

**Comment by cheeseblubber** [comment]
I've uploaded the docker-hub image here! https://hub.docker.com/r/papercups/papercups 

Feel free to reopen if there are any other issues
