### ISSUE TITLE
Papercups is double sending messages 

### ISSUE THREAD

**Issue by cheeseblubber** [papercups-io/papercups#738]
Not sure the best way to reproduce but when sending a message from Slack sometimes it will show up as a double message on the dashboard and to the chatwidget side

<img width="840" alt="Screen Shot 2021-04-15 at 10 48 42 AM" src="https://user-images.githubusercontent.com/4218509/114890639-30f8ae00-9dd9-11eb-8dc7-39ea8ba3cf13.png">
<img width="437" alt="Screen Shot 2021-04-15 at 10 48 37 AM" src="https://user-images.githubusercontent.com/4218509/114890640-3229db00-9dd9-11eb-8190-e380cbc3cd9e.png">

**Comment by reichert621** [comment]
(quick note -- first guess is that slack is doing an automatic retry after N milliseconds... first thing to try would be adding a `sleep` to the webhook handler to see if that reproduces the issue)

**Comment by a8t** [comment]
Is it persisted? If you refresh does it just go away?

**Comment by reichert621** [comment]
@a8t yeah it's persisted -- i was able to repro with the step i mentioned above (slack does an auto-retry after 3s, so if things are slow for some reason this will happen)

i'm working on a fix at the moment!
