### ISSUE TITLE
Update conversation `last_activity_at` when opened/closed

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#747]
**Problem**
If a conversation is closed or reopened, we should update the `last_activity_at` field so that the conversations are sorted properly in the dashboard.

**Testing**
Please write automated tests and test manually.

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by a8t** [comment]
What do you think about putting this inside `ChatApi.Conversations.Conversation.put_closed_at/1` ? Might have to rename it but I think it would wrap this nicely. If that sounds good, I can do this.

**Comment by reichert621** [comment]
@a8t yes that should work! basically just update the `last_activity_at` field to the current timestamp 👍 and please include some unit tests 😄

**Comment by reichert621** [comment]
(i'll assign this one to you for now, otherwise i'll probably pick it up in a couple days because i'd like to get it done by end of week)

**Comment by a8t** [comment]
gotcha, halfway done
