### ISSUE TITLE
Support SMTP for transactional emails 

### ISSUE THREAD

**Issue by cheeseblubber** [papercups-io/papercups#769]
**Problem**
Currently for self hosting some users don't want to use mailgun or a third party service for sending transactional emails. 

**Solution**
We should support SMTP as an integration so the self hosted users can provide their own service. The scope of this feature is purely for sending emails and not receiving.

We should also set the email hosted service based on the environment variable that is being set. 
For example if you set the environment variables: 

SMTP_SERVER
SMTP_HOSTNAME
SMTP_PORT etc.

It should use SMTP as your transactional email provider

These environment variables should be configured in Runtime.exs so that it doesn't get set during the docker build stage

Investigate using:
https://github.com/thoughtbot/bamboo vs building out our own adapters

I am leaning towards using bamboo. It's maintained by thoughtbot and we don't have to build our own adapters. 
There are only [4 dependencies](https://hex.pm/packages/bamboo) for bamboo as well so it wouldn't introduce too many 

**Testing**
** NOTE TO CONTRIBUTORS:
This feature is very manual testing heavy since these transactional email are critical for our users. Please include screenshots of the emails being sent when this is working. For both mailgun and SMTP we don't want to break our existing users (DM Kam on Slack for a Mailgun keys for testing) 

Three features we send transactional emails:
1. When a customer receives a message from customer support and they don't see it after 2 minutes an email gets sent to the users see : https://github.com/papercups-io/papercups/blob/master/lib/workers/send_conversation_reply_email.ex
2. When a company needs to invite a customer in the Accounts/Overview page we send an invitation email. See https://github.com/papercups-io/papercups/blob/master/lib/workers/send_user_invitation_email.ex
3. We send password reset emails 

Also need to make sure these manual end to end tests work for both Mailgun and SMTP

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by fullpwemium** [comment]
Thank you @cheeseblubber 

I would have a go at this myself but my first exposure to Elixir is Papercups.io! 

Amazon SES is my desired service for this

**Comment by cheeseblubber** [comment]
Ok sounds good most likely bamboo seems like the way to go since it would mean supporting SES with minimal work as well.

**Comment by fullpwemium** [comment]
@cheeseblubber that sounds great! Is there any ETA on things like this or could it be months from now?

**Comment by cheeseblubber** [comment]
@fullpwemium it might take a bit if no one from the community wants to take a look at it let me post it this week in our Slack channel on Monday

**Comment by fmterrorf** [comment]
Hi @cheeseblubber :wave: I can have a look at this one! I was testing out sending emails using SMTP on my personal project. I used this [smtp adapter](https://github.com/fewlinesco/bamboo_smtp) and [Sendgrid](https://sendgrid.com/docs/for-developers/sending-email/integrating-with-the-smtp-api/) to test

**Comment by fmterrorf** [comment]
I'm thinking we can do something like this https://github.com/plausible/analytics/blob/master/config/runtime.exs#L135 where we have a `MAILER_ADAPTER` environment variable (Mailgun will be the default adapter since that's the existing code is using). And if users want to use SMTP, they can set the `MAILER_ADAPTER` to `Bamboo.SMTPAdapter`

**Comment by reichert621** [comment]
seems like a good idea @fmterrorf -- i wonder if we should look into moving off Swoosh and using Bamboo instead 🤔

**Comment by fmterrorf** [comment]
We could definitely try looking into that. Bamboo also have a Mailgun adapter

**Comment by fmterrorf** [comment]
Oh wait. I just noticed that Swoosh ships with an SMTP adapter https://hexdocs.pm/swoosh/0.4.0/Swoosh.Adapters.SMTP.html 
Do you think we should stick to Swoosh since we're already using it?

**Comment by fmterrorf** [comment]
Alright i was able to send an email using the Swoosh smtp adapter (using the Sendgrid)! I'll talk to Kam later today to get the Mailgun keys so I can test if sending email using Mailgun still works 
![image](https://user-images.githubusercontent.com/77761194/118198021-5810c280-b40d-11eb-8cf9-2b129d3f29c1.png)

**Comment by reichert621** [comment]
nice! I'd also be curious to explore bamboo if their APIs are better, but if swoosh seems fine in the meantime that's great too 😄

**Comment by fmterrorf** [comment]
This can be closed now 🙏
