### ISSUE TITLE
Keyboard shortcuts modal on dashboard page 

### ISSUE THREAD

**Issue by cheeseblubber** [papercups-io/papercups#770]
Problem:
We have keyboard shortcuts that no one knows about

Solution:
Add a question mark button on top right of sending dashboard to pop a modal with keyboard shortcuts
<img width="826" alt="Screen Shot 2021-04-22 at 4 09 56 PM" src="https://user-images.githubusercontent.com/4218509/115778879-45aee600-a385-11eb-9502-727578e2ab3b.png">

At the moment we support 
`⌘ Enter` - Send a message
`⌘ d` - Close a conversation
`⌘ ↑` - Next conversation
`⌘ ↓` - Previous conversation
`⌘ p` - Mark as prioritize
`Esc ` - Close window/modal

For windows: 
When a user is on windows ⌘ should be replaced with windows button
We should make sure the same set of keys works as well if not open a new PR that supports these shortcuts.

**Comment by chops318** [comment]
Added a PR for this issue [here](https://github.com/papercups-io/papercups/pull/797)
