### ISSUE TITLE
Profile picture not showing up

### ISSUE THREAD

**Issue by cheeseblubber** [papercups-io/papercups#78]
![bug_with_showing_profile_picture](https://user-images.githubusercontent.com/4218509/89374450-46d99f00-d6a0-11ea-8a8f-43687938e493.gif)
![Screen Shot 2020-08-04 at 10 17 00 PM](https://user-images.githubusercontent.com/4218509/89374454-49d48f80-d6a0-11ea-8275-a37861062834.png)

Profile picture shows up in the demo page but doesn't show up when you install it separately on a different app

**Comment by cheeseblubber** [comment]
![bug_with_showing_profile_picture](https://user-images.githubusercontent.com/4218509/89374504-64a70400-d6a0-11ea-97a7-d463c168401a.gif)

**Comment by cheeseblubber** [comment]
Steps to reproduce:
1. Create account
2. add photo url
3. connect widget on your own website
4. Send message from Website
5. Reply to message from app.papercups.io

**Comment by reichert621** [comment]
Fixed in https://github.com/papercups-io/papercups/pull/84
