### ISSUE TITLE
I want to be able to find and filter customers based on customer metadata in the /customers page

### ISSUE THREAD

**Issue by cheeseblubber** [papercups-io/papercups#786]
**Problem**
I want to find customers who are active and ask for feedback. 

**Solution**
I want to filter customers by attributes that you pass in through client side or api and be able to search for the customers.

Example:
{
"plan": "starter",
"last active": 04/26/2021
}

On the /customers page I should be able to filter all `plan` that are starter and `last active` date that is within the last 10 days

**Comment by reichert621** [comment]
Figured out we can do this by doing something like this :) 
```
select * from customers where metadata->>'plan' = 'premium';
```

(For reference: https://thoughtbot.com/blog/querying-embedded-maps-in-postgresql-with-ecto)
