### ISSUE TITLE
Online status disappears after revisiting the page 

### ISSUE THREAD

**Issue by cheeseblubber** [papercups-io/papercups#79]
![Screen Shot 2020-08-04 at 10 33 34 PM](https://user-images.githubusercontent.com/4218509/89375528-b51f6100-d6a2-11ea-9a1d-2841274df284.png)

Refresh the page on the widget the online status disappears and online status doesn't reshow up

**Comment by reichert621** [comment]
@cheeseblubber I think this should be fixed now, can you verify when you get a chance?

**Comment by reichert621** [comment]
closing, feel free to reopen if you still see this happening
