### ISSUE TITLE
Error when trying to run <ChatWidget/> on React Native Expo

### ISSUE THREAD

**Issue by DejiAwoniyi** [papercups-io/papercups#795]
**Describe the bug**
Trying to add papercups chatwidget  causes an error and a blank screen. 

Belos is my code :

`import React from 'react';
import {ChatWidget, ChatWindow, Papercups} from '@papercups-io/chat-widget';
import {StyleSheet, Button, View, Modal, Text} from 'react-native';

const ChatScreen = ({ navigation }) => {

```
  return (
    <View style={{flex: 1, padding: 24}}>
<Text>YAY04</Text>
<ChatWidget
        // Pass in your Papercups account token here after signing up
        accountId='d8ee172b-683f-4d8b-95a1-8bda36a07eb5'
        title='Welcome to Papercups!'
        subtitle='Ask us anything in the chat window below 😊'
        newMessagePlaceholder='Start typing...'
        primaryColor='#13c2c2'
        // Optionally pass in a default greeting
        greeting='Hi there! How can I help you?'
        // Optionally pass in metadata to identify the customer
        customer={{
          name: 'Test User',
          email: 'test@test.com',
          external_id: '123',
          metadata: {version: 1, plan: 'premium'}, // Custom fields go here
        }}
        
        // Add this if you want to require the customer to enter
        // their email before being able to send you a message
        requireEmailUpfront
        // Add this if you want to indicate when you/your agents
        // are online or offline to your customers
        showAgentAvailability
      />
    </View>
  );
}

const styles = StyleSheet.create({
  modal: {
    flex: 1,
    borderRadius: 4,
    overflow: 'hidden',
  },
});
export default ChatScreen;`
```

I have provided the picture of the error below:

![simulator_screenshot_AA8F7C96-63B8-4B55-BC1B-07F4DDD35927](https://user-images.githubusercontent.com/83350689/116418626-3c65c380-a834-11eb-8cee-601b6abbbc45.png)

**Comment by reichert621** [comment]
hey @DejiAwoniyi! thanks for reporting this -- i just pushed a small change, can you see if it fixed anything on your end?

**Comment by DejiAwoniyi** [comment]
> hey @DejiAwoniyi! thanks for reporting this -- i just pushed a small change, can you see if it fixed anything on your end?

Hey @reichert621 no changes here. I got the same error and a blank screen. Anything you want me to change on this end? I really like Papercups and would like to integrate it on my expo app

**Comment by reichert621** [comment]
@DejiAwoniyi no need to change anything on your end -- i was hoping it would be a quick fix, but i'll have to look into it a bit more deeply later. i might not have time today, but i'll keep you posted!

**Comment by DejiAwoniyi** [comment]
> @DejiAwoniyi no need to change anything on your end -- i was hoping it would be a quick fix, but i'll have to look into it a bit more deeply later. i might not have time today, but i'll keep you posted!

@reichert621 Ok no problem. I'll keep a look out for it.

**Comment by DejiAwoniyi** [comment]
@reichert621 hey just checking if there was any progress on this. I want to give feedback to the dev team. Sorry to bother. I'm a bit of a noob with RN and papercups

**Comment by reichert621** [comment]
Hey @DejiAwoniyi not yet! It's been a bit of a busy week, so might not get to this until week. I'll let you know when we're working on this!

**Comment by DejiAwoniyi** [comment]
Hi @a8t thanks a million for your wholistic explanation. I actually used the RN widget you provided there but I got the error below. Is it because I have react native WebView elsewhere? IS there a way I can have both? I use webview to pop up and show the terms and conditions of the app.
![Simulator Screen Shot - iPhone 12 mini - 2021-04-29 at 18 42 40](https://user-images.githubusercontent.com/83350689/116594971-b53f4b00-a91a-11eb-9bfb-e02a21aa446b.png)
 with the same name RNCWebView"

**Comment by reichert621** [comment]
@DejiAwoniyi do any of the solutions in this thread help? https://github.com/react-native-webview/react-native-webview/issues/373

**Comment by DejiAwoniyi** [comment]
Hi @reichert621 none have worked but i did realise that when I tried to run `npm ls react-native-webview` under one of the solutions I got the following. I'm guessing that means two versions of RNCwebView are being registered somewhere:

```
calebawoniyi@Calebs-MBP MPC % npm ls react-native-webview
/Users/calebawoniyi/Desktop/Code/MPC
├─┬ @papercups-io/chat-widget-native@1.0.3
│ └── react-native-webview@10.10.2 
└── react-native-webview@9.4.0 
```

**Comment by a8t** [comment]
Can you share your package.json and package.lock?

**Comment by DejiAwoniyi** [comment]
@a8t I have just updated my expo with `expo update` following the final instruction in that thread. After that, my package.json and package.lock are like this : 

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@expo-google-fonts/inter": "^0.1.0",
    "@mdi/font": "^5.8.55",
    "@papercups-io/chat-widget-native": "^1.0.3",
    "@react-native-async-storage/async-storage": "^1.13.0",
    "@react-native-community/datetimepicker": "3.2.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/picker": "1.6.0",
    "@react-native-community/progress-bar-android": "^1.0.4",
    "@react-native-community/progress-view": "^1.2.3",
    "@react-native-firebase/app": "^10.3.0",
    "@react-native-firebase/auth": "^10.3.1",
    "@react-navigation/bottom-tabs": "^5.11.2",
    "@react-navigation/native": "^5.8.10",
    "@react-navigation/stack": "^5.12.8",
    "axios": "^0.20.0",
    "expo": "^41.0.0",
    "expo-font": "~9.1.0",
    "expo-status-bar": "~1.0.4",
    "expo-updates": "~0.5.4",
    "firebase": "8.2.3",
    "firechat": "^3.0.1",
    "link": "^0.1.5",
    "package": "^1.0.1",
    "pdfkit": "^0.11.0",
    "pdfmake": "^0.1.70",
    "react": "16.13.1",
    "react-confirm-alert": "^2.7.0",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz",
    "react-native-confirm-dialog": "^0.1.0",
    "react-native-date-picker": "^3.2.10",
    "react-native-dev-menu": "^4.0.2",
    "react-native-dropdown-picker": "^4.0.2",
    "react-native-elements": "^2.3.2",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-html-to-pdf": "^0.9.1",
    "react-native-ionicons": "^4.6.5",
    "react-native-keyboard-aware-scrollview": "^2.1.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-onboarding-swiper": "^1.1.4",
    "react-native-paystack": "^3.4.0",
    "react-native-paystack-webview": "^3.2.1",
    "react-native-pdf": "^6.2.2",
    "react-native-reanimated": "~2.1.0",
    "react-native-safe-area-context": "3.2.0",
    "react-native-screens": "~3.0.0",
    "react-native-super-grid": "^4.1.1",
    "react-native-vector-icons": "^7.1.0",
    "react-native-web": "~0.13.12",
    "react-native-webview": "11.2.3",
    "react-navigation": "^4.4.0",
    "react-navigation-stack": "^2.8.2",
    "react-navigation-tabs": "^2.9.0",
    "rn-fetch-blob": "^0.12.0"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "babel-preset-expo": "8.3.0"
  },
  "private": true
}

```

Package.lock :  

```
    "@papercups-io/chat-widget-native": {
      "version": "1.0.3",
      "resolved": "https://registry.npmjs.org/@papercups-io/chat-widget-native/-/chat-widget-native-1.0.3.tgz",
      "integrity": "sha512-AXNl9YjaTvThBhvb8+n/t0Jn6MBntBoCDzsE2uGGbyuQ8z9uqAYN4cAuVG8n6ruR7Id9lKZK3tuVqwFIwWae0A==",
      "requires": {
        "query-string": "^6.13.1",
        "react-native-webview": "^10.6.0"
      },
      "dependencies": {
        "react-native-webview": {
          "version": "10.10.2",
          "resolved": "https://registry.npmjs.org/react-native-webview/-/react-native-webview-10.10.2.tgz",
          "integrity": "sha512-98Dh7q1gEflicFZ8KNL3nK5XRjx50OZXqw87jHofVjKfjbK0LKmvI5X8ymgUMGg61JVgI3AF+g8qpDvqjgQsfg==",
          "requires": {
            "escape-string-regexp": "2.0.0",
            "invariant": "2.2.4"
          }
        }
      }
    },

  "react-native-webview": {
      "version": "11.2.3",
      "resolved": "https://registry.npmjs.org/react-native-webview/-/react-native-webview-11.2.3.tgz",
      "integrity": "sha512-r/K+Lf/O5aij72gRndMX2qsyQ/WLtDPiO75SS57y6JjqSKxedGASVL9Jwl1TM7fCXqUq8dgiwik/LuBHbJXAEg==",
      "requires": {
        "escape-string-regexp": "2.0.0",
        "invariant": "2.2.4"
      }
    },
```

The issue now is that the app doesn't even start: 
![simulator_screenshot_E33A50BF-2E97-463C-8BEA-1B5CF4492B73](https://user-images.githubusercontent.com/83350689/116704792-b4162880-a9c3-11eb-88c1-b9b363a8e340.png)

**Comment by DejiAwoniyi** [comment]
Solved it! Thank God! Had to get the `react-native-web-view `version to at least `10.6.0 `
