### ISSUE TITLE
Add support for webhooks

### ISSUE THREAD

**Issue by gdandersson** [papercups-io/papercups#80]
Support for some kind of (web)hooks, for example when a chat is initiated and perhaps email has been entered, initiate hook which might return a list of orders from that customer (visible to the agents only, of course).

Or whenever a message is sent/received, a hook could look at the message and provide additional data (a simple regexp on the message might detect order numbers (x characters long and only numbers) which could then provide the agent with a direct URL to the order in the (ecommerce) backend.

**Comment by cheeseblubber** [comment]
Thanks for opening the issue! Which event would be the most useful to you? This way we can prioritize these and break them down to smaller chunks. Also is there a specific production use case you are interested in for your website?

**Comment by gdandersson** [comment]
If email is required to start chat, then that. Customer clicks on chat icon, enters email and "chat" -> webhook is fired.

The use case we'd love to use is looking up orders in our ecommerce system, so that agents quicker can see the order(s) the customer most likely will ask about.

So webhook of https://ecommerce.com/webhooks/papercups?email=a@b.com returns
1234 https://ecommerce.com/backend/order?id=1234
2543 https://ecommerce.com/backend/order?id=2543
(which agent sees)

.. for example. Makes sense?

**Comment by reichert621** [comment]
great idea @gdandersson! makes a lot of sense.

for this to be useful for you, it sounds like we would need to do the following:
- when a new conversation is started (or a customer is created/updated), send a webhook event with the customer data (e.g. email, etc) in the form of a `POST` request to your webhook endpoint
- your endpoint would pick up the event, and query the customer's order data
- what do we do with that data? 
  - one idea: we let you add that data to the `conversation` in the form of a tag or internal note, so agents can see it alongside the conversation. we do this by exposing an API endpoint that allows you to set this metadata/note/whatever programmatically
  - or, did you have something else in mind? just want to make sure i understand :)

**Comment by gdandersson** [comment]
In my world (with XMPP), I assume the hook is async so when data is returned, it's added as a message/internal note which is only sent to the agent.

I don't think any API endpoints to be exposed for this feature. I'm thinking a HTTP request to a specified URL and whatever is returned, is added as this note/message.

Guessing it could be more advanced with the answer having to be in some json/xml/whatever format. I'm just looking for a simple way of adding links to order(s) that my agents are dealing with.

**Comment by reichert621** [comment]
gotcha, so just setting up a webhook event to be fired off via HTTP request to a specified URL when a conversation is started will be good enough for now?

**Comment by gdandersson** [comment]
As long as the returned data is sent to the agent as a message or shown somehow.

**Comment by reichert621** [comment]
gotcha -- in that case, I think the best way to do that would be via an API endpoint we expose :)

**Comment by reichert621** [comment]
@gdandersson basic support for webhooks is done :) see the docs: https://github.com/papercups-io/papercups/wiki/Event-Subscriptions-with-Webhooks

**Comment by gdandersson** [comment]
Blimey, very very nice!
