### ISSUE TITLE
Slack notification preview should show some information 

### ISSUE THREAD

**Issue by cheeseblubber** [papercups-io/papercups#804]
Right now the notification doesn't show any information we should allow it to show email + a snippet of the first few words of the message

<img width="332" alt="Screen Shot 2021-05-03 at 11 15 39 AM" src="https://user-images.githubusercontent.com/4218509/116895371-21fb6380-ac01-11eb-904c-1949bef40ebc.png">

**Comment by reichert621** [comment]
This might be relevant: https://stackoverflow.com/questions/56317962/message-notifications-produce-this-content-cant-be-displayed

May need to just add a "text" field above this line: https://github.com/papercups-io/papercups/blob/master/lib/chat_api/slack/helpers.ex#L847
