### ISSUE TITLE
Remove internal note link in slack messages

### ISSUE THREAD

**Issue by sidujjain** [papercups-io/papercups#828]
**Describe the bug**
Internal note link points to a Github pull request and expands every time there is a new slack message.

**To Reproduce**
1. Do slack integration on Papercups
2. Send a chat message from Papercups widget
3. See Github PR link preview in the slack channel

**Expected behavior**
The link should either be removed or point to a private link that doesn't show preview in Slack. 

**Screenshots**
![image](https://user-images.githubusercontent.com/2552115/117617050-9dbd5900-b189-11eb-9202-f52e6d12b138.png)
![image](https://user-images.githubusercontent.com/2552115/117617072-a746c100-b189-11eb-94d6-6607f4d56572.png)

**Comment by cheeseblubber** [comment]
Hey can you try uninstall and reinstall the Papercups app? If you are still having issues I can email you and schedule a call to debug it

**Comment by cheeseblubber** [comment]
Btw are you on self hosted or cloud version?

**Comment by reichert621** [comment]
this should be resolved now, but feel free to reopen if you're still seeing this issue!
