### ISSUE TITLE
Fix how extra users are handled if subscription plan changes

### ISSUE THREAD

**Issue by ranjit-git** [papercups-io/papercups#847]
Hello, @reichert621 , @cheeseblubber , @rhonsby  - a potential high severity security vulnerability has been  disclosed to huntr .
Report url --> https://www.huntr.dev/bounties/2-other-papercups-io/papercups/

BUG
=======
Bypass payment verification and add more user 

IMPACT
========
Free tier allow only to user for your team .
But it can be bypassed .

STEP TO REPRODUCE
====================
1. From your admin account goto https://app.papercups.io/account/team and add user B as normal user .
   So, currently there is two active user in you account .
2. Now admin try to add more user but he cant . Admin need to buy subscriptions to more than two user .

3. Now admin bypass this payment using bellow method .

   a)Admin disabled user B temporarily .So, there is currently 1 active user .

   b) Now admin generate a new invite url . Invite url look like ```https://app.papercups.io/register/c6babc3f-a4cc-4661-8a40-e0e2732f1752``` .
      Using this invitation url admin added one more user .
      So, currently there is 2 active user .

   c) Now admin again enabled user B .
       So, now admin has 3 active user . 
     So, Using this method admmin bypassed payment and added more than two users in his account .

SUGGESTED FIX
===============
It should be checked users current limit when enabling disabled user .

**Comment by cheeseblubber** [comment]
Not a security vulnerability closing
