### ISSUE TITLE
Email notifications for support responses?

### ISSUE THREAD

**Issue by Blakeinstein** [papercups-io/papercups#857]
**Problem**
The customer will never know if someone has acknowledged and responded to their query once they go offline.

**Solution**
The customer should get an email notification, when they are not active/online.

**Comment by cheeseblubber** [comment]
Hey @Blakeinstein we do have this feature it isn't documented well. When a user misses a message sent from Papercups it automatically emails them if the email address is present after 10 minutes. We probably want to cc the user who sent it to make it more apparent
