### ISSUE TITLE
adding a member to the team

### ISSUE THREAD

**Issue by s16914** [papercups-io/papercups#862]
**Describe the bug**
when the logged in user clicks on the link, the registration window is displayed. when clicking on the login option, the user is logged in immediately, but not added to the team.

**To Reproduce**
Initial conditions: The user has a link redirecting to the team's website and an active account
Steps:
1. The tester clicks on the following link: https://app.papercups.io/register/01047958-f67e-4a51-9cd3-873025fa4454
2. The tester clicks the Log in button
3. The tester enters the correct login and password
2. Expected Result:
the tester joins the team

**Expected behavior**
the tester joins the team

**Comment by reichert621** [comment]
hey @s16914, how many users do you have on your account so far? if you already have 2, you need to upgrade your subscription before you can add more
