### ISSUE TITLE
Set up `lambdas` model

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#873]
**Problem**
We want to persist lambda functions that our users set up for e.g. scripting and webhook event handlers.

Let's just call the new table `lambdas` for now?

**Solution**
Set the boilerplate for a `lambdas` table with the following fields:
- `name` (`string`): the name/title of the function 
- `description` (`string`): a description of what the function does
- `code` (`text`): the code for the function
- `language` (`string`): the language of the code (e.g. for now it will always be `"javascript"`)
- `runtime` (`string`): the language runtime (e.g. `"nodejs14.x"`)
- `url` (`string`): the url that the function lives at (e.g. on aws lambda)
- `status` (`string`): an enum of `active`/`inactive` (maybe `pending_deployment` as well?) which will determine if the function should be run
- `last_deployed_at` (`utc_datetime`): the timestamp of the last deployment (e.g. to aws lambda)
- `last_executed_at` (`utc_datetime`): the timestamp of the last time the function was executed
- `inserted_at`/`updated_at` (default timestamps included by phoenix)
- `metadata` (`map`): ad hoc metadata (e.g. maybe if we want to play around with runkit, we can store the runkit endpoint here?)

AWS-specific fields:
- `lambda_function_name` (`string`): the unique function name on AWS (see below)
- `lambda_function_handler` (`string`): the handler path of the function (we may just start off keeping this consistent for everyone in the beginning)
- `lambda_revision_id` (`string`): the latest revision ID of the function (see below)
- `lambda_last_update_status` (`string`): the status of the last update (e.g. "Successful", see below)

**Describe alternatives you've considered**
Still not sure what the best name for this table is, but we can always rename it later?

**Additional context**
This should ultimately live in the enterprise edition

**Testing**
Please write automated tests for the boilerplate modules!

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by cheeseblubber** [comment]
Here is an example of the json dump that AWS returns:
{
  "CodeSha256" => "SOME SHA",
  "CodeSize" => 1360,
  "DeadLetterConfig" => nil,
  "Description" => "",
  "Environment" => nil,
  "FileSystemConfigs" => nil,
  "FunctionArn" => "arn:aws:lambda:AWS_REGION:AWS_ACCOUNT_ID:function:UNIQUE_FUNCTION_NAME",
  "FunctionName" => "UNIQUE_FUNCTION_NAME",
  "Handler" => "FOLDER_NAME.FILE_NAME.FUNCTION",
  "ImageConfigResponse" => nil,
  "KMSKeyArn" => nil,
  "LastModified" => "2021-06-11T15:00:40.182+0000",
  "LastUpdateStatus" => "Successful",
  "LastUpdateStatusReason" => nil,
  "LastUpdateStatusReasonCode" => nil,
  "Layers" => nil,
  "MasterArn" => nil,
  "MemorySize" => 128,
  "PackageType" => "Zip",
  "RevisionId" => "a2416332-01f3-4f6c-956e-114502d224a7",
  "Role" => "arn:aws:iam::AWS_ACCOUNT_ID:role/AWS_ROLE",
  "Runtime" => "nodejs14.x",
  "SigningJobArn" => nil,
  "SigningProfileVersionArn" => nil,
  "State" => "Active",
  "StateReason" => nil,
  "StateReasonCode" => nil,
  "Timeout" => 3,
  "TracingConfig" => %{"Mode" => "PassThrough"},
  "Version" => "$LATEST",
  "VpcConfig" => nil
}
