### ISSUE TITLE
Embedding email in slack with long message overflows the string

### ISSUE THREAD

**Issue by cheeseblubber** [papercups-io/papercups#88]
![Screen Shot 2020-08-05 at 8 47 09 PM](https://user-images.githubusercontent.com/4218509/89488441-e0668680-d75c-11ea-807b-805cbd7f96fe.png)
![Screen Shot 2020-08-05 at 8 45 59 PM](https://user-images.githubusercontent.com/4218509/89488449-e9575800-d75c-11ea-987d-4040fb5bc3a8.png)

**Comment by reichert621** [comment]
There are two things we need to fix here:
- supporting better formatting for links like this that get sent from slack
- handling long text overflowing (this is just a matter of tweaking some css)

**Comment by reichert621** [comment]
(fixed in https://github.com/papercups-io/chat-window/commit/fef4c7106ef59673b7a4e7722092a5fc33c8c724)
