### ISSUE TITLE
Incorrect link rendering in Papercups emails

### ISSUE THREAD

**Issue by sidujjain** [papercups-io/papercups#903]
**Describe the bug**
If you send any link to the user from Slack, it gets incorrectly rendered in emails received by the user

**To Reproduce**
1. Initiate a conversation using the chat widget and close the tab
2. Reply to message from Slack and send any link
3. Wait for the message to arrive in email and check the link

**Expected behavior**
The link should be rendered correctly in email

**Screenshots**
![image (8)](https://user-images.githubusercontent.com/2552115/124377919-45f42780-dccc-11eb-91ce-ce4faa383d2a.png)

**Additional context**
It causes confusion and users complaining about broken links

**Comment by reichert621** [comment]
thanks for flagging this! looks like the markdown is being parsed incorrectly for emails -- we'll take a look 👍
