### ISSUE TITLE
When responding from slack show 🙂  instead of :slight_smily_face 

### ISSUE THREAD

**Issue by cheeseblubber** [papercups-io/papercups#92]
When you send emoji from slack it shows up as string instead of emoji 
![Screen Shot 2020-08-05 at 10 13 35 PM](https://user-images.githubusercontent.com/4218509/89493411-ed897280-d768-11ea-8afb-193b4e29e866.png)

**Comment by lukewaring** [comment]
Hi Alex and Kam, I saw your launch on HN and am really excited about what you're building! I'm new to Elixir and have been looking for a project. I'd love to take a crack at this issue. Is there anything else I should be aware of before diving in? Thank you!

**Comment by reichert621** [comment]
hey @lukewaring! would love it if you contributed 😄 

I just realized this ticket is actually done already, but let me know if you need help finding a good one to start with!

btw have you already gotten your development environment set up? feel free to ping us on slack if you need any help getting started https://github.com/papercups-io/papercups#get-in-touch

**Comment by lukewaring** [comment]
Hi @reichert621 thanks for the update! I think I'm set on my environment. I should have some more time later this week to take a closer look at the open issues. I'm happy to work on the front or backend. I'll touch base with you on slack with any questions. Thanks!
