### ISSUE TITLE
Future pricing model for the hosted version?

### ISSUE THREAD

**Issue by shunkakinoki** [papercups-io/papercups#93]
Hi papercups!!!
came from HN, and I just LOVE your work
just wanted to say thanks for democratizing chat widgets, really means a lot for the internet community in general honestly

I just wanted to inquire about the pricing model for the hosted version, since I'm looking to migrate from Hubspot.
Is there a general ballpark on how much the hosted version will cost a month for the enterprise?
Thanks!

**Comment by cheeseblubber** [comment]
Hi the pricing model for the near future is free for two seats/accounts and 15 dollars per additional user. We are thinking of adding more features and charging differently based on usage. We're new at pricing so theres a lot of things we're gonna experiment with but we intend to grandfather users who sign up with us now with the current price.
