### ISSUE TITLE
Prompt to collect email at the beginning of the conversation

### ISSUE THREAD

**Issue by cheeseblubber** [papercups-io/papercups#96]

**Comment by masonhensley** [comment]
... should skip if it's provided in the metadata.

Related to #128

**Comment by reichert621** [comment]
need to update the docs, but this should be possible now with the `requireEmailUpfront` prop: https://github.com/papercups-io/chat-widget/blob/master/src/components/EmbeddableWidget.tsx#L52

(will do some additional testing before closing this)

**Comment by cheeseblubber** [comment]
Been merged in to master for a month closing now
