### ISSUE TITLE
Adding a link to the away message

### ISSUE THREAD

**Issue by johncadengo** [papercups-io/papercups#986]
I noticed that on papercup's landing page, there is a link in the away message.

![Screen Shot 2021-10-12 at 8 35 09 PM](https://user-images.githubusercontent.com/561587/137065367-6c277a0b-498f-49d7-a8e7-fde603febb81.png)

I tried doing that on my own away message, just using html, and it did not come through. Is there a way to add a link to the away message?

**Comment by reichert621** [comment]
hey @johncadengo! you can do this with markdown, e.g. `[demo](https://app.papercups.io/demo)` (https://github.com/papercups-io/papercups.io/blob/5c8494f4a6edae5b61165462120c6a1d764447ca/pages/index.tsx#L488)

**Comment by johncadengo** [comment]
Oh, thank you! That wasn't clear to me earlier, but great solution. 👍
