### ISSUE TITLE
Mark as unread

### ISSUE THREAD

**Issue by pauldambra** [papercups-io/papercups#991]
**Problem**

I've been using Papercups for the first time this week. What an awesome tool! Keeping my in synch between Slack and Email. 

I click into a new message to see if I should prioritise it, discover I don't need to, and then there's no way (that I know of) to mark it as something I should come back to

**Solution**

So... I keep wishing I could mark things as unread in the paper cups app. I could look at the message, decide I don't need to act right away, and then mark it as unread. 

**Describe alternatives you've considered**

Keeping a separate to-do list.

**Additional context**
Add any other context, screenshots, or related issues about the feature request here.

**Testing**
Describe how this should be tested.

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by reichert621** [comment]
good idea @pauldambra!
